### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mjafin** [ndaniel/fusioncatcher#1]
Hi Daniel,
I'm trying to install fusioncatcher but am bumping into errors. First of all, our firewall seems to break the ensembl download so I had to resort to downloading files locally and then running the ``--local`` install. I get to liftOver and then hit an error:
```
Checking latest version of Ensembl database that is available...
2015-01-06 15:33:39 URL: ftp://ftp.ensembl.org/pub/ [6774] -> ".listing" [1]
   * Not found! (WARNING: Is the internet connection working?)
Obtaining the absolute path of the Python executable...
  * Ok! '/home/klrl262/miniconda/envs/fusioncatcher/bin/python' found!
Python used for installation of FusionCatcher: '/home/klrl262/miniconda/envs/fusioncatcher/bin/python'
Checking Python version...
  * Ok! Found Python version: 2.7
Checking if this environment is a 64-bit environment...
  * Ok! 64-bit environment found.

Installing FusionCatcher from <http://code.google.com/p/fusioncatcher/>
------------------------------------------------------------------------

Path for installation of FusionCatcher: '/home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher'
Installing tool 'FusionCatcher (fusion genes finder in RNA-seq data)' at '/home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/bin' from './fusioncatcher_v0.99.3e.zip'
    # mkdir -p /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher
    # rm -rf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/fusioncatcher_v0.99.3e.zip
    # cp ./fusioncatcher_v0.99.3e.zip /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher
    # rm -rf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/bin
    # rm -rf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/fusioncatcher_v0.99.3e
    # unzip -o /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/fusioncatcher_v0.99.3e.zip -d /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher
    # ln -s /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/fusioncatcher_v0.99.3e /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/bin
    # chmod -R +rx /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/bin
  * Done!
Checking if the Python module named 'NumPy' is installed...
  * Ok! Python module 'NumPy' found at '/home/klrl262/miniconda/envs/fusioncatcher/lib/python2.7/site-packages/numpy'!
Checking if the Python module named 'BioPython' is installed...
  * Ok! Python module 'BioPython' found at '/home/klrl262/miniconda/envs/fusioncatcher/lib/python2.7/site-packages/Bio'!
Checking if the Python module named 'Xlrd' is installed...
  * Ok! Python module 'Xlrd' found at '/home/klrl262/miniconda/envs/fusioncatcher/lib/python2.7/site-packages/xlrd'!
Checking if 'BOWTIE (short read aligner)' is installed...
  * WARNING: Not found!
Installing tool 'BOWTIE (short read aligner)' at '/home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie' from './bowtie-1.1.1-linux-x86_64.zip'
    # mkdir -p /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools
    # rm -rf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie-1.1.1-linux-x86_64.zip
    # cp ./bowtie-1.1.1-linux-x86_64.zip /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools
    # rm -rf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie
    # rm -rf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie-1.1.1-linux-x86_64
    # unzip -o /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie-1.1.1-linux-x86_64.zip -d /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools
    # rm -rf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie-1.1.1-linux-x86_64
    # mv /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie-1.1.1 /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie-1.1.1-linux-x86_64
    # ln -s /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie-1.1.1-linux-x86_64 /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie
    # chmod -R +rx /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie
  * Done!
Checking if 'BOWTIE2 (short read aligner)' is installed...
  * WARNING: Not found!
Installing tool 'BOWTIE2 (short read aligner)' at '/home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie2' from './bowtie2-2.2.4-linux-x86_64.zip'
    # mkdir -p /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools
    # rm -rf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie2-2.2.4-linux-x86_64.zip
    # cp ./bowtie2-2.2.4-linux-x86_64.zip /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools
    # rm -rf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie2
    # rm -rf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie2-2.2.4-linux-x86_64
    # unzip -o /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie2-2.2.4-linux-x86_64.zip -d /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools
    # rm -rf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie2-2.2.4-linux-x86_64
    # mv /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie2-2.2.4 /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie2-2.2.4-linux-x86_64
    # ln -s /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie2-2.2.4-linux-x86_64 /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie2
    # chmod -R +rx /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/bowtie2
  * Done!
Checking if 'NCBI SRA Toolkit (sequence assembler for short reads)' is installed...
  * WARNING: Not found!
Installing tool 'NCBI SRA Toolkit (sequence assembler for short reads)' at '/home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/sratoolkit' from './sratoolkit.2.3.5-2-centos_linux64.tar.gz'
    # mkdir -p /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools
    # rm -rf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/sratoolkit.2.3.5-2-centos_linux64.tar.gz
    # cp ./sratoolkit.2.3.5-2-centos_linux64.tar.gz /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools
    # rm -rf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/sratoolkit
    # rm -rf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/sratoolkit.2.3.5-2-centos_linux64
    # tar --overwrite -xvzf /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/sratoolkit.2.3.5-2-centos_linux64.tar.gz -C /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools
    # ln -s /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/sratoolkit.2.3.5-2-centos_linux64 /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/sratoolkit
    # chmod -R +rx /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/fusioncatcher/tools/sratoolkit
  * Done!
Checking if 'LiftOver (Batch Coordinate Conversion)' is installed...
  * Found at '/home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat'!
Traceback (most recent call last):
  File "bootstrap.py", line 1256, in <module>
    install = options.install_all or options.install_all_tools)
  File "bootstrap.py", line 791, in tool
    exit = False)
  File "bootstrap.py", line 360, in test_tool
    flag,r = cmd([[[exe,param],False]], exit = False, verbose = False)
  File "bootstrap.py", line 442, in cmd
    p = subprocess.Popen(c0, stdout = subprocess.PIPE, stderr = subprocess.STDOUT, shell = c1)
  File "/home/klrl262/miniconda/envs/fusioncatcher/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/home/klrl262/miniconda/envs/fusioncatcher/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
Could you make erroring out more verbose? Would be great to know which command causes the failing.

Further, it looks like bootstrap.py always tries to connect to Ensembl(?) as its very first step, doesn't know how to use a proxy and just waits for a long time before timing out (see first three lines above). 

Thanks,
Miika

**Comment by ndaniel** [comment]
Hi Mika!

thanks for reporting this bug!

> First of all, our firewall seems to break the ensembl download so I 
> had to resort to downloading files locally and then running the --local install.

Ok.

> I get to liftOver and then hit an error:

Indeed it looks like the error is somehow related to installing/accessing liftOver. I have tried to replicate your bug but I was unable. Therefore I would need more info, like for example:

1) which "boostrap.py" are you using? The one from sf.net or the one from github? I suggest to use the one from sf.net because on github is available a development version of FusionCatcher which is not stable.

2)  "bootstrap.py" reports that "liftOver" is here: "/home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/liftOver". Is it really there? Also, do the permissions of "/home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/liftOver" allow to be execute by the current process/user which is running  "boostrap.py"?

> Could you make erroring out more verbose? 

Yes.

> Would be great to know which command causes the failing.

True. There the error says "OSError: [Errno 2] No such file or directory". This might suggest that bootstrap.py is not able to access/execute "/home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/liftOver"

> It looks like bootstrap.py always tries to connect to Ensembl(?) as its very first 
> step, doesn't know how to use a proxy and just waits for a long time before 
> timing out (see first three lines above).

Indeed "boostrap.py" tries to connect to Ensembl and for this is using the linux command "wget". If wget does not know to access the access the internet using proxy then "bootstrap.py" will not know either. Therefore setting up such that wget works with your proxy on your system might be a solution. Anyway, "bootstrap.py" tries to connect to Ensembl server and after few seconds it will figure out that it cannot and it will proceed further with a warning message and this will not affect in any way the installation process. It is just a warning.

Cheers,
Daniel

**Comment by mjafin** [comment]
Hi Daniel,
Thanks for the prompt reply. Our firewall lets ``wget`` through under normal circumstances. I wonder how it's being called by fusion catcher? 

I followed the installation instructions here https://code.google.com/p/fusioncatcher/wiki/Manual i.e. pulled ``bootstrap.py`` from SourceForge. 

``/home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/liftOver`` exists and has execute flag for 'all'. 

I can't get past this point but I'll create a new python environment and will try again from scratch.

**Comment by ndaniel** [comment]
Hi Mika!

> /home/klrl262/miniconda/envs/fusioncatcher/bin/fuscat/liftOver exists and has execute flag for 'all'.

It should not have execute flag!
Please, try `chmod -x *` before trying again!

Cheers,
Daniel

**Comment by mjafin** [comment]
Thanks Daniel, that got me through to the end of the install.. I'll let you know if anything else comes up

**Comment by ndaniel** [comment]
Great! Daniel

**Comment by mjafin** [comment]
One more quick q., does fusioncatcher build its own star/bowtie/bt2 indices or do I need to give it prebuilt ones?

**Comment by mjafin** [comment]
Oh, and does it make use of multiple cores? I'm thinking of how to submit the jobs to SGE/Slurm

**Comment by ndaniel** [comment]
FusionCatcher is building its own pre-built indexes and database files (Ensembl, UCSC, RefSeq, etc.).

The easy way for human is to download everything (all four files) what FusionCatcher needs from here:
https://sourceforge.net/projects/fusioncatcher/files/data/
and use the mega.sh file afterwards. For more see: https://code.google.com/p/fusioncatcher/wiki/Manual#4.3_-_Semi-automatic_installation

The challening way is to build your own indexes and and download all the files from over 15 databases used by FusionCatcher by running `fusioncatcher-build.py`. Here is more at section "5.2.2 - Building yourself the organism's build data" from: https://code.google.com/p/fusioncatcher/wiki/Manual#5.2_-_Organism's_build_data

**Comment by ndaniel** [comment]
The script for finding fusion genes, that is `fusioncatcher.py`, is taking advantage of multiple cores/CPUs!

The script for building indexes and downloading database files, that is `fusioncatcher-build.py` does not take advantage of multiple cores.

**Comment by mjafin** [comment]
Daniel, is there a way to control the number of CPUs it uses locally? Otherwise it'll be difficult to integrate it with a scheduler.

**Comment by ndaniel** [comment]
> Daniel, is there a way to control the number of CPUs it uses locally? 

Yes, of course! Command option: "--threads" is for this. By running `fusioncatcher.py --help` one may see all the command line options. Also the command line options are shown in the manual: https://code.google.com/p/fusioncatcher/wiki/Manual#8.1_-_Command_line

**Comment by mjafin** [comment]
Thanks! Should've read the manual
