### ISSUE TITLE
URL redirection issues when downloading from Ensembl biomart

### ISSUE THREAD

**Issue by amirkdv** [ndaniel/fusioncatcher#100]
Currently when one runs `fusioncatcher-build.py` all the places where we try to access Ensembl biomart API are silently failing, for example:

```
# gert_exons_positions.py as called by fusioncatcher-build.py
$ bin/get_exons_positions.py --server www.ensembl.org --organism homo_sapiens --threshold_length 150 --output data/v93/
Starting...
Get lists of chromosomes...
Downloaded:      0.01 MB
FINISHED downloading:      0.01 MB # not correct, the actual data is 1.25 MB

End.
$ echo $?
0 # success?
$ du data/v93/exons.txt
0       data/v93/exons.txt # empty!
```

I have debugged this and I have identified the issue(s) and it turns out this is a problem with Ensembl servers. Sorry for the long post, I have documented the issue, its cause, and possible solutions.

**Comment by amirkdv** [comment]
#### relevant pieces of code

All the places where requests are sent to biomart are affected. The good news is that they all have a similar code using `urllib2` which can be fixed in one go.

```sh
$ grep -rl martservice fusioncatcher/bin/
fusioncatcher/bin/get_trna.py
fusioncatcher/bin/get_genes_descriptions.py
fusioncatcher/bin/get_hla2.py
fusioncatcher/bin/get_refseq_ensembl.py
fusioncatcher/bin/get_paralogs.py
fusioncatcher/bin/get_biotypes.py
fusioncatcher/bin/get_mtrna.py
fusioncatcher/bin/get_exons_positions.py
fusioncatcher/bin/get_rrna.py
```

The relevant snippet of code for access to biomart API is like this (same in master as in official release on sourceforge):

```python
query = ... # some XML query
headers = ... # some HTTP headers
data = urllib.urlencode({"query" : query})
server = "http://%s/biomart/martservice" % (options.server,)
# ^ options.server defaults to www.ensembl.org
try:
    req = urllib2.Request(server,mydata1,headers)
    page = urllib2.urlopen(req, timeout = 30)
    ... # other things
catch:
    ... # error handling
```

#### `POST` queries are not redirected correctly to mirror

* According to biomart docs we can either submit [`GET`](http://www.biomart.org/martservice.html) requests with the XML query put in the query string, or [`POST`](http://www.biomart.org/martservice_9.html) requests with XML query as data.  Currently, `fusioncatcher` is using `POST`  (relevant [`urllib2` docs](https://docs.python.org/2/library/urllib2.html#urllib2.Request)). This  seems to be supported by individual ensembl mirrors (e.g. sending a `POST` to `useast.ensembl.org` works). The real issue is that when we get redirected via a `302` by `www.ensembl.org` to `useast.ensembl.org` a `GET` request is sent to the new url which does not include the query (and the `POST` data is dropped). That's why we get an empty response back.

To verify that this is the case:

```
$ cat query.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Query>
<Query  virtualSchemaName = "default" formatter = "TSV" header = "0" uniqueRows = "0" count = "" datasetConfigVersion = "0.6" >
  <Dataset name = "hsapiens_gene_ensembl" interface = "default" >
    <Attribute name = "ensembl_gene_id" />
    <Attribute name = "chromosome_name" />
  </Dataset>
</Query>
$ curl -L --data-urlencode query@query.xml http://www.ensembl.org/biomart/martservice
... # bad output because POST data is dropped and we get a generic welcome HTML response
$ curl -L --data-urlencode query@query.xml http://useast.ensembl.org/biomart/martservice
... # correct output with gene data!
```

#### Whose problem is this?

* Redirecting to a `GET` url when the original request is a `POST` is [common practice](https://en.wikipedia.org/wiki/Post/Redirect/Get), but for this to be functional the redirect URL sent back by the server must contain the relevant parts of the original `POST` data stuck in the URL so that the client eventually gets the correct response. Ensembl servers are not doing this.
* Handling redirections (whether to resubmit the old `POST` data) is up to the client (in this case `urllib2`) and this issue has been adjudicated on a [`urllib2` bug](https://bugs.python.org/issue1401): `urllib2` will not resubmit a `POST` to the new URL. This seems to be [generally agreed upon behavior](https://greenbytes.de/tech/webdav/draft-ietf-httpbis-p2-semantics-22.html#rfc.section.6.4.p.3) since according to [HTTP specs](https://tools.ietf.org/html/rfc1945#section-9.3) resubmitting `POST` data should require user confirmation.

#### Our Options

One option is to use `GET` requests instead. I have investigated this; it has a major caveat documented below. The most reasonable solution to me seems like avoiding redirections altogether, i.e. hardcode a specific mirror (e.g. `useast.ensembl.org`) and allow the user to change as they see fit since the Ensembl dispatcher is not working properly, I've submitted a pull request that does this.


#### Using `GET` with query in URL is unreliable with Ensembl servers

One options for `fusioncatcher` is to use `GET` requests that include the XML query in the query string:

```python
full_url = server + '?' + urllib.urlencode({"query" : query})
req = urllib2.Request(full_url, None, headers) # this now sends a GET
page = urllib2.urlopen(req, timeout = 30)
```
I have confirmed that this works (but there is a major caveat, see below):
```
$ bin/get_exons_positions.py --server www.ensembl.org --organism homo_sapiens --threshold_length 150 --output data/v93/
Starting...
Get lists of chromosomes...
Downloaded:      1.25 MB
FINISHED downloading:      1.25 MB # verified correct output in temp_exons1.txt
... # the rest of output
```

I'll stick to `get_exons_positions.py` here but these failures are silent and I suspect they are happening elsewhere too. For this part of the issue I'll assume we're correctly sending `GET` requests (e.g. the two places in `get_exons_positions.py` are modified as above) and get appropriate responses and are redirected to a mirror with the correct URL. We are sending a query to get all gene ids with their chromosome numbers which works (1.25 MB response downloaded properly) and a second query for each chromosome which gets their exon coordinates. The second query is long enough for the long URL issue to surface:

```
$ bin/get_exons_positions.py --server www.ensembl.org --organism homo_sapiens --threshold_length 150 --output data/v93/
Starting...
Get lists of chromosomes...
Downloaded:      1.25 MB
FINISHED downloading:      1.25 MB #

chromosome = 1

HTTPError = HTTP Error 404: Not Found
```
What's happening here is this (confirmed by debugging URLs via `curl -vL` and browser, both give the same error):

* We send a `GET` to a URL (including encoded XML query) that is 1320 characters to `www.ensembl.org`. If we send the exact same query to `useast.ensembl.org` we get the output we want.
* But when `www.ensembl.org` redirects us via a `302` to a mirror (e.g. `useast.ensembl.org`) it adds a new `redirectsrc=...` parameters to the end of the URL which makes it 3507 characters. This fails.
* But if I take the redirect URL that `www.ensembl.org` responds with and exclude the `redirectsrc=...` parameter we get the output we want.
* Even if I leave the `redirectsrc` but truncate its value such that the full URL is <3000 characters I still get the correct output.

From all this I conclude that Ensembl mirror servers choke on super long URLs (which is not unusual anyway for URLs that are _this_ long) and we should just avoid `GET`.

**Comment by ndaniel** [comment]
I agree with the conclusion that Ensembl (mirrors and official) servers choke up with long URLs.

Thanks for the really nice description from above.

**Comment by ndaniel** [comment]
This looks to me like the equivalent of running from command line

fusioncatcher-build.py --web useast.ensembl.org
and fusioncatcher-build.py will call all the other Python scripts

fusioncatcher/bin/get_trna.py
fusioncatcher/bin/get_genes_descriptions.py
fusioncatcher/bin/get_hla2.py
fusioncatcher/bin/get_refseq_ensembl.py
fusioncatcher/bin/get_paralogs.py
fusioncatcher/bin/get_biotypes.py
fusioncatcher/bin/get_mtrna.py
fusioncatcher/bin/get_exons_positions.py
fusioncatcher/bin/get_rrna.py
...
that access Ensembl servers with the specified Ensembl mirror.

Therefore it looks like there is no need for hardcoding the mirror server. Right?

This is documented also in the manual here:
https://github.com/ndaniel/fusioncatcher/blob/master/doc/manual.md#522---building-yourself-the-organisms-build-data
