### ISSUE TITLE
Problem with the download of Genomic Databases

### ISSUE THREAD

**Issue by WYSNI** [ndaniel/fusioncatcher#106]
Hi, 

First, thanks for your tool.

I have a problem with the download of Genomic Databases.

When I use this command: 
wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python bootstrap.py -t --download

I obtain this message:

![image](https://user-images.githubusercontent.com/27208245/47087699-f53af880-d21c-11e8-9702-e2f38038150c.png)

The installation of all depencies is ok and all looks good but not the download or Genomic Databases.
And of course the internet connection is working!

Any idea?

Thanks

WYSNI

**Comment by ndaniel** [comment]
Hi,

that looks like the ftp.ensembl.org/pub is not accessible.
Could you try to run that (installs FusionCatcher) command again? Does it help?

Cheers,
Daniel

**Comment by WYSNI** [comment]
@ndaniel  the same error occur each time I use this command.
I think the problem is in line 336 (see picture).
Nothing happened in this line when I make: print(result)
So I have changed the source code a little bit.

![image](https://user-images.githubusercontent.com/27208245/47148812-0abe2a00-d2d2-11e8-815b-9a52f0dbe82c.png)

It's work but is not the best way to do.

WYSNI

**Comment by ndaniel** [comment]
For some reason I am not able to reproduce the bug reported here. I get this when running the same command:
```
Saving to: ‘bootstrap.py’

bootstrap.py                                       100%[================================================================================================================>]  94.23K  --.-KB/s    in 0.05s   

2018-10-19 10:42:22 (2.00 MB/s) - ‘bootstrap.py’ saved [96495/96495]

Checking latest version of Ensembl database that is available...
   * Version v94 found!
```

If that manual change which you made works that is great!

Anyway, that is just a warning and `bootstrap.py` is able to continue further without adverse consequences. That warning just says that `bootstrap.py` tries to find what is the latest available release of Ensembl database.
