### ISSUE TITLE
bbmap/jni java memory allocation issue

### ISSUE THREAD

**Issue by jfriend08** [ndaniel/fusioncatcher#107]
Hi!

I ran into the issue of java memory allocation:
```
java -Djava.library.path=/aslab_scratch001/asboner_dat/PeterTest/software/fusionCatcher_v0.99.7b/fusioncatcher_v0.99.7b/fusioncatcher/tools/bbmap/jni/ -ea -Xmx42219m -Xms42219m -cp /aslab_scratch001/asboner_dat/PeterTest/software/fusionCatcher_v0.99.7b/fusioncatcher_v0.99.7b/fusioncatcher/tools/bbmap/current/ jgi.BBMerge in=/aslab_scratch001/asboner_dat/PeterTest/fusionCatcher/G86_pf/candidate_focus_reads.txt.0.fq out=/aslab_scratch001/asboner_dat/PeterTest/fusionCatcher/G86_pf/candidate_focus_reads.txt.0_m.fq threads=1 extend2=20 iterations=3 k=17 mindepthseed=1 mindepthextend=1 minoverlap=11
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007f36aa000000, 29514268672, 0) failed; error='Cannot allocate memory' (errno=12)
```

Looks like the command line argument you provided that's related to memory is `--sort-buffer-size`.
However, even I have specify the value, I still got the same issue above.
```
#!/usr/bin/env bash
cd '/aslab_scratch001/asboner_dat/PeterTest/fusionCatcher'

/aslab_scratch001/asboner_dat/PeterTest/software/fusionCatcher_v0.99.7b/fusioncatcher_v0.99.7b/fusioncatcher/bin/fusioncatcher.py \
--sort-buffer-size \
20% \
-d \
/aslab_scratch001/asboner_dat/PeterTest/software/fusionCatcher_v0.99.7b/fusioncatcher_v0.99.7b/fusioncatcher/data/human_v90 \
-i \
/aslab_scratch001/asboner_dat/PeterTest/DataSet/all/torontoSample/batch53/G86_pf/ \
-o \
./G86_pf/
```

Can you show me where is the code to generate java execution command? so I can change the memory allocation.

Thanks

**Comment by ndaniel** [comment]
All the external tools are called from `fusioncatcher.py`. 

In this case `fusioncatcher.py` (at line number [2232](https://github.com/ndaniel/fusioncatcher/blob/a7483fbde3f95febcae22e831d7f51d03da706a6/bin/fusioncatcher.py#L2232)) calls `bbmap.sh` (which is in your case here `/aslab_scratch001/asboner_dat/PeterTest/software/fusionCatcher_v0.99.7b/fusioncatcher_v0.99.7b/fusioncatcher/tools/bbmap/bbmap.sh`) and this calls further the `java`. Probably in your case it might help editing directly the `bbmap.sh`.

On the other hand `--sort-buffer-size` is only and only for the Linux command `sort` does not affect Java/BBMAP at all.

**Comment by jfriend08** [comment]
Thanks! seems bbmap.sh use calcmem.sh to calculate the RAM, but seems is problematic.
