### ISSUE TITLE
Could we pass limitSjdbInsertNsj as parameter of fusioncatcher.py

### ISSUE THREAD

**Issue by fredjarlier** [ndaniel/fusioncatcher#111]
Hi Daniel,

I encounter a problem with fusioncatcher on RNASEQ data and from time to time I recieve this message 
Fatal LIMIT error: the number of junctions to be inserted on the fly =2501023 is larger than the limitSjdbInsertNsj=2000000

I would like to change this limit without breaking the code in fusioncatcher.py. 

Do you think it is possible to pass it in a configuration file (aka fusioncatcher.conf) please?

Best

frederic

**Comment by ndaniel** [comment]
FusionCatcher is running several times STAR. I would need the log of the run where FusionCatcher failed (or at least the command line used by FusionCatcher to run STAR => FusionCatcher shows this). I need this in order to change the limit because it is not possible to change it for all steps where STAR is run.
What was the the version of FusionCatcher used?

**Comment by fredjarlier** [comment]
Hi Daniel thanks for your reply

Here is the log from fusioncatcher 

[D067T05.fusioncatcher.log](https://github.com/ndaniel/fusioncatcher/files/2918714/D067T05.fusioncatcher.log)

and the version from the fusioncatcher.conf
[versions]
fusioncatcher = 1.00

best

f

**Comment by ndaniel** [comment]
Ok. Thanks for the log.

One possible way around this would be to use FusionCatcher with the command line option `--limit-star 300000000` for the case where this error shows up. This would require to re-run from the scratch FusionCatcher though.

**Comment by fredjarlier** [comment]
thanks, I test it and tell you.
f

**Comment by fredjarlier** [comment]
Hi Daniel 

I pass  --limit-star to the fusioncatcher (in ...opt/fusioncatcher/bin/fusioncatcher) with no luck, it looks like the option isn't pass along...may I use the configuration file to send the option instead?

best, fred

**Comment by ndaniel** [comment]
command line option `--limitSjdbInsertNsj` will be added in release 1.10 which will be released in few days!

**Comment by ndaniel** [comment]
Added `--limitSjdbInsertNsj` in release 1.10.

**Comment by fredjarlier** [comment]
Hi Daniel and thank you. I will test it and comme back to you.
Best
Frederic

Envoyé depuis Yahoo Mail pour Android 
 
  Le jeu., avr. 4, 2019 à 14:57, Daniel Nicorici<notifications@github.com> a écrit :   
command line option --limitSjdbInsertNsj will be added in release 1.10 which will be released in few days!
