### ISSUE TITLE
Reproducibility question

### ISSUE THREAD

**Issue by fredjarlier** [ndaniel/fusioncatcher#112]
Hi Daniel,

I did run the fusioncatcher pipeline twice upon the same data and with the same configuration. And I have notice differences in the final results final-list_candidate-fusion-genes.hg19.txt. Have you ever encountered this? Is it normal and waited?

Best

frederic

**Comment by ndaniel** [comment]
The results should be the same. 
It is challenging to say what is happening without more info. Has the FusionCatcher been stopped and restarted?

**Comment by fredjarlier** [comment]
No fusion didn't stop. I attach the log of the 2 runs.

[fusioncatcher_run1.log](https://github.com/ndaniel/fusioncatcher/files/2918941/fusioncatcher_run1.log)
[fusioncatcher_run2.log](https://github.com/ndaniel/fusioncatcher/files/2918943/fusioncatcher_run2.log)

and the fusion catcher config 

[fusioncatcher_config.txt](https://github.com/ndaniel/fusioncatcher/files/2918953/fusioncatcher_config.txt)

Tell me if you need more info

thanks a lot

frederic

**Comment by ndaniel** [comment]
I looked to it and it looks like Bowtie (at step 93) when is run on exactly the same input gives different results every time when is run:
```
bowtie \
-t  \
--seedmms 1 \
--seedlen 60 \
-X 10000 \
-p 16 \
-k 1 \
--phred33-quals  \
--chunkmbs 128 \
--un /data/G2/fusioncatcher/ox.fq \
--max /dev/null \
 /data/annotations/pipelines/transcripts_index/ \
-1 /data/G2/fusioncatcher/ox1.fq \
-2 /data/G2/fusioncatcher/ox2.fq \
 /dev/null 
```
In this case FusionCatcher v1.0 is used which allows two versions of Bowtie that are 1.1.2 and 1.2.0.
Would be possible to look to the `info.txt`files for each run (they should be also where the `fusioncatcher.log` file is) because there is specified exactly the version of Bowtie using for the run.

**Comment by fredjarlier** [comment]
yes sure

[info.txt.tar.gz](https://github.com/ndaniel/fusioncatcher/files/2920286/info.txt.tar.gz)

To your opinion I shall pass to FusionCatcher 1.10 right?  but I don't find it in conda is it normal?

bests

fred

**Comment by ndaniel** [comment]
Hi!

Bowtie 1.1.2 is used. It is supposed that Bowtie 1.2.x has bugs and not 1.1.2.
FusionCatcher 1.10 is not yet released officially!

All I can think is if it would be possible to run FusionCatcher the third time on the same input FASTQ files and see how the results compare with the first two runs!

Daniel

**Comment by fredjarlier** [comment]
Hi Daniel and thanks, I wasn't aware of flaws in Bowtie 1.2. Ok  I do that and tell you.
best, fred

**Comment by fredjarlier** [comment]
Hi Daniel here is the third run

[fusioncatcher_run3.log](https://github.com/ndaniel/fusioncatcher/files/2929909/fusioncatcher_run3.log)

**Comment by ndaniel** [comment]
Are the same fusions found similar to first run or second run?

**Comment by fredjarlier** [comment]
yes the three runs have different results.

**Comment by ndaniel** [comment]
On first run one has:
```
ox_1.fq (size: 6454063286 bytes)
ox_2.fq (size: 6461802802 bytes)
```
and second run one has:
```
ox_1.fq (size: 6454063288 bytes)
ox_2.fq (size: 6461802804 bytes)
```
and on third run:
```
ox_1.fq (size: 6454063288 bytes)
ox_2.fq (size: 6461802804 bytes)
```

**Comment by fredjarlier** [comment]
yes you are right. Why is the 3rd and 2nd the same to your opinion?

But when I look at the tsv files they all have different lines number I don't get it...

**Comment by ndaniel** [comment]
Ok. Could you contact me privately?

**Comment by fredjarlier** [comment]
I have a meeting this afternoon. Tomorrow is fine by me and you?

Envoyé depuis Yahoo Mail pour Android 
 
  Le mar., mars 5, 2019 à 12:44, Daniel Nicorici<notifications@github.com> a écrit :   
Ok. Could you contact me privately?

**Comment by ndaniel** [comment]
Yes, basically I would need more info about the differences in fusion genes between the three runs.

**Comment by fredjarlier** [comment]
no problem here is my professional address frederic.jarlier@curie.fr

best

fred

**Comment by ndaniel** [comment]
It looks like there is some randomness in Bowtie's mappings. Also in this case for each run FusionCatcher has found around a very large number of fusion genes (i.e. over 1500).

According to [Bowtie's manual](http://bowtie-bio.sourceforge.net/manual.shtml#bowtie-options-seed) one has

> The process by which bowtie chooses an alignment to report is randomized in order to avoid "mapping bias" - the phenomenon whereby an aligner systematically fails to report a particular class of good alignments, causing spurious "holes" in the comparative assembly. Whenever bowtie reports a subset of the valid alignments that exist, it makes an effort to sample them randomly. This randomness flows from a simple seeded pseudo-random number generator and is deterministic in the sense that Bowtie will always produce the same results for the same read when run with the same initial "seed" value (see --seed option).

This randomness from bowtie does not show up when the number of fusion genes is low (that is in range 0-200) but obviously it shows up when one has around (or more) than 1000 fusion genes. It looks like the fix in this case for FusionCatcher is that the command line parameter `--seed` should be added each time bowtie is executed.
