### ISSUE TITLE
what does m3,m7 in column Fusion_description mean?

### ISSUE THREAD

**Issue by wqhf** [ndaniel/fusioncatcher#113]
Hi Daniel,
When I got final-list_candidate-fusion-genes.hg19.txt, I meet some flag in column Fusion_description like m0,m1,m11,m12,m15,m16,m3,m35,m37,m4,m5,m6,m60,m7. I didn't see any description with such flags in your instruction. I checked data inside directory human_v90, but I got no answer too. So could you please show details about all of these flags?
Best
WeiQiang Yu

**Comment by ndaniel** [comment]
These are explained in the manual of FusionCatcher. See Table 2  here https://github.com/ndaniel/fusioncatcher/blob/master/doc/manual.md#62---output-data-output-data :


mX (where X is a number) =| count of pairs of reads supporting the fusion (excluding the mutimapping reads).
m0 = There are no pairs of non-multi-mapping reads supporting the fusion. Basically, there are supporting pairs of reads but all of them map also in some other places on genome (that is their mappings on genome are not unique).
