### ISSUE TITLE
Disable usage of COSMIC

### ISSUE THREAD

**Issue by dinggens** [ndaniel/fusioncatcher#119]
Hello,
is there an option to disable the usage of COSMIC?
Many thanks in advance!

**Comment by ndaniel** [comment]
The only way is to empty the file `cosmic.txt` which should be somewhere and approximately here `fusioncatcher/data/human_v96/cosmic.txt`.

From command line this would be something like:
```
cd  fusioncatcher/data/human_v96
rm cosmic.txt
touch cosmic.txt
```

I am just curious. Why would you like to disable COSMIC?
