### ISSUE TITLE
Multiple same fusion in Output Result [RESOLVED]

### ISSUE THREAD

**Issue by Evansef** [ndaniel/fusioncatcher#120]
Hello,
I would like know to if my results have a problem or not, in fact, like you can see on the result bellow i have the same fusions which appear several times in my output file final "final-list_candidate-fusion-genes.txt". The sequence is not exactly the same, the longest anchor found is different but the finding method and Counts_of_common_mapping_reads appears several times for each fusion. More over I use fusioncatcher on single-end reads data, why does I have spanning pairs ? Is it normal ?

Thank you in advance for your answer.

Gene_1_symbol(5end_fusion_partner) | Gene_2_symbol(3end_fusion_partner) | Fusion_description | Counts_of_common_mapping_reads | Spanning_pairs | Spanning_unique_reads | Longest_anchor_found | Fusion_finding_method | Fusion_point_for_gene_1(5end_fusion_partner) | Fusion_point_for_gene_2(3end_fusion_partner) | Gene_1_id(5end_fusion_partner) | Gene_2_id(3end_fusion_partner) | Exon_1_id(5end_fusion_partner) | Exon_2_id(3end_fusion_partner) | Fusion_sequence | Predicted_effect
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CRLF2 | CSF2RA | banned,known,paralogs,similar_reads,oncogene,healthy,ambiguous,chimerdb3pub,cancer,m3,mitelman,reciprocal | 2916 | 24 | 2 | 37 | BOWTIE+STAR | X:1245134:- | X:1309251:+ | ENSG00000205755 | ENSG00000198223 |   |   | GCTACTCGGGAGGCTGAGGCAGGAGAATCGCTCGAACCCGGGAGGCGGAG*GTTGCAGTGAGCTGAGATGACACCACTGCACTCCAGCCTGGGCAATAGAA | intergenic/intronic
CRLF2 | CSF2RA | banned,known,paralogs,similar_reads,oncogene,healthy,ambiguous,chimerdb3pub,cancer,m3,mitelman,reciprocal | 2916 | 24 | 2 | 36 | BOWTIE+STAR | X:1158673:- | X:1305218:+ | ENSG00000205755 | ENSG00000198223 |   |   | GTAGGGATGGGGTTTCACCACGTTGGCCAGGCTGGTCTCGAACTCCCGAC*CTCAAGTGATCCACCCGCCTCGGCCTCCCAAAGTGCTGGGATTACAGGTG | intergenic/intronic
CRLF2 | CSF2RA | banned,known,paralogs,similar_reads,oncogene,healthy,ambiguous,chimerdb3pub,cancer,m3,mitelman,reciprocal | 2916 | 24 | 2 | 35 | BOWTIE+BLAT | X:1121911:- | X:1255619:+ | ENSG00000205755 | ENSG00000198223 |   |   | TCAAGCGATTCTTCTGCCTCAGCCTCCCGAGTAGCTGGGACTACAGGTGC*CACCACCATGCCCAGCTAATTTTTTGTATTTTTAGTACAGATAGGGTTTC | intergenic/intergenic
CRLF2 | CSF2RA | banned,known,paralogs,similar_reads,oncogene,healthy,ambiguous,chimerdb3pub,cancer,m3,mitelman,reciprocal | 2916 | 24 | 2 | 34 | BOWTIE+STAR | X:1238529:- | X:1256008:+ | ENSG00000205755 | ENSG00000198223 |   |   | TCTTGTCATCCAGGCTGGAGTGCAGTGGTGTGATCTCGGCTCACTGCAAC*CTCTGCCTCCCGGGTTCAAACGATTCTCCTGCCTCAGCCTCCCGAATAGC | intergenic/intergenic
CRLF2 | CSF2RA | banned,known,paralogs,similar_reads,oncogene,healthy,ambiguous,chimerdb3pub,cancer,m3,mitelman,reciprocal | 2916 | 24 | 2 | 34 | BOWTIE+STAR | X:1156969:- | X:1256008:+ | ENSG00000205755 | ENSG00000198223 |   |   | CTCTGTCACCCAGGCTGGAGTGCAGTGGTGTGATCTCGGCTCACTGCAAC*CTCTGCCTCCCGGGTTCAAACGATTCTCCTGCCTCAGCCTCCCGAATAGC | intergenic/intergenic
CRLF2 | CSF2RA | banned,known,paralogs,similar_reads,oncogene,healthy,ambiguous,chimerdb3pub,cancer,m3,mitelman,reciprocal | 2916 | 24 | 2 | 27 | BOWTIE+BLAT | X:1191663:- | X:1280358:+ | ENSG00000205755 | ENSG00000198223 |   |   | CTAAAAATACAAAATTAGCCGTGTGTGGTGGTGCACGTCTGTAATCCCAG*CTACTTGGGAGGCCGAGGCAGGAGAATCGCTTGAACCCGGGAGGCGGAGG | intronic/intronic
CRLF2 | CSF2RA | banned,known,paralogs,similar_reads,oncogene,healthy,ambiguous,chimerdb3pub,cancer,m3,mitelman,reciprocal | 2916 | 24 | 2 | 27 | BOWTIE+BLAT;BOWTIE+STAR | X:1217472:- | X:1261119:+ | ENSG00000205755 | ENSG00000198223 |   |   | GCTCTGTCACCAGGCTGGAATGCAGTGGTGTGATCTTGGCTCACTGCAAC*CTCCGCCTCCCAGGTTCAGGTGATTCTCCTGCCTCAGCCTCCCGAGTAGC | intergenic/intergenic
CRLF2 | CSF2RA | banned,known,paralogs,similar_reads,oncogene,healthy,ambiguous,chimerdb3pub,cancer,m3,mitelman,reciprocal | 2916 | 24 | 2 | 25 | BOWTIE+BLAT | X:1119995:- | X:1263503:+ | ENSG00000205755 | ENSG00000198223 |   |   | ACCTGTAGTCCCAGCTACTCGGGAGGCTGAGGCAGGAGAATCGCTTGAAC*CCGGGAGGCGGAGATTGCAGTGAGCCGAGATTGCACCATTGCACTCCAGC | intergenic/intergenic
CRLF2 | CSF2RA | banned,known,paralogs,similar_reads,oncogene,healthy,ambiguous,chimerdb3pub,cancer,m3,mitelman,reciprocal | 2916 | 24 | 2 | 18 | BOWTIE+BLAT | X:1194822:- | X:1305215:+ | ENSG00000205755 | ENSG00000198223 |   |   | TTAGTAGAGACGGGGTTTCACCGTGTTGGCCAGGCTGGTCTCGAACTCCT*AACCTCAAGTGATCCACCCGCCTCGGCCTCCCAAAGTGCTGGGATTACAG | intronic/intronic
CSF2RA | CRLF2 | banned,known,paralogs,similar_reads,oncogene,healthy,ambiguous,chimerdb3pub,cancer,m3,mitelman,reciprocal | 2916 | 24 | 4 | 37 | BOWTIE+STAR | X:1287602:+ | X:1153083:- | ENSG00000198223 | ENSG00000205755 |   |   | CCTGCCTCAGCCTCCTGAGTAGCTGGGATTACAGGTGCCCACCACCACAC*CCAGCTAATTTTTGTATTTTTAGTAGAGACGGGGTTTCCCTGTGTTAGCC | intronic/intergenic
CSF2RA | CRLF2 | banned,known,paralogs,similar_reads,oncogene,healthy,ambiguous,chimerdb3pub,cancer,m3,mitelman,reciprocal | 2916 | 24 | 2 | 34 | BOWTIE+STAR | X:1299686:+ | X:1166874:- | ENSG00000198223 | ENSG00000205755 |   |   | GCCAGGCACGGTGGCTCACGCCTGTCATCCCAGCACCTTGGGAGGCTGAG*GCAGGCGGATCATCTGAGGTCAGGAGTTCGAGACCATCCTGGCCAACATG | intronic/intergenic
CSF2RA | CRLF2 | banned,known,paralogs,similar_reads,oncogene,healthy,ambiguous,chimerdb3pub,cancer,m3,mitelman,reciprocal | 2916 | 24 | 2 | 26 | BOWTIE+BLAT | X:1315485:+ | X:1244153:- | ENSG00000198223 | ENSG00000205755 |   |   | TTCTGTCACCCAGGCTGGAGTGCAGTGGCGCGATCTCAGCTCACTACAAC*CTCCGCCTCCCGGGTTCACGCCATTCTCCTGCATCAGCCTCCTGGGTAGC | intergenic/intergenic
CSF2RA | CRLF2 | banned,known,paralogs,similar_reads,oncogene,healthy,ambiguous,chimerdb3pub,cancer,m3,mitelman,reciprocal | 2916 | 24 | 2 | 20 | BOWTIE+BLAT | X:1304801:+ | X:1216452:- | ENSG00000198223 | ENSG00000205755 |   |   | CCTCCCGGGTTCACGCCATTCTCCTGCCTCAGCCTCCCGAGTAGCTGGGA*CAGGCACCTGCCACCACGCCTGGCTAATTTTTGTATTTTTAGTAGAGACG | intronic/intergenic
CSF2RA | CRLF2 | banned,known,paralogs,similar_reads,oncogene,healthy,ambiguous,chimerdb3pub,cancer,m3,mitelman,reciprocal | 2916 | 24 | 2 | 19 | BOWTIE+STAR | X:1300062:+ | X:1207821:- | ENSG00000198223 | ENSG00000205755 |   |   | CGAGACCATCCTGGCCAACATGGTGAAACCCCGTCTCCACTAAAAATACA*AAAAACTAGCCGGGCGTGGCGGCAGGTGCCTGTAATCCCAGCTACTCAGG | intronic/intronic
CRLF2 | TRA@ | oncogene,cancer,m3,reciprocal | 0 | 22 | 3 | 36 | BOWTIE+STAR | X:1188068:- | 14:21568386:+ | ENSG00000205755 | ENSG09000001070 |   |   | GGCGTAAGCCACCACGCCTGGCTAATTTTTGTATTTTTAGTAGAAACGGG*GTTTTGCCATGTTGGCCAGGCTGGTCTCAAACTCCTGACCTCAGGTGATC | intronic/---
CRLF2 | TRA@ | oncogene,cancer,m3,reciprocal,short_repeats | 0 | 22 | 2 | 35 | BOWTIE+BLAT | X:1184514:- | 14:21562895:+ | ENSG00000205755 | ENSG09000001070 |   |   | GAGGTTGCAGTGAGCCGAGATCGTGCCACTGCACTCCAGCCTGGGTGACA*GAGCGAAACTCCGTCTCAAAACAAAACAAAACAAACAAACGAACAAAAAC | intergenic/---
CRLF2 | TRA@ | oncogene,cancer,m3,reciprocal | 0 | 22 | 2 | 33 | BOWTIE+BLAT | X:1202882:- | 14:21632822:+ | ENSG00000205755 | ENSG09000001070 |   |   | TTAGCATATTGGCCAGGCTGGTCTCGAACTCCTGACTTCAGGTGATCCAC*CCACCTCGGCCTCTCAAAGTGCTGGGATTACAGGCGTGAGCCACTGCGCC | intronic/---
CRLF2 | TRA@ | oncogene,cancer,m3,reciprocal | 0 | 22 | 2 | 25 | BOWTIE+STAR | X:1197686:- | 14:21584127:+ | ENSG00000205755 | ENSG09000001070 |   |   | TTCAAGTGATTCTCCTGCCTCAGCCTCCCAAGTAGCTGGGACTACAGGCA*CGCACCATCACACCTGGCTAATTTTGTATTTTTAGTAGAGATGGAGTTTC | intronic/---
CRLF2 | TRA@ | oncogene,cancer,m3,reciprocal | 0 | 22 | 2 | 22 | BOWTIE+BLAT | X:1130648:- | 14:21594668:+ | ENSG00000205755 | ENSG09000001070 |   |   | GGGCAGGAGAATCGCTTGAACCCGGGAGGCGGAGGTTGCAGTGAGCCGAG*ATCACGCCATTGCACTCCAGCCTAGGTGACAAGAGCGAAACTCTGTCTCA | intergenic/---
TRA@ | CRLF2 | oncogene,cancer,m3,reciprocal | 0 | 22 | 2 | 27 | BOWTIE+STAR | 14:21620809:+ | X:1150508:- | ENSG09000001070 | ENSG00000205755 |   |   | ATGTTCAAGTGATTCTCCTGCCTCAGCCTCCTGAGTAGCTGGGATTGCAG*GTGTGCACCACCACGCCCGGCTGATTTTTGTATTTTTAGTAGAGATGGGG | ---/intergenic
TRA@ | CRLF2 | oncogene,cancer,m3,reciprocal | 0 | 22 | 2 | 26 | BOWTIE+STAR | 14:21611640:+ | X:1208345:- | ENSG09000001070 | ENSG00000205755 |   |   | GTAGAGACAGGGTTTTGCCATGTTGGCCAGGCTGGTCTCGAACTCCTGAT*CTCATGTGATCCACCTGCCTCAGCCTCCCAAAGTGCTGGGATGACAGGCG | ---/intronic
TRA@ | CRLF2 | oncogene,cancer,m3,reciprocal | 0 | 22 | 2 | 19 | BOWTIE+BLAT | 14:21777696:+ | X:1246028:- | ENSG09000001070 | ENSG00000205755 |   |   | GAGATGGGGTTTCACCGTGTTAGCCAGGATGGTCTCGATTTCCTGACCTC*GTGATCCGCCTGCCTCGGGCTCCCAAAGTGCTGGGATTACAAGCGTGAGC | ---/intergenic
TRA@ | WWOX | cancer,tumor,m4,reciprocal | 0 | 20 | 2 | 31 | BOWTIE+BLAT | 14:21826566:+ | 16:78243617:+ | ENSG09000001070 | ENSG00000186153 |   |   | GATGGAGTCTCACTCAGTCGCCCAGGCTGGAGTGCAGTGGCGTGATTTCG*GCTCACTGCAACCTCCACCTCCTGGGTTCAAGCGATTCTTGTGCCTCAGC | ---/intronic
TRA@ | WWOX | cancer,tumor,m4,reciprocal | 0 | 20 | 2 | 30 | BOWTIE+STAR | 14:21782271:+ | 16:78726340:+ | ENSG09000001070 | ENSG00000186153 |   |   | ATCTCAGCTTACTGCAACCTTCGCCTCCCGGGTTCAAGCAATTCTCCTGC*CTCAGCCTCCCGGGTAGCTGGGACCACAGGTATGCACCACCACACGTGGC | ---/intronic
TRA@ | WWOX | cancer,tumor,m4,reciprocal | 0 | 20 | 2 | 25 | BOWTIE+STAR | 14:21593970:+ | 16:79080707:+ | ENSG09000001070 | ENSG00000186153 |   |   | CCTGTCTCTACTAAAAATACAAAAAATTAGCAGGGCATGGTGGCGGGCGC*CTGTAATCCCAGCCACTTGGGAGGCTGAAGTGGGAGGATCGCTTGAAGCC | ---/intronic
TRA@ | WWOX | cancer,tumor,m4,reciprocal | 0 | 20 | 2 | 24 | BOWTIE+STAR | 14:21782277:+ | 16:78495629:+ | ENSG09000001070 | ENSG00000186153 |   |   | GCTTACTGCAACCTTCGCCTCCCGGGTTCAAGCAATTCTCCTGCCTCAGC*CTCCCGAGTAGCTGGGACTACAGGCCAACGCCACGGCACCTGGCTAATTT | ---/intronic
TRA@ | WWOX | cancer,tumor,m4,reciprocal | 0 | 20 | 2 | 19 | BOWTIE+STAR | 14:21552337:+ | 16:78427728:+ | ENSG09000001070 | ENSG00000186153 |   |   | TGAGGCAGGAGAATCGCTTGAACCCGGGAAGTGGAGGTTGCAGTGAGCCA*TGATCATGCCACTGCATTCCAGCCTGGGTGACAGAGTGAGACCCCATCTC | ---/intronic
WWOX | TRA@ | cancer,tumor,m4,reciprocal | 0 | 20 | 3 | 34 | BOWTIE+STAR | 16:78186595:+ | 14:21646631:+ | ENSG00000186153 | ENSG09000001070 |   |   | TTGTGGTCAGGAGTTTGAGACCAGCCTGGCCAATATGGCGAAACCCTGTC*TCTACTAAAAATACAAAAATTAGCTGGGCGTGGTGGTGGGCGCCTGTAAT | intronic/---
WWOX | TRA@ | cancer,tumor,m4,reciprocal | 0 | 20 | 2 | 37 | BOWTIE+STAR | 16:79026712:+ | 14:21614638:+ | ENSG00000186153 | ENSG09000001070 |   |   | GCTGCAGTGCAGTGGCGCGATCTCAGCTCACTGCAACCTCCGCCTCCCGG*GTTCAAGGGATTCTCCTGCCTCAGCCTCCCGAGTAGCTGGGGTTACAGGC | intronic/---

**Comment by ndaniel** [comment]
Hi,

the CRLF2-CSF2RA fusion looks like is real (because are tons of reads supporting it) and also it has been reported in scientific literature before, like for example: 
- http://atlasgeneticsoncology.org/Anomalies/TL_delXp22p22ID2120.html 
- https://www.ncbi.nlm.nih.gov/pubmed/24935070
- https://onlinelibrary.wiley.com/doi/pdf/10.1002/pbc.26539 .


From the literature it is known that there are a lot mutations and variations going on between CRLF2 and CSF2RA genes. It might be that all those fusion junctions are correct and that might be explained by there being multiple copies (e.g. amplification in copy number) of CRLF2 and CSF2RA and each copy gets fused differently.

My guess is that the candidate fusions CRLF2-TRA@ and TRA@-WWOX are probably false positives.

Regarding single-end reads, FusionCatcher handles them by *generating* paired-end reads out of single-end reads and then working with the generated paired-end reads. So yes, it is normal to have spanning_pairs even for single-end reads in FusionCatcher's results.

Cheers,
Daniel

**Comment by Evansef** [comment]
Thank you very much for your answer ! I have another question, completely different, I would like to know your point of view about it. I have 50 samples, two conditions and my research purpose to find fusion transcripts and see if there is a correlation between the transcripts I find in a condition are specific to this one. 
With your tool, it appears there is a correlation because I find few transcripts often in a condition and not in the other. BUT, the fact is, in my 20 fastq data from one condition, these transcripts are find in this proportion : 10/20 (50% not bad because this is tumor samples). I went further using the GREP command : 
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0099439

It appears the sequence of these fusion transcripts are found in my 10 other samples from the same condition. So, can I consider these fusion transcripts has been filtered by the tool ? For me it should be possible because my data are not equal a sample to another, I have not the same amount of reads between all my sequence, it's very variable, I have to work with these I didn't got the choice to resequence.

**Comment by ndaniel** [comment]
Your plan sounds good to me. 
I expect, that grep would give better estimates (and better sensitivity) than FusionCatcher in this case.
FusionCatcher is a [unsupervised learning](https://en.wikipedia.org/wiki/Unsupervised_learning) method (that in this case means it looks for ten of thousands of possible fusion genes) whilst grep (that way is used in the article you highlighted) is used as [supervised learning](https://en.wikipedia.org/wiki/Supervised_learning). Supervised and unsupervised learning answers different questions. For example one needs to known beforehand the fusion is looking for before using grep BUT for FusionCatcher that is not needed. Indeed one would expect that grep is more sensitive in your case.

**Comment by Evansef** [comment]
Okay thank you for this precise answer I understand better ! Do you consider 26 nt of the fusion sequence is sufficient for the grep command ? In term of specificity it's approximately the size of a primer, I think it's relevant if I found something with this size no ?

**Comment by ndaniel** [comment]
I think that size is ok.
