### ISSUE TITLE
Inconsistent results between coordination and gene name

### ISSUE THREAD

**Issue by xiucz** [ndaniel/fusioncatcher#122]
HI, @ndaniel 

I found a breakpoint's coordination didn't match its gene name,  CRLF2 gene range from NC_000023.10 (1314869..1331529, complement)[https://www.ncbi.nlm.nih.gov/gene/64109] ,
however, which is not including  X:1250524 (hg19 system).

Can you give some comments? Thank you very much.
```
$ egrep "CRLF2" final-list_candidate-fusion-genes.hg19.txt 

IGH@	CRLF2	known,oncogene,fragments,cancer,m0,multi	0	3	2	39	BOWTIE+STAR	14:107189210:+	X:1250524:-	ENSG09000000018	ENSG00000205755			GACCTTATGATCCGCCCGCCTCAGCCTCCCAAAGTGCTGGGATTACAGGC*GTGAGCCACCACGCCCAGTCCCTGTTTATTTTTCTGTCATTTATTTATCT	---/intergenic

$ egrep "CRLF2" final-list_candidate-fusion-genes.txt 

IGH@	CRLF2	known,oncogene,fragments,cancer,m0,multi	0	3	2	39	BOWTIE+STAR	14:106780973:+	X:1150371:-	ENSG09000000018	ENSG00000205755			GACCTTATGATCCGCCCGCCTCAGCCTCCCAAAGTGCTGGGATTACAGGC*GTGAGCCACCACGCCCAGTCCCTGTTTATTTTTCTGTCATTTATTTATCT	---/intergenic
```

Xiucz

**Comment by ndaniel** [comment]
Your observation is correct.

First, IGH@ is not a gene either. It is region on chromosome that contains many IGH genes.

FusionCatcher slightly "extends" most of the genes left and right whenever is possible (and when it does not overlap with other neighboring genes).  I found this to be required for detecting especially fusions involving CRLF2 gene.

Looking to your example of IGH@-CRLF2 I would say that that fusion is for real there.

**Comment by xiucz** [comment]
Thank you @ndaniel,

Thank you for your reply, which has lighted me a lot , and the last paragraph is really useful to remind me of the difference between coordinates and annotations.

**Comment by xiucz** [comment]
Thank you @ndaniel,

Thank you for your reply, which has lighted me a lot , and the last paragraph is really useful to remind me of the difference between coordinates and annotations.

**Comment by xiucz** [comment]
@ndaniel,

One more thing I  want to comfirm with you: the gene annotation  in **final-list_candidate-fusion-genes.hg19.txt ** is hg19-coordinatesystem or hg38-coordinatesystem ?

Xiucz

**Comment by ndaniel** [comment]
The file `final-list_candidate-fusion-genes.hg19.txt` is obtained from file `final-list_candidate-fusion-genes.txt` by converting the genomic coordinates from hg38 to hg19 using the tool `liftOver` (from https://genome.ucsc.edu ). No other conversion is done. So the answer to your question is that  `final-list_candidate-fusion-genes.hg19.txt` has the genomic coordinates into hg19 system but the gene annotations info (where a gene starts and ends, etc.) are from hg38.
