### ISSUE TITLE
ERROR: Workflow execution failed at step 95 while executing sra2illumina.py

### ISSUE THREAD

**Issue by vaishmanobala** [ndaniel/fusioncatcher#123]
`ImportError: cannot import name _aligners: you should not import directly from the biopython source directory; please exit the source tree and re-launch your code from there.`

How to proceed further?

**Comment by ndaniel** [comment]
I need more info, like for example:
- version of FusionCatcher used,
- logs of the run (e.g. fusioncatcher.log and info.txt).

**Comment by vaishmanobala** [comment]
fusioncatcher.py 1.10

**Comment by ndaniel** [comment]
fusioncatcher.log ?

**Comment by vaishmanobala** [comment]
================================================
Software version: fusioncatcher.py 1.10
================================================


===================================
GENOME INFORMATION:
===================================
fusioncatcher-build.py 1.10
Ensembl database version: 95
Organism: Homo sapiens
Genome version: GRCh38
NCBI Viral Genomes version: 2019-01-07
UCSC database version (hg38): 2018-11-18
RefSeq NCBI database version (downloaded thru UCSC database; hg38): 2018-11-25
Gencode database version: 29
Non-cancer tissues and cells (Babiceanu et al. Nucl. Acids Res. 2016) database version: 2019-01-23
Cancer Gene List database version: 2019-01-23
Oncogenes database version: 2019-01-23
TumorFusions (Hu et al. Nucleic Acids Research) database version: Nov. 2017
TumorFusions (Hu et al. Nucleic Acids Research) database version: Nov. 2017
TCGA Fusions Dataset (Qingsong G., Cell Reports, 2018) version: April 2018
Cell lines (Klijn et al. Nature Biotechnology 2014) database version: 2019-01-23
Pancreatic Tumor Patients (Bailey et al. Nature 2016) database version: 2019-01-23
ChimerDB database version: 2.0
ChimerDB database version: 3.0
TICdb database version: 2019-01-23
ConjoinG database version: 2019-01-23
CGP database version: 2019-01-23
CACG database version: 2019-01-23
DGD database version: 2019-01-23
GTEx database version (thru FusionAnnotator): 2019-01-23
rt-circ RNAs dataset (J.N. Vo, The Landscape of Circular RNA in Cancer, Cell, Feb. 2019):
Mitelman database version: 2019-03-12


===================================
Genome FASTA files:
===================================
ftp.ensembl.org//pub/release-95/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa

**Comment by vaishmanobala** [comment]
> fusioncatcher.log ?

Yes. Error occurred during the test run

**Comment by vaishmanobala** [comment]
> I need more info, like for example:
> 
> * version of FusionCatcher used,
> * logs of the run (e.g. fusioncatcher.log and info.txt).

[fusioncatcher.log](https://github.com/ndaniel/fusioncatcher/files/3320099/fusioncatcher.log)
[info.txt](https://github.com/ndaniel/fusioncatcher/files/3320100/info.txt)

**Comment by ndaniel** [comment]
It looks like it is related to: 
- https://stackoverflow.com/questions/51296034/importerror-cannot-import-name-aligners-biopython
- https://mailman.open-bio.org/pipermail/biopython/2018-June/016485.html

It looks like BioPython is installed locally into a user account. A workaround might be to install BioPython (and NumPy) as root instead as user.

**Comment by vaishmanobala** [comment]
I upgraded `PIP` and `BioPython` & got it fixed. thank you so much for the quick response!
