### ISSUE TITLE
problem for fusioncatcher-build

### ISSUE THREAD

**Issue by LEIyuechen** [ndaniel/fusioncatcher#125]
Hi,

I am trying to use fusioncatcher-build and I need the genome and database of hg37 version. However, the default and "https://sourceforge.net/projects/fusioncatcher/files/data/" is all for hg38. Could I build my hg37 version directory and how I change the parameter?? I tried to go through the code and change the "-e" parameter but it doesn't work. Please show me how to deal it or what should I download by myself.

Hope your reply. Thank you.

Best,
Lei

**Comment by ndaniel** [comment]
Sorry that is not possible. 
FusionCatcher gives the genomic coordinates of fusion genes in hg38 and hg19 though.

**Comment by LEIyuechen** [comment]
If I want to build hg19 version genome, What parameter should I use in terms of fusioncatcher-build.py？I cannot find appropriate way to tell programme I want hg19.------------------ 原始邮件 ------------------
发件人: "Daniel Nicorici"<notifications@github.com>
发送时间: 2019年7月2日(星期二) 晚上6:58
收件人: "ndaniel/fusioncatcher"<fusioncatcher@noreply.github.com>;
抄送: "LEIyuechen"<747166943@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ndaniel/fusioncatcher] problem for fusioncatcher-build (#125)



Sorry that is not possible.
 FusionCatcher gives the genomic coordinates of fusion genes in hg38 and hg19 though.
 
&mdash;

**Comment by ndaniel** [comment]
FusionCatcher gives the genomic coordinates of fusion in hg38 and hg19 always. The file that file that has hg19 contains the coordinates using hg19. There is no need to build anything because FusionCatcher converts hg38 to hg19.

**Comment by Coaxecva** [comment]
Hi Ndaniel,

I ran fusioncatcher using human_v102 (from the download script). In the output folder, I couldn't find hg19. Wonder if I missed something in the run?

Thanks,
Coax

**#Output folder**
> final-list_candidate-fusion-genes.caption.md.txt     
> final-list_candidate-fusion-genes.vcf  
> fusioncatcher.log.002.bak  
> summary_candidate_fusions.txt             
> supporting-reads_gene-fusions_STAR.zip
> final-list_candidate-fusion-genes_sequences.txt.zip  
> fusioncatcher.log                      
> info.txt                   
> supporting-reads_gene-fusions_BLAT.zip    
> viruses_bacteria_phages.txt
> final-list_candidate-fusion-genes.txt                
> fusioncatcher.log.001.bak              
> junk-chimeras.txt          
> supporting-reads_gene-fusions_BOWTIE.zip

**Comment by Coaxecva** [comment]
Looks like it has only hg38:

> ##source=fusioncatcher_v1.33
> ##reference=ftp://ftp.ensembl.org/pub/release-102/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa
> ##assembly=ftp://ftp.ensembl.org/pub/release-102/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa
> ##phasing=none
> ##geneAnnotation=ensembl_v102

**Comment by rpauly** [comment]
Did anyone find a solution this problem? I am looking for the hg19 build as well.
Thanks!

**Comment by Coaxecva** [comment]
Hi @rpauly,

I think you just have to run FusionCatcher with hg38. In the result folder, you will find `final-list_candidate-fusion-genes.hg19.txt` that was converted from hg38.

Previously, I put the option `--skip-conversion-grch37 True` so there wasn't hg19.

Coax
