### ISSUE TITLE
Converting Predicted_fused_transcript column from old version to new version

### ISSUE THREAD

**Issue by amirkdv** [ndaniel/fusioncatcher#127]
Our team works on an analysis tool that, in some cases, needs to operate on already existing FusionCatcher output files produced by our users. A specific issue we need to deal with is this. Our analysis makes heavy usage of the `Predicted_fused_transcripts` column in the "compressed format" but sometimes we have FC output files that were run without  `--compress-transcripts` and thus have different contents in that column. Specifically, we don't want a nucleotide sequence in that column, but rather the "compressed" format that looks like this: `ENST00000445552:346/ENST00000639853:563;ENST00000570550:333/ENST00000639853:563`

By poking around FC source code we have come up with a hacky way of dealing with this (shown below). But since the complexity of FC codebase is quite overwhelming we would like to ask the author if they think our hacky workaround is (a) correct, and (b) can be done in a more robust way.

## Our workaround

Assuming `fc_old.txt` is the old FC output with the "uncompressed" format for the `Predicted_fused_transcript` column we did this (assuming FC/Ensembl version is the same between old FC run and our current installation):

```bash
# remove everything but first 15 cols (up to "Fusion_sequence", excluding last 3)
$ cut -f 1-15 fc_old.txt > fc_old_first15.txt

$ fusioncatcher/install/bin/predict_frame.py \
    --compress-transcripts \ # the missing flag at the time fc_old.txt was produced
    --gtf data/fusioncatcher/human_v90/organism.gtf \
    --transcripts data/fusioncatcher/human_v90/transcripts.fa \
    --input fc_old_first15.txt \
    --output fc_new.txt
```

**Comment by ndaniel** [comment]
This workaround looks correct.

**Comment by amirkdv** [comment]
Thank you @ndaniel! Feel to close this.
