### ISSUE TITLE
ERROR: Workflow execution failed at step 91 while executing:

### ISSUE THREAD

**Issue by lujin518** [ndaniel/fusioncatcher#129]
When I used the fusioncatcher, I got the error as follow. I hope someone can help me solve it.
Python 2.7.15
fusioncatcher 1.0.0
Thanks.
```
==> Current working directory: '/users/lupqy3/.conda/envs/myfusioncatcher/bin'
LC_ALL=C \
cat  \
 /scratch/lupqy3/gene_fusion/results/PBTR-0002/Normal/orig.fq \
|  \
LC_ALL=C  \
paste - - - - - - - - \
|  \
pair8removal.py  \
-l 30 \
-i - \
-o - \
|  \
LC_ALL=C  \
sort  \
-k 2,2 \
-k 6,6 \
-u  \
-t '	' \
--buffer-size 26G \
-T /scratch/lupqy3/gene_fusion/results/PBTR-0002/Normal/tmp/ \
|  \
LC_ALL=C  \
tr  \
"\t"  \
"\n"  \
> /scratch/lupqy3/gene_fusion/results/PBTR-0002/Normal/origi.fq
--------------------------------------------------------------------------------
+-->EXECUTING...


ERROR: Workflow execution failed at step 91 while executing:
------
```

**Comment by ndaniel** [comment]
One way around this might be using a newer version of FusionCatcher that is 1.1.0.
Also the log files (e.g. `fusioncatcher.log` and `info.txt`) for this might be needed in order to be able to propose a fix.

**Comment by lujin518** [comment]
Thanks,but I can not get the newer version(1.1.0) of FusionCatcher using Conda. In conda, the newest version of fusionCatcher is 1.0.0.

**Comment by ndaniel** [comment]
FusionCatcher v1.1.0 can be installed using this one-line command:
```
wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python bootstrap.py -t --download
```

**Comment by ndaniel** [comment]
This looks like is related to https://github.com/ndaniel/fusioncatcher/issues/134
