### ISSUE TITLE
Fusioncatcher Processing .bam Files

### ISSUE THREAD

**Issue by angelussong** [ndaniel/fusioncatcher#130]
Hi, I am working on a project trying to identify fusion events using aligned tumor sample RNAseq .bam files. The .bam files I have are already trimmed and aligned. So when I tried to use fusioncatcher, I would first use samtools fastq to convert .bam files into two paired fastq files.  

But when I ran fusioncatcher, I got this error: 

ERROR: The input FASTQ files do not form a pair!
   - read id from 'FusionCall/G292_1/init-0_G292_1_1.fq' is '@CBKV9ANXX170908:5:2209:4485:2352'
   - mate read id from 'FusionCall/G292_1/init-1_G292_1_2.fq' is '@CBKV9ANXX170908:6:1215:18145:81417'
###################################################################

I'm wondering if there is any way to solve this issue or how could I prepare for the FASTQ inputs that could be processed in fusioncatcher. 

Thank you very much!

**Comment by angelussong** [comment]
Sorry to bother again. I think I solved the problem above by sorting the FASTQ files before using fusioncatcher. However, I'm facing another problem. In my current research, I want to detect all telomere fusion events such as Chr. A: 5’TTAGGGTTAGGGTTAGGGTTAGGG3’ (NNN) fused to (NNN) 5’CCCTAACCCTAACCCTAACCCTAA3’ Chr. B. But the fusioncatcher would use all known genes in the Ensembl database, correct? I'm wondering how I could modify the code to include this kind of detection. Essentially, I think I could detect all telomere repeats myself but I don't know how to feed the information to the gene names to include the search of telomere fusion. 

Thanks very much!

**Comment by ndaniel** [comment]
Yes, only the known genes in ensembl would be used.
The change which you suggest is quite major. Probably would be easier to build something from scratch.
