### ISSUE TITLE
Step 88 creates empty output

### ISSUE THREAD

**Issue by findlaycopley** [ndaniel/fusioncatcher#134]
#####EDIT version 1.1 seems to have fixed this.

I've been trying to run fusion catcher and it'm getting an error on step 91. I saw the issue with another user who had the error here and tried updating to version 1.1 but the issue still appears.

I've gone through the logs and found that step 88 creates an empty file which should normally then be split into read 1 and read 2 files for alignment.

 This then obviously fails at step 91 as the files are empty.

I've tried running step 88 myself and I'm getting an error on the sort step as it can't find the specified delimiter.

Looking at the source the sort is supposed to be
`sort -k2,2 -k6,6 -u -t '\t'`

but in the log file it looks like this:  
`sort -k2,2 -k6,6 -u -t '    '` 
(This might be due to shell expansion whilst writing to the log though I guess ...)

If I manually run the step 88 up to the sort on orig.fq without specifying the delimiter it works and outputs only one copy of any duplicates.

As tab separation is the standard delimiter for sort I've tried commenting out this specific line in the fusioncatcher.py file but I'm still getting an empty origi.fq file.

I'm working on a Centos7 machine.

I've attached my log file:
[fusioncatcher.log](https://github.com/ndaniel/fusioncatcher/files/3559947/fusioncatcher.log)

Thanks for any assistance.

**Comment by ndaniel** [comment]
Hi @findlaycopley 

the [fusioncatcher.log](https://github.com/ndaniel/fusioncatcher/files/3559947/fusioncatcher.log) shows that the ' ' from `sort -k2,2 -k6,6 -u -t ' '` is actually the character tab (line no. 1114).

Would be possible to take a look to the `info.txt` file?

**Comment by findlaycopley** [comment]
Hi @ndaniel thanks for the speedy response!

Here the file:
[info.txt](https://github.com/ndaniel/fusioncatcher/files/3560059/info.txt)

**Comment by ndaniel** [comment]
How the first 16 lines of ´/data/scratch/hfx472/FusionCatcher/Fusion/C0210/orig.fq` look like?

```
head -16 /data/scratch/hfx472/FusionCatcher/Fusion/C0210/orig.fq
```

**Comment by findlaycopley** [comment]
They just look like a regular fastq file: 

[head_orig.fq.txt](https://github.com/ndaniel/fusioncatcher/files/3565306/head_orig.fq.txt)

I have noticed on my info.txt that a lot of the dependencies seem to be missing (probably due to me updating to version 1.1 and no longer using the conda version,  however the error is still occuring at the same place so I don't think that should be it.

**Comment by findlaycopley** [comment]
I tried running it again today, as I couldn't remember if I'd fully removed the run on version 1.0.

Now that I'm using a fresh install of version 1.1 it seems to be creating the oirgi.fq file correctly.

I'll close this now, thanks for your help!

**Comment by ndaniel** [comment]
It looks like this bug affects the conda version of FusionCatcher (that uses FusionCatcher v1.10). It looks like installing a newer version of FusionCatcher (and not using Conda) fixes the issue.
