### ISSUE TITLE
Get paired-end fastq files

### ISSUE THREAD

**Issue by cytcc123** [ndaniel/fusioncatcher#139]
Hi,

I want to visualize fusion genes from fusioncatcher output, however, most programmes support paired-end fastq files. That's the one I got from fusioncatcher output:
[NSD2--RBPJP2__1919187--66635754_reads.fq.zip](https://github.com/ndaniel/fusioncatcher/files/3767020/NSD2--RBPJP2__1919187--66635754_reads.fq.zip)

Could you tell me how to get paired-end fastq files from fusioncatcher?

Thanks a lot,
Yi

**Comment by ndaniel** [comment]
Hi @cytcc123 

That is *already* paired-end fastq file! If one wants to get two FASTQ files out of that then for example `seqtk seq -1` and `seqtk seq -2` could be used.

Cheers,
Daniel
