### ISSUE TITLE
Running fusioncatcher-build fails from within container

### ISSUE THREAD

**Issue by hassanfa** [ndaniel/fusioncatcher#142]
I am trying to run `fusioncatcher-build.py` from within the container but build stops at step 5 where it has to import biopython. The warning message is below:

```
/opt/fusioncatcher/v1.20/tools/biopython/Bio/__init__.py:128: BiopythonWarning: You may be 
importing Biopython from inside the source tree. This is bad practice and might lead to 
downstream issues. In particular, you might encounter ImportErrors due to missing compiled C 
extensions. We recommend that you try running your code from outside the source tree. If you 
are outside the source tree then you have a setup.py file in an unexpected directory: 
/opt/fusioncatcher/v1.20/tools/biopython.
  format(_parent_dir), BiopythonWarning)
Traceback (most recent call last):
  File "/opt/fusioncatcher/v1.20/bin/generate_chrom_lens.py", line 67, in <module>
    import Bio.SeqIO
  File "/opt/fusioncatcher/v1.20/tools/biopython/Bio/SeqIO/__init__.py", line 387, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/opt/fusioncatcher/v1.20/tools/biopython/Bio/Align/__init__.py", line 22, in <module>
    from Bio.Align import _aligners
ImportError: cannot import name _aligners
```

The container I've built is:

https://hub.docker.com/r/hassanf/fusioncatcher

Docker file can be found [here](https://github.com/Clinical-Genomics/BALSAMIC/blob/master/BALSAMIC/containers/FusionCatcher_docker_centos)

And the command I am running:

```
$ singularity exec fusioncatcher_latest.sif \
/opt/fusioncatcher/v1.20/bin/fusioncatcher-build.py \
-g homo_sapiens -o fusioncatcher_data
```

I have also tried to run it shell'ing into container. And I have also tried `-F` option:

```
$ singularity exec fusioncatcher_latest.sif \
/opt/fusioncatcher/v1.20/bin/fusioncatcher-build.py \
-g homo_sapiens -o fusioncatcher_data -F

Traceback (most recent call last):
  File "/opt/fusioncatcher/v1.20/bin/fusioncatcher-build.py", line 398, in <module>
    _OS_ = confs.get("OASES").rstrip("/")+"/" if options.force_paths else ''
AttributeError: 'NoneType' object has no attribute 'rstrip'
```

**Comment by hassanfa** [comment]
Forgot to mention that the goal is to have a leaner container, and build reference data on site.

**Comment by ndaniel** [comment]
Hi,

it is not clear to me what is the the error from step 5.

Anyway, the way around that is to download the pre-built files for human. There is no need to build them. See here how those can be download and installed: https://github.com/ndaniel/fusioncatcher/blob/master/data/download-human-db.sh

I looked to the docker file and I was wondering if this line is really necessary:
```
&& conda install -y -c conda-forge -c bioconda openpyxl numpy parallel \
```
because this might cause many issues right due to conda installation of FusionCatcher installs and old version of FusionCatcher that is v1.10.

Probably the best for now would be to install it FusionCatcher without conda.
Another comment, is that FusionCatche does not really need openpyxl and parallel. Numpy and bioPython is better to install them using yum, something like:
```
yum install -y python-devel python-numpy python-biopython
```

**Comment by hassanfa** [comment]
Daniel, Thanks for the quick feedback.

I had some issues with `yum install -y python-devel ...` where fusioncatcher couldn't find the numpy. So after playing around with it, so I decided to use conda to install those. I'll skip `openpyxl` and `parallel` as well.

I'm building a new container now, and I will update here as soon as it is finished.

**Comment by ndaniel** [comment]
Thanks for the update @hassanfa 

Actually, FusionCatcher does not uses NumPy directly. NumPy is a dependency of BioPython. So if you can install BioPython, and BioPython works (without complaining about NumPy) then everything should be fine.

**Comment by hassanfa** [comment]
Daniel, it seems the issue was my conda being in the PATH and not allowing `fusioncatcher-build.py` to find correct Python modules. I changed the container to the following and it is working as intended. Thank you for your comments and help.

```
FROM centos:7.6.1810

LABEL Description="This image is used to run FusionCatcher" Version="1.20"

RUN yum install -y epel-release \
    && yum install -y \
    automake \
    which \
    git \
    bzip2 \
    cmake \
    curl \
    gawk \
    gcc \
    gzip  \
    ncurses \
    ncurses-devel \
    make \
    pigz \
    tar \
    unzip \
    wget \
    zlib-devel \
    java-1.8.0-openjdk* \
    tbb-devel \
    glibc-devel \
    python-devel \
    numpy \
    python-biopython \
    && wget --no-check-certificate http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py \
    && python bootstrap.py --help \
    && python bootstrap.py -t -y -i /opt/fusioncatcher/v1.20/

WORKDIR /opt
```

**Comment by ndaniel** [comment]
@hassanfa 

Great!

I guess that I see a typo though. `numpy` should be `python-numpy` above?

**Comment by hassanfa** [comment]
In CentOS repo I found it to be just `numpy`: http://mirror.centos.org/centos/7/os/x86_64/Packages/

Here is also the output from my vagrant:
```
(base) [vagrant@localhost ~]$ yum search numpy
Loaded plugins: fastestmirror
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Determining fastest mirrors
 * base: mirror.hh.se
 * extras: mirror.hh.se
 * updates: mirror.hh.se
================================================================================= N/S matched: numpy ==================================================================================
numpy-f2py.x86_64 : f2py for numpy
numpy.x86_64 : A fast multidimensional array facility for Python

  Name and summary matches only, use "search all" for everything.
(base) [vagrant@localhost ~]$ yum search python-numpy
Loaded plugins: fastestmirror
Repodata is over 2 weeks old. Install yum-cron? Or run: yum makecache fast
Loading mirror speeds from cached hostfile
 * base: mirror.hh.se
 * extras: mirror.hh.se
 * updates: mirror.hh.se
Warning: No matches found for: python-numpy
No matches found
(base) [vagrant@localhost ~]$ rpm -q centos-release
centos-release-7-6.1810.2.el7.centos.x86_64
```

**Comment by ndaniel** [comment]
Indeed you are correct! My bad!
I corrected it in Dockerfile for CentOS!
Thanks again!
