### ISSUE TITLE
Wrong version of BBMAP found

### ISSUE THREAD

**Issue by akesarwani** [ndaniel/fusioncatcher#146]
Fusioncatcher v1.2 isssues:
```
ERROR: Wrong version of BBMAP found
Found 'exception in thread "main" java.lang.noclassdeffounderror: java/util/concurrent/threadlocalrandom'. It should be 'bbmap version 38.44'. One may specify the path to the correct version in 'fusioncatcher/etc/configuration.cfg'.
```

**Comment by ndaniel** [comment]
That looks more like BBMAP is not installed at all.

Would be possible to have the logs of the run (ie. `fusioncatcher.log` & `info.txt`) which produced this error?

**Comment by akesarwani** [comment]
**Log of the pipeline:**
--------------------------------------------------------------------------------
Starting execution with step 21.
////////////////////////////////////////////////////////////////////////////////
  Running: step = 1   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
printf \
"
================================================
Software version: fusioncatcher.py 1.20
================================================


"  \
> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/info.txt
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 2   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
printf \
"
Software version: fusioncatcher.py 1.20
"  \
>> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/fusioncatcher.log
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 3   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'

--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 4   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'

--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 5   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
Skipping from erasing '/projects/compsci/Anil/tools/fusioncatcher/data/human_v98/version.txt' (size: 1253 bytes)
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 6   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'

--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 7   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
Skipping from erasing '/projects/compsci/Anil/tools/fusioncatcher/data/human_v98/genome_information.txt' (size: 98 bytes)
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 8   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
printf \
"
Linux:
------
"  \
>> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/info.txt
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 9   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
cat \
/etc/issue  \
2>&1  \
>> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/info.txt
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 10   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
printf \
"
Python:
------
"  \
>> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/info.txt
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 11   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
python_version.py \
>> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/info.txt
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 12   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
printf \
"
BioPython:
------
"  \
>> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/info.txt
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 13   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
biopython_version.py \
>> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/info.txt
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 14   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
printf \
"
===========
TOOLS:
===========
"  \
>> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/info.txt
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 15   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
printf \
"
SORT:
------
"  \
>> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/info.txt
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 16   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
sort \
--version  \
|  \
head -1 \
>> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/info.txt
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 17   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
printf \
"
BOWTIE:
------
"  \
>> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/info.txt
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 18   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
bowtie \
--version  \
|  \
head -2 \
>> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/info.txt
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 19   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
printf \
"
BBMAP:
------
"  \
>> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/info.txt
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 20   Time: 10:12   Date: 2019-11-27 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2'
bbmap.sh \
--version  \
2>> /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/info.txt
--------------------------------------------------------------------------------
|==> SKIPPED because of the step count.
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
################################################################################
################################################################################
TOTAL RUNNING TIME: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s) 
################################################################################
################################################################################

**Comment by akesarwani** [comment]
**================================================
Software version: fusioncatcher.py 1.20
================================================**


===================================
GENOME INFORMATION:
===================================
fusioncatcher-build.py 1.20
Ensembl database version: 98
Organism: Homo sapiens
Genome version: GRCh38
NCBI Viral Genomes version: 2019-09-12
UCSC database version (hg38): 2018-11-18
RefSeq NCBI database version (downloaded thru UCSC database; hg38): 2019-07-28
Gencode database version: 32
Non-cancer tissues and cells (Babiceanu et al. Nucl. Acids Res. 2016) database version: 2019-10-07
Cancer Gene List database version: 2019-10-07
Oncogenes database version: 2019-10-07
TumorFusions (Hu et al. Nucleic Acids Research) database version: Nov. 2017
TCGA Fusions Dataset (Qingsong G., Cell Reports, 2018) version: April 2018
Cell lines (Klijn et al. Nature Biotechnology 2014) database version: 2019-10-07
Prostate Tumor Patients (Robison et al. Cell 2015) database version: 2019-10-07
Pancreatic Tumor Patients (Bailey et al. Nature 2016) database version: 2019-10-07
ChimerDB database version: 2.0
ChimerDB database version: 3.0
TICdb database version: 2019-10-07
ConjoinG database version: 2019-10-07
CGP database version: 2019-10-07
CACG database version: 2019-10-07
DGD database version: 2019-10-07
GTEx database version (thru FusionAnnotator): 2019-10-08
OncoKB (Chakravarty et al., JCO PO 2017): 2019-10-08
Mitelman database version: 2019-10-08

===================================
Genome FASTA files:
===================================
ftp.ensembl.org//pub/release-98/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa




Linux:
------
CentOS release 6.5 (Final)
Kernel \r on an \m


Python:
------
Python version: 2.7.14 (default, Apr  5 2018, 16:05:15) 
[GCC 4.9.2]
Python executable: /opt/software/helix/python/2.7.14/bin/python

BioPython:
------
1.74

===========
TOOLS:
===========

SORT:
------
sort (GNU coreutils) 8.4

BOWTIE:
------
/projects/compsci/Anil/tools/fusioncatcher/tools/bowtie-1.2.3-linux-x86_64/bowtie-align-s version 1.2.3
64-bit

BBMAP:
------
java -ea -Xmx192125m -cp /projects/compsci/Anil/tools/fusioncatcher/tools/bbmap/current/ align2.BBMap build=1 overwrite=true fastareadlen=500 --version
Exception in thread "main" java.lang.NoClassDefFoundError: java/util/concurrent/ThreadLocalRandom
	at align2.AbstractMapper.<init>(AbstractMapper.java:46)
	at align2.BBMap.<init>(BBMap.java:43)
	at align2.BBMap.main(BBMap.java:31)
Caused by: java.lang.ClassNotFoundException: java.util.concurrent.ThreadLocalRandom
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:201)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:200)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:325)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:296)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:270)
	... 3 more
java -ea -Xmx148860m -cp /projects/compsci/Anil/tools/fusioncatcher/tools/bbmap/current/ align2.BBMap build=1 overwrite=true fastareadlen=500 --version
Exception in thread "main" java.lang.NoClassDefFoundError: java/util/concurrent/ThreadLocalRandom
	at align2.AbstractMapper.<init>(AbstractMapper.java:46)
	at align2.BBMap.<init>(BBMap.java:43)
	at align2.BBMap.main(BBMap.java:31)
Caused by: java.lang.ClassNotFoundException: java.util.concurrent.ThreadLocalRandom
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:201)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:200)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:325)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:296)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:270)
	... 3 more
java -ea -Xmx14286m -cp /projects/compsci/Anil/tools/fusioncatcher/tools/bbmap/current/ align2.BBMap build=1 overwrite=true fastareadlen=500 --version
BBMap version 38.44
For help, please run the shellscript with no parameters, or look in /docs/.

PIGZ:
------
pigz 2.3.3

PXZ:
------

fastq-dump (from SRA Toolkit):
--------------
fastq-dump : 2.9.6

GNU Parallel:
--------------

SAMTools:
---------
Version: 1.7 (using htslib 1.7)

liftOver:
---------
liftOver: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by liftOver)

SeqTK:
---------
Version: 1.2-r101c-dirty

sed:
---------
GNU sed version 4.2.1

awk:
---------
GNU Awk 3.1.7

BLAT:
------

faToTwoBit (from BLAT toolbox):
----------------
faToTwoBit: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by faToTwoBit)

STAR:
------
2.7.2b


BOWTIE2:
------
/projects/compsci/Anil/tools/fusioncatcher/tools/bowtie2/bowtie2-align-s version 2.3.5.1
64-bit



Pipeline parameters:
====================
aligners = /projects/compsci/Anil/tools/fusioncatcher/etc/configuration.cfg,blat,star
all_reads_junction = False
ambiguous_filtering = False
ambiguous_mismatches = 2
assembly = False
batch_mode = False
biotypes = 1000genomes,7skrna,ambiguous,banned,bodymap2,conjoing,cta,ctb,ctc,ctd,dist1000bp,ensembl_fully_overlapping,ensembl_same_strand_overlapping,fragments,healthy,hla,hpa,metazoa,mirna,mt,multi,pair_pseudo_genes,paralogs,refseq_fully_overlapping,refseq_same_strand_overlapping,removed,rp,rp11,rrna,similar_reads,similar_symbols,snorna,snrna,trna,yrna
bridges = 0
checksums_filename = checksums.txt
chunkmbs = 128
compress_transcripts = False
configuration_filename = /projects/compsci/Anil/tools/fusioncatcher/etc/configuration.cfg,/projects/compsci/Anil/tools/fusioncatcher/bin/configuration.cfg
data_directory = /projects/compsci/Anil/tools/fusioncatcher/data/human_v98
extract_buffer_size = 1000000000
ff_tryhard = False
filter_mismatches = 2
filter_str = 0
force_paths = False
gap_wiggle_size = 2
hash = no
homolog = 1.25e-05
input_filename = /projects/compsci/Anil/fusionseq/rna_fastqs_for_fusions
keep_preliminary = False
keep_temporary_files = False
keep_unmapped_reads = False
keep_viruses = False
length_anchor = 17,17,17,17,40
length_anchor2 = 47
length_anchor_gap = 17
length_anchor_gap_max = 100
length_gap = 21
limitOutSJcollapsed = 1000000
limitSjdbInsertNsj = 2000000
limit_blat = 3221225472
limit_bowtie = 4294867296
limit_bowtie2 = 30000000
limit_star = 500000000
long_report = False
min_dist = 200000
mismatches = 2
mismatches_gap = 7
mismatches_psl = 2
output_directory = results
paranoid_sensitive = False
processes = 1
psl_visualization = False
reads_preliminary_fusions = False
rescue_gap_size = 0
rescue_wiggle_size = 0
sam_visualization = False
single_end = False
skip_adapter_filtering = False
skip_adjacent = False
skip_automatic_scaling = False
skip_b_filtering = False
skip_banned_fusions = False
skip_bbmerge = False
skip_bbmerge_auto = False
skip_blat = False
skip_bowtie2 = True
skip_compress_ids = False
skip_conversion_grch37 = False
skip_deduplication = False
skip_extension = False
skip_fast = False
skip_filter_low_entropy = False
skip_genome_filtering = False
skip_genome_transcriptome_filtering = False
skip_ig_star = False
skip_interleave_processing = False
skip_known_fusions = False
skip_mitochondrion_filtering = False
skip_prefiltering_psl = False
skip_spotlight = False
skip_star = False
skip_star_bowtie = False
skip_trim_multiple_5 = False
skip_unmapped_pairs_filtering = False
skip_update_check = False
skip_viruses_filtering = False
sonication = 130
sort_buffer_size = 80%
spanning_pairs = 3,3,3,3,3
spanning_pairs_count = 8000
spanning_reads = 2,2,2,2,2
split_seqtk_subseq = 1
start_step = 0
tmp_directory = /projects/compsci/Anil/fusionseq/fusioncatcher/v1.2/results/tmp
trim_3end = 0
trim_3end_keep = 60
trim_3end_keep2 = 23
trim_5end = 0
trim_psl = False
trim_psl_3end_keep = 82
trim_psl_5end = False
trim_quality = 5
trim_wiggle = 0
trimfq = 1.0
xmx = 18g
main_script = /projects/compsci/Anil/tools/fusioncatcher/bin/fusioncatcher.py
main_script_version = 1.20

Current working directory:
---------------------------
/projects/compsci/Anil/fusionseq/fusioncatcher/v1.2

Command line used for launching FusionCatcher:
----------------------------------------------
/projects/compsci/Anil/tools/fusioncatcher/bin/fusioncatcher.py \ 
-i \ 
/projects/compsci/Anil/fusionseq/rna_fastqs_for_fusions \ 
-d \ 
/projects/compsci/Anil/tools/fusioncatcher/data/human_v98 \ 
-o \ 
results \ 
-p \ 
1
----------------------------------------------



Shebang for Python scripts:
---------------------------
#!/opt/software/helix/python/2.7.14/bin/python




===================
CONFIGURATION.CFG:
===================
[paths]
python = /opt/software/helix/python/2.7.14/bin
data = /projects/compsci/Anil/tools/fusioncatcher/data/current
scripts = /projects/compsci/Anil/tools/fusioncatcher/bin
bowtie = /projects/compsci/Anil/tools/fusioncatcher/tools/bowtie
bowtie2 = /projects/compsci/Anil/tools/fusioncatcher/tools/bowtie2
bwa = /projects/compsci/Anil/tools/fusioncatcher/tools/bwa
blat = /projects/compsci/Anil/tools/fusioncatcher/tools/blat
liftover = /projects/compsci/Anil/tools/fusioncatcher/tools/liftover
star = /projects/compsci/Anil/tools/fusioncatcher/tools/star/source
velvet = /projects/compsci/Anil/tools/fusioncatcher/tools/velvet
fatotwobit = /projects/compsci/Anil/tools/fusioncatcher/tools/fatotwobit
samtools = /projects/compsci/Anil/tools/fusioncatcher/tools/samtools
seqtk = /projects/compsci/Anil/tools/fusioncatcher/tools/seqtk
sra = /projects/compsci/Anil/tools/fusioncatcher/tools/sratoolkit/bin
numpy = /opt/software/helix/python/2.7.14/lib/python2.7/site-packages/numpy
biopython = /projects/compsci/Anil/tools/fusioncatcher/tools/biopython
xlrd = /projects/compsci/Anil/tools/fusioncatcher/tools/xlrd
openpyxl = /projects/compsci/Anil/tools/fusioncatcher/tools/openpyxl
lzo = /projects/compsci/Anil/tools/fusioncatcher/tools/lzo
lzop = /projects/compsci/Anil/tools/fusioncatcher/tools/lzop/src
pigz = /projects/compsci/Anil/tools/fusioncatcher/tools/pigz
pxz = /projects/compsci/Anil/tools/fusioncatcher/tools/pxz
picard = /projects/compsci/Anil/tools/fusioncatcher/tools/picard
bbmap = /projects/compsci/Anil/tools/fusioncatcher/tools/bbmap
parallel = /projects/compsci/Anil/tools/fusioncatcher/tools/parallel/src
java = /usr/bin/

[parameters]
threads = 1
aligners = blat,star

[versions]
fusioncatcher = 1.20





============
DATA DIRECTORY:
============
/projects/compsci/Anil/tools/fusioncatcher/data/human_v98/
It is not a link!



============
MEMORY:
============
             total       used       free     shared    buffers     cached
Mem:         64385      57664       6721          0        786      10001
-/+ buffers/cache:      46875      17510
Swap:         4096       3504        591

Total installed RAM memory = 64385 MB



Input files (which contain the short reads):
--------------------------------------------
/projects/compsci/Anil/fusionseq/rna_fastqs_for_fusions/PositiveControl_S11_L001_R1_001.fastq.gz
/projects/compsci/Anil/fusionseq/rna_fastqs_for_fusions/PositiveControl_S11_L001_R2_001.fastq.gz
/projects/compsci/Anil/fusionseq/rna_fastqs_for_fusions/PositiveControl_S11_L002_R1_001.fastq.gz
/projects/compsci/Anil/fusionseq/rna_fastqs_for_fusions/PositiveControl_S11_L002_R2_001.fastq.gz
/projects/compsci/Anil/fusionseq/rna_fastqs_for_fusions/PositiveControl_S11_L003_R1_001.fastq.gz
/projects/compsci/Anil/fusionseq/rna_fastqs_for_fusions/PositiveControl_S11_L003_R2_001.fastq.gz
/projects/compsci/Anil/fusionseq/rna_fastqs_for_fusions/PositiveControl_S11_L004_R1_001.fastq.gz
/projects/compsci/Anil/fusionseq/rna_fastqs_for_fusions/PositiveControl_S11_L004_R2_001.fastq.gz

**Comment by ndaniel** [comment]
Hi @akesarwani 

it looks like Java is not installed or is a very old version of Java.
When you run this :
```
java --version
```
what does it show?

**Comment by akesarwani** [comment]
/projects/compsci/Anil/tools/fusioncatcher/tools/bbmap/bbmap.sh --version
java -ea -Xmx13564m -cp /projects/compsci/Anil/tools/fusioncatcher/tools/bbmap/current/ align2.BBMap build=1 overwrite=true fastareadlen=500 --version
BBMap version 38.44
For help, please run the shellscript with no parameters, or look in /docs/.

**Comment by ndaniel** [comment]
And what does this show `which java`?

**Comment by akesarwani** [comment]
/opt/compsci/java/jdk1.8.0_20/bin/java

**Comment by ndaniel** [comment]
It looks like Java 1.8 is not found by FusionCatcher.
Therefore the fix for this is to edit manually the configuration file of FusionCatcher that is `/projects/compsci/Anil/tools/fusioncatcher/etc/configuration.cfg`
and the line
```
java=/usr/bin
```
should be
```
java=/opt/compsci/java/jdk1.8.0_20/bin
```

**Comment by akesarwani** [comment]
Thanks. I was wondering if the fusioncather 1.2 has all bug fixes for conda

**Comment by ndaniel** [comment]
Hi @akesarwani 

it depends when some volunteer will step in and upgrade the bioconda recipe for FusionCatcher 1.20.

**Comment by ndaniel** [comment]
Hi @akesarwani , if you feel that this issue is not yet solved please feel free to re-open it!
