### ISSUE TITLE
error during running script download-human-db.sh

### ISSUE THREAD

**Issue by ConcettaDe4** [ndaniel/fusioncatcher#149]
Hi! 
I have installed the latest version of Fusioncatcher (v1.20) from GitHub. 

When I ran the command two times:

`./download-human-db.sh`

I got the following error every time: 

```
Saving to: ‘human_v98.md5’

     0K                                                       100% 28,1M=0s

2019-12-05 17:10:57 (28,1 MB/s) - ‘human_v98.md5’ saved [216/216]

human_v98.tar.gz.aa: OK
human_v98.tar.gz.ab: OK
human_v98.tar.gz.ac: OK
human_v98.tar.gz.ad: OK
tar: data: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now



   ERROR: The downloaded files are corrupted! Please, download them again or re-run this script again!
```
 How can I solve this error?

Thank you.

Concetta

**Comment by ndaniel** [comment]
Hi @ConcettaDe4 

if you run this at command line `ls` (in the directory where `./download-human-db.sh` was run), what does it show?

**Comment by ConcettaDe4** [comment]
Hi!

Here is the ls command:

```
s@hiseq:/home/FusionCatcher/v_1.20/fusioncatcher/data$ ls -ltr

-rw-rw-r-- 1 ale ale         216 nov  6 21:26 human_v98.md5
-rwxrwxr-x 1 ale ale        1318 dic  2 20:25 download-human-db.sh
drwxrwxr-x 2 ale ale          80 dic  5 18:30 human_v98
lrwxrwxrwx 1 ale ale           9 dic  5 18:30 current -> human_v98
-rw-rw-r-- 1 ale ale 18119834261 dic  5 20:24 human_v98.tar.gz

```
Thank you!

**Comment by ndaniel** [comment]
It looks like everything is fine!
You may run fusioncatcher/test/test.sh to chrck that it works.

**Comment by ConcettaDe4** [comment]
Hi!
I extracted the files from human_v98.tar.gz and I got 149 files in the folder human_v98. 
I tested the checked if fusioncatcher works using fusioncatcher/test/test.sh . 
I got the following error:
```
 File "./../bin/fusioncatcher.py", line 1624
    print "EXAMPLE:"
                   ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "EXAMPLE:")?
diff: test_fusioncatcher/summary_candidate_fusions_a.txt: File o directory does not exist
diff: test_fusioncatcher/summary_candidate_fusions_b.txt: File o directory does not exist



   WARNING: Test is NOT ok! There is something wrong with FusionCatcher installation!

```

How can I solve it?

Thank you!

Concetta

**Comment by ndaniel** [comment]
That error is because Python 3.X is used instead of Python 2.7.x.
Python 2.7.x should be used!

**Comment by ConcettaDe4** [comment]
I am using python version 2.7.15 and I run Fusioncatcher. 

I get the following error: 

`////////////////////////////////////////////////////////////////////////////////
  Running: step = 11   Time: 11:52   Date: 2019-12-10 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/home/stefania/Brusco/fusionCatcher_version1_20'
python_version.py \
>> /home/stefania/Brusco/fusionCatcher_version1_20/info.txt
--------------------------------------------------------------------------------
+-->EXECUTING...


ERROR: Workflow execution failed at step 11 while executing:
----------------
   python_version.py \
   >> /home/stefania/Brusco/fusionCatcher_version1_20/info.txt
----------------
Please, check if 'Python' (from <http://python.org/>) is installed (or if 'configuration.cfg' file is set up correctly)!
  * Size '/home/stefania/Brusco/fusionCatcher_version1_20/info.txt' = 1738 bytes


Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------
  File "/home/stefania/fusion_catcher_installation/fusioncatcher/bin/python_version.py", line 44
    print "Python version: " + sys.version
                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Python version: " + sys.version)?

`

**Comment by ndaniel** [comment]
Sorry, but for some reason Python 3 is used to run FusionCatcher instead of Python 2. The error message suggests this:
```
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(".....")?
```
For more regarding this see: https://stackoverflow.com/questions/25445439/what-does-syntaxerror-missing-parentheses-in-call-to-print-mean-in-python

When you run this command `/usr/bin/env python --version` what does it show?

**Comment by ConcettaDe4** [comment]
It shows :

`Python 2.7.15`

**Comment by ndaniel** [comment]
Ok. When you run this `head -3 /home/FusionCatcher/v_1.20/fusioncatcher/bin/fusioncatcher.py` what does it show?

**Comment by ConcettaDe4** [comment]
It shows :

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""

```

**Comment by ndaniel** [comment]
Ok. Run these commands:
```
mv /home/FusionCatcher/v_1.20/fusioncatcher/bin/fusioncatcher.py /home/FusionCatcher/v_1.20/fusioncatcher/bin/fusioncatcher__old.py

printf "/usr/bin/env python\nimport sys\nsys.stdout.write(str(sys.version_info))\n" > /home/FusionCatcher/v_1.20/fusioncatcher/bin/fusioncatcher.py
chmod +x /home/FusionCatcher/v_1.20/fusioncatcher/bin/fusioncatcher.py
```
and afterwards run `fusioncatcher/test/test.sh`. What does it show?

P.S. This prints the Python version from within FusionCatcher.

**Comment by ndaniel** [comment]
Please, re-open if this is still and issue!
