### ISSUE TITLE
what dose SPOTLIGNT mean?

### ISSUE THREAD

**Issue by xiucz** [ndaniel/fusioncatcher#151]
Hi, @ndaniel 

what is the meaning of SPOTLIGNT? I did not find details about it in the doc. Please see the link here https://github.com/ndaniel/fusioncatcher/issues/115. 

Thank you very much.

Xiucz

**Comment by ndaniel** [comment]
Hi @xiucz 

Spotlight is a different method of finding fusion genes. The methods used to find fusion genes within FusionCacher are:
- BOWTIE
- BOWTIE+BLAT
- BOWTIE+STAR
- BOWTIE+BOWTIE2
- BOWTIE+SPOTLIGHT (which actually uses BBMAP aligner)

Cheers,
Daniel

**Comment by xiucz** [comment]
@ndaniel 
Thanks for your quick reply

I also got confused, there are two different aligner methods, but the first result's coordinate is not consistent with the `Fusion_sequence`. Please see blow:
  
The first result  3-end(4:106530738:+) fasta is from the ucsc genome fasta. 

1. How was this coordinate specified to the sequence? 
2. Which result should I choose for IGH@-NSD2 fusion event?

```
$ grep IGH final-list_candidate-fusion-genes.txt  |grep NSD2
IGH@    NSD2    known,oncogene,chimerdb2,cancer,tumor,m4,mitelman       0       7       4       112     BOWTIE+SPOTLIGHT        14:106543230:+4:106530738:+    ENSG09000000017 ENSG00000109685                 TTTCTGTGTCTGACTCATTTCACTCAACATAGTGGTGTCCCATTCCATCCATGTTGCTTTAA*AGTTGCTTGATTTTAGTGGCTCAGAACTGCAATTTAATTCTTGTTCTTTGCACCTCTCTCTCCACCCCTTCTTTAACTTTTTGTTAGGGATTCACTCATGTTTCGTGTGTAA        ---/intergenic
IGH@    NSD2    known,oncogene,chimerdb2,cancer,tumor,m4,mitelman       0       7       3       36      BOWTIE+BLAT;BOWTIE+STAR 14:106543230:+4:1953237:+      ENSG09000000017 ENSG00000109685                 ACTCATTTCACTCAACATAGTGGTGTCCCATTCCATCCATGTTGCTTTAA*AGTTGCTTGATTTTAGTGGCTCAGAACTGCAATTTAATTCTTGTTCTTTG  ---/CDS(truncated)
```

```
$bedtools getfasta -s -fi ucsc.hg38.fasta -bed  NSD2.bed -fo  test.fa
>chr4:106530738-106531748(+)
AAGCTCACATAGAGGCATATATTTTCTTAAAGAAGTCATGTTAGAATCATTTTGCTAAAATATCACATCTGTCTTACAGAAATTACAACAGAAAAGCAACAAGATTACAAAATCATTTCAAAATAAATATTGTACCAACCTAATGGAAAAACATCTGTGCTGTTTTAGCTTATTACAGCAGTTTGTCATGACAATTTATAGATAAGTATGCAATTTTTCTTAGATTTATTATTGGAAACTTCTACTTATAGGTCTGTGGTTTAAGACAGGAAATGTGTTTTGATTGATTATCCTGAAAAGAAATTGGTAGGCCAAATGTTGAAACCATGAAAACATTAGGAGATGAAGTAACAGTTGAAAAAATGAACTGCACTTTGGAAGAACTCACAGGAGTAGTGATGATTGTACCACTAAATCTTGTGCTTGTTTACCAAAGTTGAGAGAGAAAAATTTCAGTTGAACTAGTATGTAGAGTGATACTCTGGTTTCTCTTGAGATGGTATAAATCTTTTGCCTTTTACTAGTATGTAGAGTGATATGAGAATTCCCTCTAATAGGCAAGTGAATGGAGAGTAGATAATATAACAACTGAGAAAATATAATCCTTAACCCTTCAAAAGAAAATATTTCTTCAAGAAGTGGGTACAAGCAAAGCAATTCAATAAATTAGAAATACATTATGATTATAAGGACAGTGCATTTAGAGTTCCCAATGACCTGATTTAACTATTAAAAATATACACAGGCAAACCATACACTAAATCATAATAGCCGATTTTAGAATTCCTCTCAGGAAGAGCACTGTCTTAGCTTGAGTGGCTGTAGATAGTAAGATCCTTAGGATATGGGTTGGTAGGCACAAAGAATAAGTACATCTTCATATAATAACAAACAAGCATGTAACAAACAGGAATTTGGTAATTGAGAGGACAGCAGAAATGAGAGAAAAGAGAAAGTAAGAGAAAGTTGAATTACATAGTGAAATTCTGGAGCCCAAATTGGGGAAAAGA
```

Thank you very much.
Xiucz

**Comment by ndaniel** [comment]
Indeed two different aligner methods give different results. STAR and BLAT aligns the same reads differently than BBMAP (thru SPOTLIGHT). This is normal. Some aligners align the same reads differently than other aligners, as it happens in this case. This is why the same fusion gene is found with two different genomic coordinates which give different fusion sequence. Therefore both should be validated.

**Comment by xiucz** [comment]
thank you , I will look into BBMAP's SPOTLIGHT method and I will close this issue.

**Comment by ndaniel** [comment]
@xiucz 

SPOTLIGHT is the name of the method used by FusionCatcher. SPOTLIGHT uses BBMAP aligner.

BBMAP aligner has no SPOTLIGHT method.
