### ISSUE TITLE
ERROR: The input FASTQ file is not in a supported FASTQ format

### ISSUE THREAD

**Issue by suhrig** [ndaniel/fusioncatcher#152]
Hi Daniel,

I am trying to process this sample from the SRA: SRR5163549
But FusionCatcher fails to detect the FastQ format:

```
ERROR: Workflow execution failed at step 60 while executing:
----------------
   solexa18to15.py \
   --fail  \
   --input /tmp/fusioncatcher/output/init-0_SRR5163549.fastq \
   --output /tmp/fusioncatcher/output/init-head-0_SRR5163549.fastq \
   --link hard
----------------
  * Size '/tmp/fusioncatcher/output/init-0_SRR5163549.fastq' = 11586070 bytes
  * Size '/tmp/fusioncatcher/output/init-head-0_SRR5163549.fastq' = 0 bytes


Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------
Starting...
ERROR: The input FASTQ file is not in a supported FASTQ format, which are:
 - version 1.5 (i.e. read names end with /1 or /2 and contain no blank characters)
 - version 1.8 (e.g. read name looks like '@GQWE8:57:C00T6ABXX:2:1101:1233:2230 1:N:0:CTTGTA')
The read names in the input file look like this '@1' but it should look like this '@GQWE8:57:C00T6ABXX:2:1101:1233:2230 1:N:0:CTTGTA' (i.e. there should be 6 of ':' in read name, one blank space between read name and description, description should be in this format '1:N:0:CTTGTA')
```

I tried fixing the read names manually to match the expected format. `solexa18to15.py` then completes successfully. But a later step aborts with this error:

```
////////////////////////////////////////////////////////////////////////////////
  Running: step = 83   Time: 11:11   Date: 2020-01-29 (elapsed time: 0d:0h:22m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/tmp/fuERROR: Too many reads have been removed during the pre-filtering steps!
Please, check that the input files are from a RNA-seq dataset with pair-reads 
or that the input files are given correctly!Please, check that also the input reads have the same length!
```

It's single-end data and the read length is 100nt. I read somewhere in the manual that single-end data is only supported if the read length exceeds 130nt. Can FusionCatcher deal with this sample or should I stop trying to get it to work?

Thanks,
Sebastian

**Comment by ndaniel** [comment]
Hi @suhrig 

What version of FusionCatcher is used?
What is the command line used to run FusionCatcher?
Do you give as input the SRA file or FASTQ files?

These info can be found in file ''info.txt".

**Comment by suhrig** [comment]
> What version of FusionCatcher is used?

1.00 and 1.20

> What is the command line used to run FusionCatcher?

fusioncatcher.py -d /tmp/fusioncatcher/data/human_v98 -i SRR5163549.fastq -o output --limitSjdbInsertNsj 2000000

> Do you give as input the SRA file or FASTQ files?

I tried both. Passing the SRA file does not work at all. FusionCatcher complains that it is single-end data and aborts pretty early. I have to convert the SRA to FastQ using fastq-dump to get the pipeline to the step described in my initial post.

**Comment by ndaniel** [comment]
The single-end reads are 101 bp long.
FusionCatcher needs at least 130 bp long for single-end input.

For single-end reads of 130bp or longer the FusionCatcher needs the command line parameter '--single-end', like this:
```
fusioncatcher.py -d /tmp/fusioncatcher/data/human_v98 --single-end -i SRR5163549.fastq -o something
```

**Comment by suhrig** [comment]
Many thanks for the clarification!
