### ISSUE TITLE
can fusioncatcher take alignment/junction output of STAR as input

### ISSUE THREAD

**Issue by jzjsoil** [ndaniel/fusioncatcher#153]
Hi ndaniel,
we have processed all RNAseq samples by STAR, and wondering if fusioncatcher can use STAR output (genome alignment, chimeric alignment, junction file) as input.

Thanks,
Z

**Comment by ndaniel** [comment]
Unfortunately, FusionCatcher is using only raw sequencing data. FC uses internally by default at least 4 aligners, that are Bowtie, Blat, STAR and BBMap. All of these have their different weaknesses and strengths.
