### ISSUE TITLE
Error in Bowtie installation

### ISSUE THREAD

**Issue by suhana13** [ndaniel/fusioncatcher#155]
Hey,
I tried the automatic installation of fusion catcher via the bootstrap python script. After, the installation was complete, I ran the test bash script but I got the following error:
```
ERROR: Wrong version of BOWTIE found ()! It should be: version 1.1.2, version 1.2, version 1.2.2, version 1.2.3.

ERROR: One may specify the path to the correct version in 'fusioncatcher/etc/configuration.cfg',

ERROR: like for example change manually the line fusioncatcher/tools/bowtie to fusioncatcher/tools/bowtie-old

ERROR: Also it may be that some of Bowtie's dependencies are missing.

ERROR: Therefore also make sure that Bowtie's dependencies are installed, like for example:

ERROR:    sudo apt-get install libtbb-dev libtbb2 libc6-dev

ERROR: or

ERROR:    sudo yum install libtbb-devel libtbb2 libc6-devel
```
So, I already have bowtie installed on my system and therefore, I tried changing the path of bowtie in the config file but it gave me the same error.
I am a Mac user and I don't have yum and apt-get installation options, However, I installed tbb via Mac port and it still gives me the same error.
Your help will be truly appreciated.

Best,
Suhana

**Comment by ndaniel** [comment]
Could you post the file "info.txt" that was created during the run test?

**Comment by suhana13** [comment]
Hey, 
Pardon me for the late response!
Apparently. there was no info.txt created during the run test.

**Comment by ndaniel** [comment]
That is strange.

One could try to remove FusionCatcher and install it again.
