### ISSUE TITLE
intronic-intronic fusion

### ISSUE THREAD

**Issue by stellaoh** [ndaniel/fusioncatcher#158]
Dear Daniel, 

Hi I'm Oh. 

I used mRNA-sequencing data for detecting fusions. 

I didn't understand how to detect intronic-intronic fusions. 

In mRNA-sequencing data, I think, they have only sequences from exonic regions. 

Many Thanks. 

Oh.

**Comment by ndaniel** [comment]
Hi @stellaoh 

For some fusion genes FusionCatcher is able to detect fusion genes where the fusion junction takes place within introns.
In general fusion genes that have fusion junctions within introns are very challeging for all fusion callers.

Cheers,
Daniel
