### ISSUE TITLE
missing metastasis.txt

### ISSUE THREAD

**Issue by gaborbedics** [ndaniel/fusioncatcher#159]
IOError: [Errno 2] No such file or directory: '/metastasis.txt'

Fixed with: generate_metastasis.py

**Comment by ndaniel** [comment]
Indeed that is a bug. Thanks for the report!
The fix is as you suggested or just create an empty file `metastasis.txt` like this `touch metastasis.txt`.
This will be fixed in the next release of FusionCatcher.
