### ISSUE TITLE
Commandline option for limiting coreutils sort

### ISSUE THREAD

**Issue by mmterpstra** [ndaniel/fusioncatcher#16]
The script [fusioncatcher.py](https://github.com/ndaniel/fusioncatcher/blob/master/bin/fusioncatcher.py) does not have an commandline option for limiting the `sort` memory but defaults to 80% of the machine memory. Using job managers (slurm and PBS for example) this might get out of assigned memory or an somewhat ridiculous amount of memory has to be assigned(on 256g node =~ 205g ram). Can you consider changing this? 

In the git repo this happens at [line 1913](https://github.com/ndaniel/fusioncatcher/blob/master/bin/fusioncatcher.py#L1913)

**Comment by ndaniel** [comment]
Good point! This will be added in the next release!

**Comment by mmterpstra** [comment]
Thanks in advance!

**Comment by ndaniel** [comment]
Fixed in v0.99.6a.
