### ISSUE TITLE
Is gencode annotation available?

### ISSUE THREAD

**Issue by yeswzc** [ndaniel/fusioncatcher#165]
Hi,
I want to know if gencode annotation can be used to build the index.
And what is the "necessary data" and what are the format looks like in order to make a gencode index?

Thank you!

**Comment by ndaniel** [comment]
Sorry, but building directly genome index using gencode annotation is not supported.

**Comment by yeswzc** [comment]
> Sorry, but building directly genome index using gencode annotation is not supported.

OK. Thanks!
