### ISSUE TITLE
Minor edit: Update --sort-buffer-size description

### ISSUE THREAD

**Issue by mmterpstra** [ndaniel/fusioncatcher#17]
Hi thanks for including my request!

The commandline usage manual [here](https://github.com/ndaniel/fusioncatcher/blob/master/bin/fusioncatcher.py#L1260) still mentions the 80% memory. 

It might be better to also mention the newly included [limit](https://github.com/ndaniel/fusioncatcher/blob/master/bin/fusioncatcher.py#L1939) using something like `"Default is '%default' capped at 26G."` at [here](https://github.com/ndaniel/fusioncatcher/blob/master/bin/fusioncatcher.py#L1265).

**Comment by ndaniel** [comment]
Good point. The manual and description do not match the reality. I updated the documentation and the description for now.

**Comment by ndaniel** [comment]
Fixed and backported to v0.99.6a.
