### ISSUE TITLE
fusioncatcher biased against intronic fusion events?

### ISSUE THREAD

**Issue by erprateek** [ndaniel/fusioncatcher#174]
Hi Daniel,

I am noticing for a given tumor sample that fusioncatcher gets evidence for 2 splice site events between the same fusion partners (TMPRSS2-ETV4 in this case). However I tested this with two other fusion callers (with the same sample) that there is significant support for an intron-CDS fusion between the same pair of genes, much higher than the splice site event. I looked through the intermediate files produced by fusioncatcher and I did not get any evidence whatsoever about the intronic event. Do you happen to know if this is a known behavior?

**Comment by ndaniel** [comment]
I think that is more likely that FusionCatcher will find fusion events that have fusion junction inside exons or at the borders of exons. For some specific fusion genes that might not be the case like for example for IGH fusions.

I would say that probably the difference compared to other callers and  which are seen here are due most likely different gene annotations being used. Probably the other fusion callers used different gene annotation than FusionCatcher?

**Comment by erprateek** [comment]
I indeed thought the same and tweaked other callers to use the exact same annotation as is coded in our version of FusionCatcher but I arrived at the same set of results.

**Comment by ndaniel** [comment]
FusionCatcher marks with label exon-exon every fusion that it finds that has the fusion junction at exon borders.
