### ISSUE TITLE
failed building database for my organism

### ISSUE THREAD

**Issue by scseekers** [ndaniel/fusioncatcher#176]
Hi 

I am working on the rice genome obtained from the ensemble.
I installed fusioncatcher via conda using the commands described in your readme.

I ran the following command to build the database

`fusioncatcher-build.py -g oryza_sativa -o /raw/trimmomatic/ensemble_genome/os_db`

```bash

Downloading the genome of organism 'oryza_sativa' from Ensembl!
230 Login successful.
FTP Error = 550 Failed to change directory.


ERROR: Workflow execution failed at step 4 while executing:
----------------
   get_genome.py \
   --organism oryza_sativa \
   --server ftp.ensembl.org \
   --output /scratch/Asad/E.Coli-Resistant/multiqc_data/tmp/rice_paper_springer/raw/trimmomatic/ensemble_genome/os_db/
----------------


Executing second time the same step/command in order to capture error messages (i.e. STDERR)...
```
Can't figure out the issue...

**Comment by ruizgo** [comment]
You can download manually
```
https://sourceforge.net/projects/fusioncatcher/files/data/
```

**Comment by ndaniel** [comment]
It looks like here: http://ftp.ensembl.org/pub/current_fasta/ is no organism like Oryza Sativa. This means that it is not supported by FusionCatcher.
