### ISSUE TITLE
fusioncatcher-build downloads unwanted version of mouse reference 

### ISSUE THREAD

**Issue by anoronh4** [ndaniel/fusioncatcher#185]
we are looking to use `fusioncatcher-build` to create a mouse reference genome but we are unable to configure the version, and by default it is downloading GRCm39. However several of our other existing tools use GRCm38 or mm10. Can we not choose which version we want to use? is there any guidance on custom builds for the current version of the software?

**Comment by ndaniel** [comment]
Unfortunately, the current release of FusionCatcher does not support old version mouse genome GRCm37. :-(
