### ISSUE TITLE
Sample names missing in output

### ISSUE THREAD

**Issue by mjafin** [ndaniel/fusioncatcher#2]
Hi Daniel,
Maybe I'm missing something, but I had 5 samples in the input directory and now looking at the output directory I can see a lot of evidence for fusions in the output file, but it doesn't point out which sample they came from.

**Comment by ndaniel** [comment]
Hi Mika,

FusionCatcher takes by default (i.e. fusioncatcher.py script) as input only
one sample at time!

If one wishes to process a batch of samples, then it should use
"fusioncatcher-batch.py". For more see:
http://code.google.com/p/fusioncatcher/wiki/Manual#4.6_-_Batch_mode

Cheers,
Daniel

**Comment by mjafin** [comment]
Thanks Daniel. Any idea what it would have done with the directory then? It clearly did something for 1.5 days

**Comment by ndaniel** [comment]
No idea :-/

**Comment by mjafin** [comment]
Maybe the input data got combined?

**Comment by ndaniel** [comment]
Probably!
