### ISSUE TITLE
Install via conda

### ISSUE THREAD

**Issue by bow** [ndaniel/fusioncatcher#20]
Hi @ndaniel,

I was wondering if there are plans to make FusionCatcher available via Conda (perhaps more appropriately via the [bioconda channel](https://bioconda.github.io/). I think it could also simplify the deployment script a bit since many dependencies can then be installed also via conda.

Thanks for working on the tool and making it public by the way!

**Comment by yhoogstrate** [comment]
This would also help me in adding FusionCatcher into galaxy.

**Comment by yhoogstrate** [comment]
Although FusionCatcher is installing the dependencies itself it's still using those available in `$PATH` by default. I think this is not the ideal behavior as this often results in version mismatches due to tools installed system wide. Even when I explicitly set $PATH to the bowtie installed by fusioncatcher, fusioncatcher uses the one in /usr/bin. If I wouldn't be admin on this machine I could not uninstsall the one in /usr/bin and I wouldn't be able to run fusioncatcher.

**Comment by ndaniel** [comment]
Regarding bioconda, I agree. It is on todo list.

Regarding the $PATH, the things are not that well documented in FusionCatcher's manual. Shortly, the path for the tools used by FusionCatcher are specified in: `fusioncatcher/etc/configuration.cfg` and/or $PATH. `fusioncatcher/etc/configuration.cfg` has priority over $PATH.

@yhoogstrate Does specifying the correct path in `fusioncatcher/etc/configuration.cfg` fix the issue?

**Comment by isuxyang** [comment]
Hi Daniel,

I have the same issue running your test that fusioncatcher dependent path cannot be found. Even in your instruction saying specifying --config=path/to/configuration.cfg, it failed by still using versions of tools already existed in the system, which doesn't seem to use --config at all

**Comment by ndaniel** [comment]
Hi isuxyang,

What exactly is the error message shown?
What tool is not found correctly by FusionCatcher?
Are the paths specified in ..../fusioncatcher/etc/configuration.cfg correct?

Cheers,
Daniel

**Comment by isuxyang** [comment]
hi Daniel

Here's the cmd i used: 
/app/fusioncatcher/test/test.sh

error I got: 
ERROR: Wrong version of BOWTIE found! It should be 'bowtie version 1.1.2'.

sort: open failed: test_fusioncatcher/summary_candidate_fusions.txt: No such file or directory

Also, i tried just manually tested it by obtaining r1 and r2 files and run, 

//App/fusioncatcher/bin/fusioncatcher -d /App/fusioncatcher/data/current/ --input /test/ --output /test-results/ --config=/App/fusioncatcher/etc/configuration.cfg

where in config file, there's a line specifies:

bowtie = /App/fusioncatcher/tools/bowtie

thanks,
Xiao

**Comment by isuxyang** [comment]
Hi Daniel,

After investigation, there's some issues with export on my end. So, no issues remain anymore.
thanks,
Xiao

**Comment by tetianakh** [comment]
Are there any updates on this issue? Can FusionCatcher be installed via bioconda?

**Comment by ndaniel** [comment]
Hi tetianakh,

for now FusionCatcher cannot be installed via bioconda **yet**. Until then one can *automatically* install FusionCatcher (and all its genomic files and tools) using one command line that is:

```
wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python bootstrap.py -t --download
```

**Comment by ndaniel** [comment]
In order to get FusionCatcher on bioconda it needs first to get its dependency [seqtk-fork](https://github.com/ndaniel/seqtk) on bioconda, as shown here: 
https://github.com/bioconda/bioconda-recipes/pull/3980

**Comment by bow** [comment]
Hi @ndaniel,

Sorry to bother you again with this request, but I have to ask again if it is at all still possible to make FusionCatcher work with bioconda?

After going over the discussion in the other threads, I was thinking:

* Is it possible to move the seqtk-fork setup into FusionCatcher's `build.sh` script in conda? I'm not sure yet how open the bioconda maintainers are to this, but this seems like a reasonable tradeoff.

* As for the specific tool versions (STAR, etc), you could specify an exact dependency in the `meta.yml` file so if a user updates one of these tools, either conda refuses or it asks the user to uninstall FusionCatcher first so possible conflicts are prevented.

I really want to use FusionCatcher in my pipeline and make it easy to share my pipeline with other people. I've been getting interesting results on my data. Unfortunately, one of the biggest hindrance I've experienced with this when sharing with my colleagues is the install step: It's just not easy to install FusionCatcher. I've encountered various errors when installing FusionCatcher and running it that just boils down to some system-specific configuration. And sure, Conda won't make these errors completely, but in my experience it has helped a lot in reducing them. I also have to say that even though Docker is an attractive option, it is still not available on a wide range of systems. 

Is there anything at all that I can do to make this work with Bioconda? If you are still open with trying to make this work, I would like to help.

**Comment by ndaniel** [comment]
FusionCatcher is using Bowtie aligner version 1.2.0. Out there are newer version of Bowtie that are 1.2.1 and 1.2.1.1 which have major bugs (see: https://github.com/BenLangmead/bowtie/issues/70 https://github.com/BenLangmead/bowtie/issues/69 https://github.com/BenLangmead/bowtie/issues/66  https://github.com/BenLangmead/bowtie/issues/58 ...) which would make FusionCatcher to miss finding fusion genes. Therefore is highly **NOT** recommended to use Bowtie 1.2.1 and 1.2.1.1 with FusionCatcher! BioConda or Conda do not offer granular support for **only and only** a specific version of a tool which would be needed in this case to avoid the usage of versions 1.2.1 and 1.2.1.1 of Bowtie.
