### ISSUE TITLE
fusioncatcher-build fails for mouse data

### ISSUE THREAD

**Issue by tantrev** [ndaniel/fusioncatcher#23]
Greetings,

fusioncatcher-build seems to fail on step 12 for mouse data:

```
ERROR: Workflow execution failed at step 12 while executing:
----------------
   get_exons_positions.py \
   --organism mus_musculus \
   --server www.ensembl.org \
   --threshold_length 150 \
   --output /mnt/disks/sandbox/fusioncatcher/data/v85/
----------------


Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------
Traceback (most recent call last):
  File "/mnt/disks/sandbox/fusioncatcher/bin/get_exons_positions.py", line 281, in <module>
    data = set([(line[1],line[8],line[7],line[11],line[12]) for line in data])
IndexError: list index out of range
```

The full output may be found [here](http://pastebin.com/raw/xFu684j4).  Any ideas?  Thank you in advance.

**Comment by ndaniel** [comment]
Ok. I will take a look!

What version of FusionCatcher is producing this error? v0.99.6a?

**Comment by tantrev** [comment]
Thank you!  I believe so - I just downloaded (presumably) the latest version using:

`wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python bootstrap.py -t`

**Comment by ndaniel** [comment]
It is challenging to say what version of FusionCatcher has been installed by:

```
wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python bootstrap.py -t
```
because it always installs the latest version available. This means that it installed different versions of FusionCatcher depending on the date when it was run.

One may find out the version of FusionCatcher by running this:
```
/mnt/disks/sandbox/fusioncatcher/bin/fusioncatcher.py --version
```

**Comment by ndaniel** [comment]
Not able to reproduce the issue using the latest version of FusionCatcher, that is v0.99.6a!

It might be that the internet connection to Ensembl server is not that good and it might help to use the US based Ensembl server while building the mouse files (that is for US West coast use for example  `--web=uswest.ensembl.org`, see for more: https://github.com/ndaniel/fusioncatcher/blob/master/doc/manual.md#522---building-yourself-the-organisms-build-data )
