### ISSUE TITLE
padding-fastq.py ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by mmterpstra** [ndaniel/fusioncatcher#24]
error produced with:
```
python $EBROOTFUSIONCATCHER/bin/padding-fastq.py    --input infolder/S2_L001_R1_001.fastq    --output outfolder/S2_L001_R1_001.fastq    --size 151 
Traceback (most recent call last):
  File "padding-fastq.py", line 133, in <module>
    qual = min([min(data[j][:-1]) for j in xrange(len(data)) if (j+i)%4 == 3])
ValueError: min() arg is an empty sequence
```
After a bit of experimenting I found out that changing the buffer size variable solves this problem:

old:
```python
    buffer_size = 10**8
```
new suggested buffer size:  
```python
    buffer_size = 10**7
```

You ask me why: 
I don't know. At least I can tell it is not because of the maximum array length:
```python
>>> import sys
>>> print sys.maxsize
9223372036854775807
```

PS: for me 6/8 runs fail on this with ```buffer_size = 10**8``` and 2/8 runs fail on this with ```buffer_size = 10**7```

**Comment by mmterpstra** [comment]
found the real perpetrator:
change 
`qual = min([min(data[j][:-1]) for j in xrange(len(data)) if (j+i)%4 == 3])`
into
`qual = min([min([data[j][:-1]]) for j in xrange(len(data)) if (j+i)%4 == 3])`

really don't know why it behaves like that though.

**Comment by mmterpstra** [comment]
maybe this happens on reads with length of 1

**Comment by ndaniel** [comment]
Thx for the bug reporting!

It looks like that happens when the read sequence has length zero (or the last read in the FASTQ has the read sequence as 1 and also it does not have a newline character!

Does this work?
```
qual = min([min(data[j].rstrip('\r\n')) for j in xrange(len(data)) if (j+i)%4 == 3])
```

**Comment by ndaniel** [comment]
Probably, this would be the best:

```
            try:
                qual = min([min(data[j][:-1]) for j in xrange(len(data)) if (j+i)%4 == 3 and len(data[j])>1])
            except:
                qual = 'F'
```

**Comment by ndaniel** [comment]
Fixed.

**Comment by mmterpstra** [comment]
Thanks,

Also for your fast reply my solution works as patchwork but your solution is better on the long term.

Also did you know that you can mention issues in commit messages then the commit will show up here.
