### ISSUE TITLE
seqtk dependency

### ISSUE THREAD

**Issue by TomSmithCGAT** [ndaniel/fusioncatcher#3]
Fusioncatcher used seqtk mergepe which is not available with older version of seqtk. This either needs documenting or else adding to the dependency checking.

**Comment by ndaniel** [comment]
Actually, it is specified in FusionCatcher documentation that FusionCatcher depends on [SeqTK version 1.0-r68e-dirty](http://github.com/ndaniel/seqtk).
See:
  * https://code.google.com/p/fusioncatcher/wiki/Manual
  * https://github.com/ndaniel/fusioncatcher/blob/master/DEPENDENCIES

FusionCatcher may be installed using [bootstrap.py](http://sf.net/projects/fusioncatcher/files/bootstrap.py) which will choose the correct seqtk.
