### ISSUE TITLE
fusioncatcher-build.py does not match version of configuration.cfg

### ISSUE THREAD

**Issue by danielgerlach** [ndaniel/fusioncatcher#30]
Hi,

Running fusioncatcher-build to generate data for mouse, prints the following error message:

`ERROR: The version of configuration.cfg file does not match the version of the fusioncatcher-build.py!
Please, fix this!`

The reason behind is that fusioncatcher-build.py runs 0.99.7a beta while the config files states  0.99.7b beta. The code on github looks o.k., probablythe data on sourceforge is outdated (http://sf.net/projects/fusioncatcher/files/bootstrap.py).

Thanks, Daniel

**Comment by ndaniel** [comment]
Hi Daniel,

indeed there was a bug which I just fixed by re-releasing the fusioncatcher v0.99.7b on SF.NET again!

Thanks for reporting it!

Cheers,
Daniel
