### ISSUE TITLE
bootstrap.py as root fails

### ISSUE THREAD

**Issue by Jeltje** [ndaniel/fusioncatcher#35]
I've been running `bootstrap.py` successfully as a regular user on a VM. 

Now I'm trying to install on a docker container (ubuntu), and the program recognizes I'm doing this as root. So instead of 
`Installing Python module 'python-biopython' locally `
I now get 
`Installing Python package 'python-biopython' as root...`

Unfortunately, this part of the code exits with
```
  File "bootstrap.py", line 1308, in <module>
    install = options.install_all or options.install_all_py
  File "bootstrap.py", line 856, in module
    pythonpath = pythonpath
  File "bootstrap.py", line 583, in install_module
    f,r = cmds([['apt-get']], verbose = False, exit = False)
TypeError: 'list' object is not callable
```
I had a quick look and wondered if `cmds` should be replaced with `cmd` in that code block, but a quick try just got me into more trouble.

**Comment by ndaniel** [comment]
Hi!

Thanks for reporting the bug!

It should be fixed now and now there is a new bootstrap.py at https://sourceforge.net/projects/fusioncatcher/files/bootstrap.py

Here is also patch:

**Comment by Jeltje** [comment]
Thanks for the quick action.

It seems we're not quite there yet. Now, this command just hangs:
```
  * Ok! Python module 'NumPy' found at '/usr/local/lib/python2.7/dist-packages/numpy'!
Installing Python package 'python-biopython' as root...
    # apt-get install python-biopython
```
I can see the command when I run `ps -ef`:
```
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 17:08 ?        00:00:00 /bin/bash
root        65     1  0 17:08 ?        00:00:00 SCREEN
root        66    65  0 17:08 pts/0    00:00:00 /bin/sh
root        68    66  2 17:09 pts/0    00:00:02 python bootstrap.py -a -y
root       145    68  1 17:09 pts/0    00:00:01 apt-get install python-biopython
```
But nothing's happening
When I `Ctrl-C` out of this, I get
`  * ERROR: Unable to execute: 'apt-get install python-biopython' (shell = False)!`

I know this is not the most helpful of bug reports, but can you verify that _you_ can run bootstrap.py as root?

**Comment by ndaniel** [comment]
Ok. I modifed the boostrap.py (from sf.net) such that as root now it runs `apt-get --yes install` instead of `apt-get install`. Does this work?

**Comment by Jeltje** [comment]
It does! Thanks again.
