### ISSUE TITLE
Wrong version of BOWTIE found 

### ISSUE THREAD

**Issue by komalsrathi** [ndaniel/fusioncatcher#36]
Hi,

So I install fusioncatcher and the data separately like this:

```
wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O $bin/bootstrap.py
python2.6 $bin/bootstrap.py --install-all --yes -t
bash $bin/fusioncatcher/fusioncatcher_v0.99.7b/bin/download.sh
```

The installation did not throw any errors but when I went to test the installation:

```
/mnt/isilon/cbmi/variome/bin/fusioncatcher/test/test.sh 
```

It gave me test not ok:
```
ERROR: Wrong version of BOWTIE found (/mnt/isilon/cbmi/variome/bin/fusioncatcher/tools/bowtie/bowtie)! It should be 'bowtie-align version 1.2'. One may specify the path to the correct version in 'fusioncatcher/etc/configuration.cfg'.

sort: open failed: test_fusioncatcher/summary_candidate_fusions.txt: No such file or directory
```

The one that is in the `etc/configuration.cfg` file is:

```
$ head configuration.cfg 
[paths]
python = /usr/bin
data = /mnt/isilon/cbmi/variome/bin/fusioncatcher/data/current
scripts = /mnt/isilon/cbmi/variome/bin/fusioncatcher/bin
bowtie = /mnt/isilon/cbmi/variome/bin/fusioncatcher/tools/bowtie
bowtie2 = /mnt/isilon/cbmi/variome/bin/fusioncatcher/tools/bowtie2
```

Here are all the bowtie installations:

```
$ ls /mnt/isilon/cbmi/variome/bin/fusioncatcher/tools/
1.0-r82b         biopython-1.68           bowtie-1.2-linux-x86_64.zip     liftover                  setuptools                       sratoolkit.2.6.2-centos_linux64.tar.gz
1.0-r82b.tar.gz  biopython-1.68.tar.gz    bowtie2                         openpyxl                  setuptools-20.9.0                star
2.5.2b           blat                     bowtie2-2.2.9-linux-x86_64      openpyxl-2.4.0-a1         setuptools-20.9.0.tar.gz         xlrd
2.5.2b.tar.gz    bowtie                   bowtie2-2.2.9-linux-x86_64.zip  openpyxl-2.4.0-a1.tar.gz  sratoolkit                       xlrd-0.9.4
biopython        bowtie-1.2-linux-x86_64  fatotwobit                      seqtk                     sratoolkit.2.6.2-centos_linux64  xlrd-0.9.4.tar.gz

$ ls /mnt/isilon/cbmi/variome/bin/fusioncatcher/tools/bowtie-1.2-linux-x86_64/
AUTHORS                 bowtie-align-s          bowtie-build-l-debug    bowtie-inspect-l        doc/                    MANUAL                  scripts/
bowtie                  bowtie-align-s-debug    bowtie-build-s          bowtie-inspect-l-debug  genomes/                MANUAL.markdown         SeqAn-1.1/
bowtie-align-l          bowtie-build            bowtie-build-s-debug    bowtie-inspect-s        indexes/                NEWS                    TUTORIAL
bowtie-align-l-debug    bowtie-build-l          bowtie-inspect          bowtie-inspect-s-debug  LICENSE                 reads/                  VERSION
```

However, none of the bowtie installations were ok because when I try to print out the version, it throws me this error:

```
$ /mnt/isilon/cbmi/variome/bin/fusioncatcher/tools/bowtie/bowtie -version
bowtie-align: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory

$ /mnt/isilon/cbmi/variome/bin/fusioncatcher/tools/bowtie-1.2-linux-x86_64/bowtie --version
bowtie-align: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory
```

Can you suggest a possible solution for this?

**Comment by ndaniel** [comment]
Hi!

The configuration.cfg file looks good!

If you run manually this in a terminal:
```
/mnt/isilon/cbmi/variome/bin/fusioncatcher/tools/bowtie/bowtie --version
```

what does it show?

**Comment by komalsrathi** [comment]
It is in my question - the bowtie installation wasn't correct:

```
$ /mnt/isilon/cbmi/variome/bin/fusioncatcher/tools/bowtie/bowtie -version
bowtie-align: error while loading shared libraries: libtbb.so.2: cannot open shared object file: No such file or directory
```

**Comment by komalsrathi** [comment]
I don't have sudo rights but I can ask the sys admin to do it. Thanks!

**Comment by komalsrathi** [comment]
I got that installed but now I am getting another library issue - libtbbmalloc_proxy.so.2

**Comment by ndaniel** [comment]
Hi,

that needs

sudo apt-get install libtbb-dev

Cheers,
Daniel

**Comment by ndaniel** [comment]
From https://sourceforge.net/projects/fusioncatcher/files/README.md/download
one has
```
Download / Install / Update FusionCatcher

Use this one-line command:

wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python bootstrap.py -t --download
If one wants to have all the questions asked by boostrap.py answered automatically with yes then add -y to command above. For more see:

bootstrap.py --help
In Ubuntu running this command before installing FusionCatcher would make the installation smoother:

sudo apt-get install wget gawk gcc g++ make cmake curl unzip zip tar gzip pigz build-essential libncurses5-dev zlib1g-dev libtbb-dev libtbb2 python python-dev python-numpy python-biopython python-xlrd python-openpyxl
```

**Comment by komalsrathi** [comment]
Ok I got that working but after fixing that I got another error:

```
$ ./bowtie --version
bowtie-align: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bowtie-align)
```

I am working with the systems engineer here to install these requirements but just want to keep you updated - if at all its helpful.

**Comment by komalsrathi** [comment]
Can I change the .cfg file to point to any currently installed bowtie version?

**Comment by ndaniel** [comment]
Hi,

you may change the .cfg file to point to another installed bowtie installation but that bowtie has to be version 1.2.0.

On the other hand does this solve the issue "`/lib64/libc.so.6:` not found":

```
sudo ln -s /lib/x86_64-linux-gnu/libc-2.15.so /lib/libc.so.6
```

**Comment by komalsrathi** [comment]
I was successfully able to install it - the test is still running (STAR is taking a long time) but I am positive that it was installed ok after loading all the libraries. Thanks!!

**Comment by ndaniel** [comment]
The test should run in approx. 5 to 20 minutes.

**Comment by komalsrathi** [comment]
I am not sure then - because my test ran for like 7 hours and then I had to kill it.

**Comment by ndaniel** [comment]
Hi,

running the test on my laptop (quad-core, 24 GB RAM) takes 7 minutes. Therefore I think that something is going wrong in your case.

Would be possible to get the log of your run, which is the file `/mnt/isilon/cbmi/variome/bin/fusioncatcher/fusioncatcher_v0.99.7b/test/` which contains all the command line executed by FusionCatcher and their execution times?

Cheers,
Daniel

**Comment by ndaniel** [comment]
I looked into this more and now I believe more than this might fix it:

```bash
cp -f \
/mnt/isilon/cbmi/variome/bin/fusioncatcher/fusioncatcher_v0.99.7b/tools/star/bin/Linux_x86_64_static/STAR \
/mnt/isilon/cbmi/variome/bin/fusioncatcher/fusioncatcher_v0.99.7b/tools/star/source/
```

**Comment by komalsrathi** [comment]
So actually I don't have anything under `/mnt/isilon/cbmi/variome/bin/fusioncatcher/fusioncatcher_v0.99.7b/tools/`

**Comment by komalsrathi** [comment]
Awesome! Got it to work in 8 mins and the installation is ok! Thanks for being so prompt in replying.

**Comment by ndaniel** [comment]
Great!
I had a typo in the above fix, where it should have been this:
```
cp -f \
/mnt/isilon/cbmi/variome/bin/fusioncatcher/tools/star/bin/Linux_x86_64_static/STAR \
/mnt/isilon/cbmi/variome/bin/fusioncatcher/tools/star/source/
```

I guess that you figured it out anyway!

Another comment it that the installation of FusionCatcher is a little bit uncommon and I do not know if this is due to some bug in bootstrap.py or is something else. Anyway the installation is uncommon but it works.

**Comment by komalsrathi** [comment]
Yeah I forgot to mention that I figured out the `Linux_x86_64_static` part. Yeah it took a while but it works!
