### ISSUE TITLE
BiopythonWarning: Import of C module failed

### ISSUE THREAD

**Issue by komalsrathi** [ndaniel/fusioncatcher#37]
This is more of a warning than an error but wanted to know if I can do something about it:

This is my command:

```
fusioncatcher.py -p 10 -d $bin/fusioncatcher/data/current --input SKNAS --output SKNAS_out
```

The second warning about Biopython:

```
WARNING: Cannot restart automatically because the previous log file '/mnt/isilon/maris_lab/target_nbl_ngs/rathik/fusion-catcher/SKNAS_out/fusioncatcher.log' cannot be found!
The workflow will be restarted from the beginning with step 1!
/mnt/isilon/cbmi/variome/bin/fusioncatcher/tools/biopython/Bio/pairwise2.py:993: BiopythonWarning: Import of C module failed. Falling back to pure Python implementation. This may be slooow...
  'implementation. This may be slooow...', BiopythonWarning)
```

If its going to be really slow, how can I fix this?

**Comment by komalsrathi** [comment]
Closing this because I realized its not related to fusioncatcher but with Biopython.

**Comment by ndaniel** [comment]
I think that this warning is real BUT FusionCatcher is not using `biopython/Bio/pairwise2.py` even that it imports `Pairwise2.py`. I should remove the python imports of pairwise2 in the future because they are not used anyway....
