### ISSUE TITLE
fusioncatcher_v0.99.7a: version of the data build does not match the version of this pipeline

### ISSUE THREAD

**Issue by igordot** [ndaniel/fusioncatcher#42]
I can't run fusioncatcher_v0.99.7b due to the libtbb issue with Bowtie. Thus, I decided to use fusioncatcher_v0.99.7a. The install finished fine. Then, I ran `test/test.sh` and got a warning:
```
WARNING: This is an OLD version of FusionCatcher! There is a newer
         version available! Please, update to the newest version!
 - Current version:   0.99.7a beta
 - New version:       0.99.7b beta
```
Makes sense, but it kept going.

When it gets to the data directory, it throws an error:
```
....................
ERROR: The version of the data build does not match the version of this pipeline!
Please, run again the 'fusioncatcher-build.py' in order to fix this!
....................
sort: open failed: test_fusioncatcher/summary_candidate_fusions.txt: No such file or directory
```

What version of the data and the pipeline should it be? My data directory is 86 and the pipeline should be 86 as well. Is there any way I can override that?

**Comment by igordot** [comment]
I ended up solving this. It turns out there is a version specified in `data/ensembl_v86/version.txt`. I edit that file and the test worked.

**Comment by ndaniel** [comment]
Ok.
The issue regarding Bowtie and libb in FusionCatcher v0.99.7b can be fixed by installing libtbb and libtbb2, like this:
```
sudo apt-get install libtbb-dev libtbb2
```
If that does not work then compiling bowtie 1.2 from sources (or using the legacy version https://sourceforge.net/projects/bowtie-bio/files/bowtie/1.2.0/bowtie-1.2-linux-legacy-x86_64.zip/download ) should fixed it.

I do not recommend using FusionCatcher v0.99.7a because it has a major bug that is https://github.com/ndaniel/fusioncatcher/issues/32

**Comment by igordot** [comment]
Thanks for alerting me to the bug.

I saw the libtbb fix, but it requires sudo rights, which I do not have. I also tried downloading the compiled legacy version of Bowtie and got a different error with that:
```
bowtie-align: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by bowtie-align)
```

**Comment by ndaniel** [comment]
Ok. You could still use FusionCatcher v0.99.7b with an older version of Bowtie, that is 1.1.2 from here: https://sourceforge.net/projects/bowtie-bio/files/bowtie/1.1.2/bowtie-1.1.2-linux-x86_64.zip

Here are the steps:
- install manually Bowtie 1.1.2 over the Bowtie 1.2 in FusionCatcher's tools folder (that is something like fusioncatcher/tools/bowtie/ )
- edit manually the file fusioncatcher/bin/fusioncatcher.py such that these lines are commented out:
```
    os.system("bowtie --version | head -1 > '%s'" % (outdir('bowtie_version.txt'),))
    last_line = file(outdir('bowtie_version.txt'),'r').readline().lower().rstrip("\r\n")
    correct_version = 'bowtie-align version 1.2'
    if last_line != correct_version:
        job.close()
        os.system("which bowtie > '%s'" % (outdir('bowtie_path.txt'),))
        bowtie_path = file(outdir('bowtie_path.txt'),'r').readline().rstrip("\r\n")
        print >>sys.stderr,("\n\n\nERROR: Wrong version of BOWTIE found ("+bowtie_path+")! It should be '"+correct_version+"'. One may specify the path to the correct version in 'fusioncatcher/etc/configuration.cfg'.\n")
        sys.exit(1)
    os.remove(outdir('bowtie_version.txt'))
```
should be 
```
#    os.system("bowtie --version | head -1 > '%s'" % (outdir('bowtie_version.txt'),))
#    last_line = file(outdir('bowtie_version.txt'),'r').readline().lower().rstrip("\r\n")
#    correct_version = 'bowtie-align version 1.2'
#    if last_line != correct_version:
#        job.close()
#        os.system("which bowtie > '%s'" % (outdir('bowtie_path.txt'),))
#        bowtie_path = file(outdir('bowtie_path.txt'),'r').readline().rstrip("\r\n")
#        print >>sys.stderr,("\n\n\nERROR: Wrong version of BOWTIE found ("+bowtie_path+")! It should be '"+correct_version+"'. One may specify the path to the correct version in 'fusioncatcher/etc/configuration.cfg'.\n")
#        sys.exit(1)
#    os.remove(outdir('bowtie_version.txt'))
```

**Comment by igordot** [comment]
That worked. The test script said everything was fine. Thank you for the suggestion.
