### ISSUE TITLE
FusionCatcher on mouse fails due to cannot find pancreases.txt

### ISSUE THREAD

**Issue by hmgeiger** [ndaniel/fusioncatcher#48]
Was able to (I thought) run fusioncatcher-build successfully for mouse (version v0.99.7b), after manually adjusting the file get_synonyms.py as described in another thread. However, it failed because it was unable to find a file "pancreases.txt" in the data directory. I am trying to run it again after manually creating an empty file with this name in the data directory, but just thought you should know.

Full error:

ERROR: Workflow execution failed at step 246 while executing:
----------------
   label_fusion_genes.py \
   --input fusioncatcher/candidate_fusion-genes_70.txt \
  --label pancreases \
 --filter_genes data_dir/pancreases.txt \
 --output_fusion_genes fusioncatcher/candidate_fusion-genes_1000.txt

----------------
  * Size 'fusioncatcher/candidate_fusion-genes_70.txt' = 267296 bytes
 *Size 'data_dir/pancreases.txt' = 0 bytes
*Size 'fusioncatcher/candidate_fusion-genes_1000.txt' = 0 bytes
Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------
Traceback (most recent call last):
  File "software_dir/label_fusion_genes.py", line 155, in <module>
    no_proteins=set([line.rstrip('\r\n') for line in file(options.input_filter_genes_filename,'r') if line.rstrip('\r\n')])
IOError: [Errno 2] No such file or directory: 'data_dir/pancreases.txt'

**Comment by ndaniel** [comment]
Creating and empty file `data_dir/pancreases.txt` should fix this, e.g.

```
touch data_dir/pancreases.txt
```
