### ISSUE TITLE
FusionCatcher v0.99.4c installs wrong version of STAR

### ISSUE THREAD

**Issue by ndaniel** [ndaniel/fusioncatcher#5]
FusionCatcher v0.99.4c install an incorrect version of STAR. It should installed STAR 2.4.1d instead of STAR 2.4.1c!

**Comment by ndaniel** [comment]
This has been fixed and patches which fix this has been pushed into FusionCatcher v0.99.4c and therefore from now June 26, 2015 FusionCatcher v0.99.4c will install STAR 2.4.1d (thru boostrap.py)!

A workaround in case that the installation of FusionCatcher v0.99.4c was done before this data is to install manually STAR 2.4.1d as following (assuming that fusioncatcher was installed in `/apps` path:

```
cd /apps/fusioncatcher/tools
wget http://github.com/alexdobin/STAR/archive/STAR_2.4.1d.tar.gz -O STAR_2.4.1d.tar.gz
tar zxvf STAR_2.4.1d.tar.gz
cd STAR-STAR_2.4.1d
cd source
rm -f STAR
cp ../bin/Linux_x86_64_static/STAR .
cd ..
ln -s STAR-STAR_2.4.1d star
```

**Comment by tylmoss** [comment]
conda version of fusioncatcher v1.10 also install wrong version of STAR

**Comment by ndaniel** [comment]
That is strange because conda installs as far as I know FusionCatcher v1.00 and not v1.10. Right?
