### ISSUE TITLE
http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64.v287/liftOver does not exist anymore

### ISSUE THREAD

**Issue by pjongeneel** [ndaniel/fusioncatcher#50]
Hey, was just checking the downloader - apparently they took down 
http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64.v287/liftOver

however
http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/liftOver exists.

Can we use this file with fusion catcher? Will this be okay?

**Comment by pjongeneel** [comment]
This is for running the automatic install using bootstrap.py

**Comment by pjongeneel** [comment]
actually - now none of the  http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64.v287 sources exist

**Comment by ndaniel** [comment]
Hi @pjongeneel  !

Thanks for reporting this!

Indeed `http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64.v287/` is not valid URL anymore and now it is changed into `http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/`. This now has been fixed in `bootstrap.py` on sf.net.

Cheers,
Daniel
