### ISSUE TITLE
Failed in the single-end mode

### ISSUE THREAD

**Issue by smw1414** [ndaniel/fusioncatcher#53]
Hi
I was trying to use single-end mode to detect fusion genes. But, the fragment_fastq.py showed the following errors. Here was my command and error messages. How do I fix this error? Thank you.
`fusioncatcher.py -i ./single.fastq.gz -o test --single-end`

Error msg
> Traceback (most recent call last):
  File "/home/wsm/bam/apps/fusioncatcher/fusioncatcher/bin/fragment_fastq.py", line 537, in <module>
    main()
  File "/home/wsm/bam/apps/fusioncatcher/fusioncatcher/bin/fragment_fastq.py", line 532, in main
    options.verbose
  File "/home/wsm/bam/apps/fusioncatcher/fusioncatcher/bin/fragment_fastq.py", line 248, in fragment_fastq
    for bucket in get_reads:
  File "/home/wsm/bam/apps/fusioncatcher/fusioncatcher/bin/fragment_fastq.py", line 141, in reads_from_single_fastq_file
    piece[it] = (line_1,line_2)
UnboundLocalError: local variable 'line_2' referenced before assignment

**Comment by ndaniel** [comment]
Hi,

I would need more info like for example, the length of the reads from the input FASTQ file and also the version of FusionCatcher!

Cheers,
Daniel

**Comment by smw1414** [comment]
Hi Daniel,
I tried the command you suggested, but it was still failed. 
I have upload the single-end fastq to the google driver. 
https://drive.google.com/open?id=0B4E7rQ1He2dcZV96aU90OE1zMTg
This is a ion torrent generated fastq. Some of reads are less than 130 bp, I have used the cutadapt to remove the sequence less than 130 bp. But, it's still not working.

**Comment by ndaniel** [comment]
Hi,

thanks for sharing the problematic FASTQ file. I will take a look and let you know!

Cheers,
Daniel

**Comment by ndaniel** [comment]
Ok. I think that I have a fix for it but it is really complex fix. That means that this fix will be released in the next version of FusionCatcher, that is v0.99.7c, which will be released some time next week.

If you contact me privately, I can share with you the results for the FASTQ file produced by FusionCatcher v0.99.7c.

**Comment by ndaniel** [comment]
This is fixed in v0.99.7c which was just released.
