### ISSUE TITLE
hg19 is unavailable on fusioncatcher-build?

### ISSUE THREAD

**Issue by ddhb** [ndaniel/fusioncatcher#59]
i have some bam files aligned with reference of hg19. but FusionCatcher doesn't provide hg19 database downloading? or What should i do downloading db manually with hg19?

**Comment by ndaniel** [comment]
Hi,

FusionCatcher needs as input the reads and it does the alignment itself on hg38. FusionCatcher uses only hg38 for alignment even that it will output the results also on hg19 coordinates.

Cheers,
Daniel
