### ISSUE TITLE
this error occured repeatedly 

### ISSUE THREAD

**Issue by ddhb** [ndaniel/fusioncatcher#60]
ERROR: Workflow execution failed at step 25 while executing:
----------------
   add_custom_gene.py \
   --organism homo_sapiens \
   --output /home/ddhb/data/
----------------

Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------
Add/change/correct the genes which have errors or are missing from the Ensembl database...
Found version GRCh38 human genome version!
Gene ENSG09000000001 (C19MC) found already in the database!
  * Gene ENSG09000000001 (C19MC), transcript ENST09000000001, exon ENSE09000000001 are already in the database and they will NOT be added again!

Gene ENSG09000000002 (MIR-371-CLUSTER) found already in the database!
  * Gene ENSG09000000002 (MIR-371-CLUSTER), transcript ENST09000000002, exon ENSE09000000002 are already in the database and they will NOT be added again!

Gene ENSG09000000004 (DA750114) found already in the database!
  * Gene ENSG09000000004 (DA750114), transcript ENST09000000004, exon ENSE09000000004 are already in the database and they will NOT be added again!

Gene ENSG00000237955 (AC008746.10) found already in the database!
  * Gene ENSG00000237955 (AC008746.10), transcript ENST09000000005, exon ENSE09000000005 are already in the database and they will NOT be added again!

Gene ENSG00000205755 (CRLF2) found already in the database!
  * Gene ENSG00000205755 (CRLF2), transcript ENST09000000006, exon ENSE09000000006 are already in the database and they will NOT be added again!

Gene ENSG00000205755 (CRLF2) found already in the database!
  * Gene ENSG00000205755 (CRLF2), transcript ENST09000300006, exon ENSE09000300006 are already in the database and they will NOT be added again!

Gene ENSG00000198223 (CSF2RA) found already in the database!
  * Gene ENSG00000198223 (CSF2RA), transcript ENST09000000007, exon ENSE09000000007 are already in the database and they will NOT be added again!

Gene ENSG00000185291 (IL3RA) found already in the database!
  * Gene ENSG00000185291 (IL3RA), transcript ENST09000000008, exon ENSE09000000008 are already in the database and they will NOT be added again!

Gene ENSG09000000009 (IGK_locus_(a)) found already in the database!
  * Gene ENSG09000000009 (IGK_locus_(a)), transcript ENST09000000009, exon ENSE09000000009 are already in the database and they will NOT be added again!

Gene ENSG09000000010 (IGK_locus_(b)) found already in the database!
  * Gene ENSG09000000010 (IGK_locus_(b)), transcript ENSG09000000010, exon ENSE09000000010 are already in the database and they will NOT be added again!

Gene ENSG09000000011 (IGK_locus_(c)) found already in the database!
  * Gene ENSG09000000011 (IGK_locus_(c)), transcript ENST09000000011, exon ENSE09000000011 are already in the database and they will NOT be added again!

Gene ENSG09000000012 (IGK_locus_(d)) found already in the database!
  * Gene ENSG09000000012 (IGK_locus_(d)), transcript ENST09000000012, exon ENSE09000000012 are already in the database and they will NOT be added again!

Gene ENSG09000000009 (IGK_locus_(e)) found already in the database!
  * Gene ENSG09000000009 (IGK_locus_(e)), transcript ENST09000000009, exon ENSE09000000009 are already in the database and they will NOT be added again!

Gene ENSG09000001010 (IGK_locus_(f)) found already in the database!
  * Gene ENSG09000001010 (IGK_locus_(f)), transcript ENSG09000001010, exon ENSE09000001010 are already in the database and they will NOT be added again!

Gene ENSG09000001011 (IGK_locus_(g)) found already in the database!
  * Gene ENSG09000001011 (IGK_locus_(g)), transcript ENST09000001011, exon ENSE09000001011 are already in the database and they will NOT be added again!

Gene ENSG09000001012 (IGK_locus_(h)) found already in the database!
  * Gene ENSG09000001012 (IGK_locus_(h)), transcript ENST09000001012, exon ENSE09000001012 are already in the database and they will NOT be added again!

Gene ENSG09000000013 (IGH_locus_(a)) found already in the database!
  * Gene ENSG09000000013 (IGH_locus_(a)), transcript ENST09000000013, exon ENSE09000000013 are already in the database and they will NOT be added again!

Gene ENSG09000000014 (IGH_locus_(b)) found already in the database!
  * Gene ENSG09000000014 (IGH_locus_(b)), transcript ENST09000000014, exon ENSE09000000014 are already in the database and they will NOT be added again!

Gene ENSG09000000015 (IGH_locus_(c)) found already in the database!
  * Gene ENSG09000000015 (IGH_locus_(c)), transcript ENST09000000015, exon ENSE09000000015 are already in the database and they will NOT be added again!

Gene ENSG09000000016 (IGH_locus_(d)) found already in the database!
  * Gene ENSG09000000016 (IGH_locus_(d)), transcript ENST09000000016, exon ENSE09000000016 are already in the database and they will NOT be added again!

Gene ENSG09000000017 (IGH_locus_(e)) found already in the database!
  * Gene ENSG09000000017 (IGH_locus_(e)), transcript ENST09000000017, exon ENSE09000000017 are already in the database and they will NOT be added again!

Gene ENSG09000000018 (IGH_locus_(f)) found already in the database!
  * Gene ENSG09000000018 (IGH_locus_(f)), transcript ENST09000000018, exon ENSE09000000018 are already in the database and they will NOT be added again!

Gene ENSG09000001013 (IGH_locus_(g)) found already in the database!
  * Gene ENSG09000001013 (IGH_locus_(g)), transcript ENST09000001013, exon ENSE09000001013 are already in the database and they will NOT be added again!

Gene ENSG09000001014 (IGH_locus_(h)) found already in the database!
  * Gene ENSG09000001014 (IGH_locus_(h)), transcript ENST09000001014, exon ENSE09000001014 are already in the database and they will NOT be added again!

Gene ENSG09000001015 (IGH_locus_(i)) found already in the database!
  * Gene ENSG09000001015 (IGH_locus_(i)), transcript ENST09000001015, exon ENSE09000001015 are already in the database and they will NOT be added again!

Gene ENSG09000001016 (IGH_locus_(j)) found already in the database!
  * Gene ENSG09000001016 (IGH_locus_(j)), transcript ENST09000001016, exon ENSE09000001016 are already in the database and they will NOT be added again!

Gene ENSG09000001017 (IGH_locus_(k)) found already in the database!
  * Gene ENSG09000001017 (IGH_locus_(k)), transcript ENST09000001017, exon ENSE09000001017 are already in the database and they will NOT be added again!

Gene ENSG09000001018 (IGH_locus_(l)) found already in the database!
  * Gene ENSG09000001018 (IGH_locus_(l)), transcript ENST09000001018, exon ENSE09000001018 are already in the database and they will NOT be added again!

Gene ENSG09000000020 (CRHR1-IT1_) found already in the database!
  * Gene ENSG09000000020 (CRHR1-IT1_), transcript ENST09000000020, exon ENSE09000000020 are already in the database and they will NOT be added again!

Gene ENSG00000204650 (CRHR1-IT1) found already in the database!
  * Gene ENSG00000204650 (CRHR1-IT1), transcript ENST09000000021, exon ENSE09000000021 are already in the database and they will NOT be added again!

Gene ENSG00000109685 (WHSC1) found already in the database!
  * Gene ENSG00000109685 (WHSC1), transcript ENST09000000030, exon ENSE09000000030 are already in the database and they will NOT be added again!

Gene ENSG00000095209 (TMEM38B) found already in the database!
  * Gene ENSG00000095209 (TMEM38B), transcript ENST09000000031, exon ENSE09000000031 are already in the database and they will NOT be added again!

Gene ENSG00000187266 (EPOR) found already in the database!
  * Gene ENSG00000187266 (EPOR), transcript ENST09000000033, exon ENSE09000000033 are already in the database and they will NOT be added again!

Gene ENSG00000187266 (EPOR) found already in the database!
  * Gene ENSG00000187266 (EPOR), transcript ENST09000000036, exon ENSE09000000036 are already in the database and they will NOT be added again!

Gene ENSG00000187266 (EPOR) found already in the database!
  * Gene ENSG00000187266 (EPOR), transcript ENST09000000036, exon ENSE09000000037 are already in the database and they will NOT be added again!

Gene ENSG00000187266 (EPOR) found already in the database!
  * Gene ENSG00000187266 (EPOR), transcript ENST09000000038, exon ENSE09000000037 are already in the database and they will NOT be added again!

Gene ENSG00000187266 (EPOR) found already in the database!
  * Gene ENSG00000187266 (EPOR), transcript ENST09000000038, exon ENSE09000000038 are already in the database and they will NOT be added again!

Gene ENSG00000187266 (EPOR) found already in the database!
  * Gene ENSG00000187266 (EPOR), transcript ENST09000000038, exon ENSE09000000039 are already in the database and they will NOT be added again!

Gene ENSG00000243944 (RP11-167H9.4) found already in the database!
  * Gene ENSG00000243944 (RP11-167H9.4), transcript ENST09000000050, exon ENSE09000000050 are already in the database and they will NOT be added again!

Gene ENSG00000130558 (OLFM1) found already in the database!
  * Gene ENSG00000130558 (OLFM1), transcript ENST09000000055, exon ENSE09000000055 are already in the database and they will NOT be added again!

Gene ENSG00000182944 (EWSR1) found already in the database!
  * Gene ENSG00000182944 (EWSR1), transcript ENST09000000060, exon ENSE09000000060 are already in the database and they will NOT be added again!

Gene ENSG09000001070 (TRA_locus_(a)) found already in the database!
  * Gene ENSG09000001070 (TRA_locus_(a)), transcript ENST09000001070, exon ENSE09000001070 are already in the database and they will NOT be added again!

Gene ENSG09000001071 (TRA_locus_(b)) found already in the database!
  * Gene ENSG09000001071 (TRA_locus_(b)), transcript ENST09000001071, exon ENSE09000001071 are already in the database and they will NOT be added again!

Gene ENSG09000001072 (TRA_locus_(c)) found already in the database!
  * Gene ENSG09000001072 (TRA_locus_(c)), transcript ENST09000001072, exon ENSE09000001072 are already in the database and they will NOT be added again!

Gene ENSG09000001073 (TRA_locus_(d)) found already in the database!
  * Gene ENSG09000001073 (TRA_locus_(d)), transcript ENST09000001073, exon ENSE09000001073 are already in the database and they will NOT be added again!

Gene ENSG09000001075 (TRB_locus_(a)) found already in the database!
  * Gene ENSG09000001075 (TRB_locus_(a)), transcript ENST09000001075, exon ENSE09000001075 are already in the database and they will NOT be added again!

Gene ENSG09000001076 (TRB_locus_(b)) found already in the database!
  * Gene ENSG09000001076 (TRB_locus_(b)), transcript ENST09000001076, exon ENSE09000001076 are already in the database and they will NOT be added again!

Gene ENSG09000001077 (TRG_locus_(a)) found already in the database!
  * Gene ENSG09000001077 (TRG_locus_(a)), transcript ENST09000001077, exon ENSE09000001077 are already in the database and they will NOT be added again!

Gene ENSG09000001078 (TRG_locus_(b)) found already in the database!
  * Gene ENSG09000001078 (TRG_locus_(b)), transcript ENST09000001078, exon ENSE09000001078 are already in the database and they will NOT be added again!

Gene ENSG09000001014 (IGH_locus_(h)) found already in the database!
  * Gene ENSG09000001014 (IGH_locus_(h)), transcript ENST09000001100, exon ENSE09000001101 are already in the database and they will NOT be added again!

Gene ENSG09000001014 (IGH_locus_(h)) found already in the database!
  * Gene ENSG09000001014 (IGH_locus_(h)), transcript ENST09000001100, exon ENSE09000001100 are already in the database and they will NOT be added again!

Gene ENSG09000000014 (IGH_locus_(b)) found already in the database!
  * Gene ENSG09000000014 (IGH_locus_(b)), transcript ENST09000001200, exon ENSE09000001200 are already in the database and they will NOT be added again!

Gene ENSG09000000014 (IGH_locus_(b)) found already in the database!
  * Gene ENSG09000000014 (IGH_locus_(b)), transcript ENST09000001200, exon ENSE09000001201 are already in the database and they will NOT be added again!

Gene ENSG09000000014 (IGH_locus_(b)) found already in the database!
  * Gene ENSG09000000014 (IGH_locus_(b)), transcript ENST09000001202, exon ENSE09000001202 are already in the database and they will NOT be added again!

Gene ENSG09000000014 (IGH_locus_(b)) found already in the database!
  * Gene ENSG09000000014 (IGH_locus_(b)), transcript ENST09000001202, exon ENSE09000001203 are already in the database and they will NOT be added again!

Gene ENSG09000000014 (IGH_locus_(b)) found already in the database!
  * Gene ENSG09000000014 (IGH_locus_(b)), transcript ENST09000001202, exon ENSE09000001204 are already in the database and they will NOT be added again!

Gene ENSG09000000014 (IGH_locus_(b)) found already in the database!
  * Gene ENSG09000000014 (IGH_locus_(b)), transcript ENST09000001202, exon ENSE09000001205 are already in the database and they will NOT be added again!

Gene ENSG00000143365 (RORC) found already in the database!
  * Gene ENSG00000143365 (RORC), transcript ENST09000001210, exon ENSE09000001210 are already in the database and they will NOT be added again!

Gene ENSG00000171094 (ALK) found already in the database!
  * Gene ENSG00000171094 (ALK), transcript ENST09000001250, exon ENSE09000001250 are already in the database and they will NOT be added again!

Gene ENSG00000181163 (NPM1) found already in the database!
  * Gene ENSG00000181163 (NPM1), transcript ENST09000001251, exon ENSE09000001251 are already in the database and they will NOT be added again!

Gene ENSG00000077782 (FGFR1) found already in the database!
  * Gene ENSG00000077782 (FGFR1), transcript ENST09000001252, exon ENSE09000001252 are already in the database and they will NOT be added again!

Gene ENSG00000066468 (FGFR2) found already in the database!
  * Gene ENSG00000066468 (FGFR2), transcript ENST09000001253, exon ENSE09000001253 are already in the database and they will NOT be added again!

Gene ENSG00000068078 (FGFR3) found already in the database!
  * Gene ENSG00000068078 (FGFR3), transcript ENST09000001254, exon ENSE09000001254 are already in the database and they will NOT be added again!

Gene ENSG00000160867 (FGFR4) found already in the database!
  * Gene ENSG00000160867 (FGFR4), transcript ENST09000001255, exon ENSE09000001255 are already in the database and they will NOT be added again!

Gene ENSG00000165731 (RET) found already in the database!
  * Gene ENSG00000165731 (RET), transcript ENST09000001256, exon ENSE09000001256 are already in the database and they will NOT be added again!

Gene ENSG00000136997 (MYC) found already in the database!
  * Gene ENSG00000136997 (MYC), transcript ENST09000001257, exon ENSE09000001257 are already in the database and they will NOT be added again!

Gene ENSG00000143924 (EML4) found already in the database!
  * Gene ENSG00000143924 (EML4), transcript ENST09000001258, exon ENSE09000001258 are already in the database and they will NOT be added again!

Gene ENSG00000172175 (MALT1) found already in the database!
  * Gene ENSG00000172175 (MALT1), transcript ENST09000001260, exon ENSE09000001260 are already in the database and they will NOT be added again!

Gene ENSG00000119508 (NR4A3) found already in the database!
  * Gene ENSG00000119508 (NR4A3), transcript ENST09000001261, exon ENSE09000001261 are already in the database and they will NOT be added again!

Gene ENSG00000270647 (TAF15) found already in the database!
  * Gene ENSG00000270647 (TAF15), transcript ENST09000001262, exon ENSE09000001262 are already in the database and they will NOT be added again!

Gene ENSG00000130876 (SLC7A10) found already in the database!
  * Gene ENSG00000130876 (SLC7A10), transcript ENST09000001263, exon ENSE09000001263 are already in the database and they will NOT be added again!

Gene ENSG00000255248 (MIR100HG) found already in the database!
  * Gene ENSG00000255248 (MIR100HG), transcript ENST09000001264, exon ENSE09000001264 are already in the database and they will NOT be added again!

Gene ENSG09000000014 (IGH_locus_(b)) found already in the database!
  * Gene ENSG09000000014 (IGH_locus_(b)), transcript ENST09000001300, exon ENSE09000001300 are already in the database and they will NOT be added again!

Gene ENSG09000000014 (IGH_locus_(b)) found already in the database!
  * Gene ENSG09000000014 (IGH_locus_(b)), transcript ENST09000001300, exon ENSE09000001301 are already in the database and they will NOT be added again!

Gene ENSG09000000014 (IGH_locus_(b)) found already in the database!
  * Gene ENSG09000000014 (IGH_locus_(b)), transcript ENST09000001300, exon ENSE09000001302 are already in the database and they will NOT be added again!

Gene ENSG09000000014 (IGH_locus_(b)) found already in the database!
  * Gene ENSG09000000014 (IGH_locus_(b)), transcript ENST09000001300, exon ENSE09000001304 are already in the database and they will NOT be added again!

Gene ENSG09000001014 (IGH_locus_(h)) found already in the database!
  * Gene ENSG09000001014 (IGH_locus_(h)), transcript ENST09000001400, exon ENSE09000001403 are already in the database and they will NOT be added again!

Gene ENSG09000001014 (IGH_locus_(h)) found already in the database!
  * Gene ENSG09000001014 (IGH_locus_(h)), transcript ENST09000001400, exon ENSE09000001402 are already in the database and they will NOT be added again!

Gene ENSG09000001014 (IGH_locus_(h)) found already in the database!
  * Gene ENSG09000001014 (IGH_locus_(h)), transcript ENST09000001400, exon ENSE09000001401 are already in the database and they will NOT be added again!

Gene ENSG09000001014 (IGH_locus_(h)) found already in the database!
  * Gene ENSG09000001014 (IGH_locus_(h)), transcript ENST09000001400, exon ENSE09000001400 are already in the database and they will NOT be added again!

WARNING: First execution ended with error but second execution did not! Therefore cannot capture the STDERR!
################################################################################
################################################################################
TOTAL RUNNING TIME: 0 day(s), 0 hour(s), 4 minute(s), and 3 second(s) 
################################################################################
################################################################################

------------------------------------------------------

what should i do?

Thank you in advance.

**Comment by ndaniel** [comment]
It looks like you are building the files for needed by FusionCatcher for human from scratch.

Those files for human can be downloaded from https://sourceforge.net/projects/fusioncatcher/files/data/
