### ISSUE TITLE
coordinate of C19MC

### ISSUE THREAD

**Issue by xflicsu** [ndaniel/fusioncatcher#65]
Where and how to get the coordinate of C19MC?

**Comment by ndaniel** [comment]
For more info regarding C19MC see https://en.wikipedia.org/wiki/C19MC_miRNA_cluster and https://jbiomedsci.biomedcentral.com/articles/10.1186/s12929-017-0326-z .

For hg38, C19MC is on chromosome 19, forward strand, start position 53 641 443 and end position 53 7 80 750.
