### ISSUE TITLE
Exclusion of false positives/fusions present in healthy tissue

### ISSUE THREAD

**Issue by egtrgrtbsbrhr** [ndaniel/fusioncatcher#68]
The manual states: "FusionCatcher by default is focusing on finding fusion genes specific to diseased/tumor/cancer samples. That means that FusionCatcher will skip the fusion genes which are already known to exist in healthy samples. If one wishes to find fusion genes in healthy samples then we suggest other fusion finders to be used."

However the output file contains several detected fusions that have categories in column "Fusion_ description" that include fusion genes previously detected in healthy tissue (e.g "conjoing").

Is there any good way to get around this?
Thanks,
J

**Comment by ndaniel** [comment]
@egtrgrtbsbrhr 

Indeed your observation is correct. We run FusionCatcher on a very extensive RNA-seq dataset of healthy samples (like for exempla BodyMap2) for which we have very high confidence that they are healthy samples from healthy people.  

Out there are many articles where the authors have found that a given fusion genes has been found in some cancer samples, like for example TTY15-USP9Y, SLC45A3-ELK4, MSMB-NCOA4, whilst later these fusions have been shown over and over that they actually show up in normal/healhty samples. Therefore one has a new class of fusions which their status is not very clearly defined, such that they are reported in published articles to be found simultaneously in healthy and cancer samples. FusionCatcher is **focusing** on finding fusion genes in cancer samples and not to dispute directly those articles which do not agree with each other regarding the type of a fusion. Therefore FusionCatcher will report also such fusions which have been found in healthy samples but also in cancer samples and FusionCatcher will mark this **fuzzy** fusions by labeling with labels which are contradictory (like for example: "heatlhy" and "known fusion") and let the user/biologist/medical-doctor decide what type of fusion is that. So, I guess that in your case there should be also some other (cancer related) label than just the label "conjoing".
