### ISSUE TITLE
Visualization tools

### ISSUE THREAD

**Issue by komalsrathi** [ndaniel/fusioncatcher#70]
Hi Daniel,

I have been using IGV to visualize fusions until now. But looking for any R packages/tools that I can use to visualize fusioncatcher output. Do you have any suggestions? 

Thanks
Komal

**Comment by ndaniel** [comment]
Hi,

from what I can see R packages, like [chimera](https://bioconductor.org/packages/release/bioc/html/chimera.html) and [chimeraviz](https://bioconductor.org/packages/release/bioc/html/chimeraviz.html) can be used for visualization of candidate fusion genes found by FusionCatcher.

Cheers,
Daniel
