### ISSUE TITLE
ERROR: Workflow execution failed at step 89 while executing: 

### ISSUE THREAD

**Issue by evcon131** [ndaniel/fusioncatcher#71]
I ran fusioncatcher successfully on some files before, but now with new files I keep getting this error when running fusioncatcher. 

```
ERROR: Workflow execution failed at step 89 while executing:
----------------
   sra2illumina.py \
   --input_1 /n/scratch2/eac34/comb_out/init-clear-noadapt-0_PTL1_BOX_1.fq \
   --input_2 /n/scratch2/eac34/comb_out/init-clear-noadapt-1_PTL1_BOX_2.fq \
   --output_1 /n/scratch2/eac34/comb_out/init-sra-clear-noadapt-0_PTL1_BOX_1.fq \
   --output_2 /n/scratch2/eac34/comb_out/init-sra-clear-noadapt-1_PTL1_BOX_2.fq \
   --link hard \
   --tmp_dir /n/scratch2/eac34/comb_out/tmp/
----------------
  * Size '/n/scratch2/eac34/comb_out/init-clear-noadapt-0_PTL1_BOX_1.fq' = 19824577096 bytes
  * Size '/n/scratch2/eac34/comb_out/init-clear-noadapt-1_PTL1_BOX_2.fq' = 19818857164 bytes
  * Size '/n/scratch2/eac34/comb_out/init-sra-clear-noadapt-0_PTL1_BOX_1.fq' = 0 bytes
  * Size '/n/scratch2/eac34/comb_out/init-sra-clear-noadapt-1_PTL1_BOX_2.fq' = 0 bytes


Executing second time the same step/command in order to capture error messages (i.e. STDERR)...

-------------------------------------------
Traceback (most recent call last):
  File "/home/eac34/fusioncatcher/bin/sra2illumina.py", line 48, in <module>
    import phred
  File "/home/eac34/fusioncatcher/bin/phred.py", line 58, in <module>
    import Bio.SeqIO
ImportError: No module named Bio.SeqIO
```
`When I go into python and load SeqIO it doesn't show any issues: 
```
Python 2.7.6 (default, Aug  3 2015, 17:43:52) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Bio.SeqIO
>>> 
```
I really can't figure out where the error is coming from.

**Comment by ndaniel** [comment]
It looks like the Python used by FusionCatcher's scripts (for example see the shebang of the Python's scripts of FusionCatcher or look into the `/n/scratch2/eac34/comb_out/info.txt` file at *Python section*) does not have installed [BioPython](http://biopython.org/) and that there are two different versions of Python installed in your case. The second Python, which you launch manually does have the [BioPython](http://biopython.org/).

**Comment by evcon131** [comment]
Ah ok makes sense. You were correct it was calling python 2.6 by default. I changed all the shebangs in the bin folder to my 2.7 installation and it started right up again. Thank you so much! This program is great!

**Comment by evcon131** [comment]
Actually one of my sets of files started up fine, but the other one had the same issue again. I launched them both with the same environment and the shebangs are all directing towards python2.7

**Comment by ndaniel** [comment]
I guess that probably some Python scripts of FusionCatcher still have the old shebang (and that these scripts are not executed for your first sets of files due to some IFs).

**Comment by evcon131** [comment]
Ok thanks I'll see if I can get these problematic ones to start over, and ask the system admins if there are any modifications they'd recommend to ensure I get the right oython.

**Comment by ndaniel** [comment]
One may change the shebang for the Python scripts of FusionCatcher by using `fusioncatcher/bin/shebang.py` that comes with FusionCatcher.

**Comment by evcon131** [comment]
I reinstalled it with the correct oython in my path, that seems to have done the trick.
