### ISSUE TITLE
fusioncatcher.py: error: ERROR: Argument '--data' needs to be specified as command line (or in 'configuration.cfg' file)!

### ISSUE THREAD

**Issue by wengqi123** [ndaniel/fusioncatcher#72]
use fusioncatcher.py ;
####my txt:
ERR188044_chrX_1.fastq.gz,ERR188044_chrX_2.fastq.gz     con
ERR188245_chrX_1.fastq.gz,ERR188245_chrX_2.fastq.gz     noc
####my commond:
fusioncatcher/bin/fusioncatcher-batch.py -i fusion.txt -o fusion_result
####and error
fusioncatcher.py: error: ERROR: Argument '--data' needs to be specified as command line (or in 'configuration.cfg' file)!

**Comment by ndaniel** [comment]
Hi @wengqi123 

did FusionCatcher install successfully? You could test if the installation is ok by running this:
`fusioncatcher/test/test.sh`

Cheers,
Daniel

**Comment by wengqi123** [comment]
i use Automatic installation,and it install  picard  failed;
####error * ERROR: Unable to execute: 'wget http://github.com/broadinstitute/picard/releases/download/2.9.4/picard.jar -O /haplox/users/wenger/pipe/RNA/bin/fusioncatcher/tools/picard/picard.jar --no-check-certificate' (shell = False)!
--2017-11-07 17:04:26--  http://github.com/broadinstitute/picard/releases/download/2.9.4/picard.jar  

###how can I disable install picard?

**Comment by wengqi123** [comment]
$ fusioncatcher ./test/test.sh 
Checking Python version...
  * Compatible Python version found!
Checking size of installed RAM memory ...
  * 515886 MB of RAM memory found!
Usage: fusioncatcher.py [options]

fusioncatcher.py: error: ERROR: Argument '--data' needs to be specified as command line (or in 'configuration.cfg' file)!
./test/test.sh: line 16: test_fusioncatcher/summary_candidate_fusions_a.txt: No such file or directory
./test/test.sh: line 17: test_fusioncatcher/summary_candidate_fusions_b.txt: No such file or directory
sort: cannot read: test_fusioncatcher/summary_candidate_fusions.txt: No such file or directory
diff: test_fusioncatcher/summary_candidate_fusions_a.txt: No such file or directory
diff: test_fusioncatcher/summary_candidate_fusions_b.txt: No such file or directory

**Comment by ndaniel** [comment]
FusionCatcher was not installed properly.

Does this work?
`wget http://github.com/broadinstitute/picard/releases/download/2.9.4/picard.jar`

**Comment by wengqi123** [comment]
it works, so,why the Automatic installation picard failed?

**Comment by ndaniel** [comment]
Try again to install FusionCatcher using the bootstrap.py (but before erase the previous aborted installation). Does that work?

**Comment by ndaniel** [comment]
Try again to install FusionCatcher using the bootstrap.py (but before erase
the previous aborted installation). Does that work?

Cheers,
Daniel

**Comment by wengqi123** [comment]
=== Installed successfully! ===  this mean install success? 
i use : python bootstrap.py --download -y --build
####but other error:The build data not found in '/fusioncatcher/data/current/' 
i think file exits:
commad:   ls /fusioncatcher/data/current/ #files 
chromosomes_lengths.txt  fusioncatcher-build.log  genome.fa  genome_information.txt  mt.fa  organism.gtf  organism.txt  version.txt  

####and the build log file show error : 
ERROR: Workflow execution failed at step 7 while executing:
----------------
   get_viruses.py \
   --server ftp.ncbi.nlm.nih.gov \
   --output /haplox/users/wenger/pipe/chrX_data/fusion_index/


how to deal with it?

**Comment by wengqi123** [comment]
=== Installed successfully! === this mean install success?
i use : python bootstrap.py --download -y --build
####but other error:The build data not found in '/fusioncatcher/data/current/'
i think file exits:
commad: ls /fusioncatcher/data/current/ #files
chromosomes_lengths.txt fusioncatcher-build.log genome.fa genome_information.txt mt.fa organism.gtf organism.txt version.txt

####and the build log file show error :
ERROR: Workflow execution failed at step 7 while executing:
----------------
   get_viruses.py \
   --server ftp.ncbi.nlm.nih.gov \
   --output /haplox/users/wenger/pipe/RNA/bin/fusioncatcher/data/v90/
----------------
how to deal with it?

**Comment by wengqi123** [comment]
single command :./bin/get_viruses.py --server ftp.ncbi.nlm.nih.gov --output /haplox/users/wenger/pipe/RNA/bin/fusioncatcher/data/v90/
Downloading the viral genomes from NCBI server!
230 Anonymous access granted, restrictions apply
ERROR: File not 'all.fna.tar.gz' found!

**Comment by ndaniel** [comment]
> i use : python bootstrap.py --download -y --build

This is not correct. The `--build` should not be there!

This is the correct command for installing FusionCatcher in your case:

`python bootstrap.py -t -y --download`

**Comment by wengqi123** [comment]
thanks! it works well ! but how much memory it need ,because it run error # out of  memory

**Comment by wengqi123** [comment]
it's all well now,thanks again for your help!

**Comment by ndaniel** [comment]
it needs around 32 gb ram in some cases even 64 gb ram.
