### ISSUE TITLE
BBMap causes fusioncatcher failure

### ISSUE THREAD

**Issue by ferenju1** [ndaniel/fusioncatcher#74]
Hi,

I've installed fusioncatcher on DNANexus using this command:

get http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python bootstrap.py -t --download -y

I'm trying to run the latest version, 1.0.0.

When I try to run an analysis, it fails due to the BBMap checking step - the error text is below.

When I debug the BBMap version check call, I see it is returning an error code, which is why the command is crashing out.

I will try to patch the script to get it running, but as I've just used the default installation throughout I suspect this will happen to others. I'll put a note on the BBMap page too, I think it is principally a problem with their tool...

Thanks,

John.

````
BBMAP:
------
"  \
>> /home/dnanexus/fc/0/info.txt
--------------------------------------------------------------------------------
+-->EXECUTING...
--------------------------------------------------------------------------------
==> Execution time: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s)
////////////////////////////////////////////////////////////////////////////////
  Running: step = 20   Time: 07:57   Date: 2017-12-12 (elapsed time: 0d:0h:0m)
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
==> Current working directory: '/home/dnanexus/fc'
bbmap.sh \
--version  \
2>> /home/dnanexus/fc/0/info.txt
--------------------------------------------------------------------------------
+-->EXECUTING...
ERROR: Workflow execution failed at step 20 while executing:
----------------
   bbmap.sh \
   --version  \
   2>> /home/dnanexus/fc/0/info.txt
----------------
Please, check if 'BBMAP' (from <https://sourceforge.net/projects/bbmap>) is installed and it is in the corresponding PATH!
  * Size '/home/dnanexus/fc/0/info.txt' = 2144 bytes
Executing second time the same step/command in order to capture error messages (i.e. STDERR)...
-------------------------------------------
java -Djava.library.path=/opt/fusioncatcher/tools/bbmap/jni/ -ea -Xmx10819m -cp /opt/fusioncatcher/tools/bbmap/current/ align2.BBMap build=1 overwrite=true fastareadlen=500 --version
BBMap version 37.73
For help, please run the shellscript with no parameters, or look in /docs/.
################################################################################
################################################################################
TOTAL RUNNING TIME: 0 day(s), 0 hour(s), 0 minute(s), and 0 second(s) 
################################################################################
################################################################################
Error while running fusioncatcher-batch.py!
```

**Comment by ferenju1** [comment]
I checked the BBMap versions, 37.68 definitely returns 0 code on version, but 37.73 onwards return 1. I didn't check the versions in between those two.

**Comment by ndaniel** [comment]
Thanks for reporting this bug!

Fixed on SF.NET and also on GitHub https://github.com/ndaniel/fusioncatcher/commit/a308c4d98a38e3f40920e93780ca5feb60d13faa . 

Reinstalling FusionCatcher from scratch might help. In your case overwriting BBMAP with an older version (like for example 37.68), by doing something like this:
```
cd /opt/fusioncatcher/tools/
wget https://sourceforge.net/projects/bbmap/files/BBMap_37.68.tar.gz
tar zxvf BBMap_37.68.tar.gz
```
should fix the issue.

**Comment by ndaniel** [comment]
I am going to assume that this is no longer an issue. Feel free to reopen the issue if you feel otherwise.
