### ISSUE TITLE
Too many unaligned reads in newest fusioncatcher version

### ISSUE THREAD

**Issue by dwooi** [ndaniel/fusioncatcher#75]
Hi 

I am using fusioncatcher 0.99.7d and when I run it on one of my fastq files there seems to be too many unaligned reads. However when I run it with an older version of fusioncatcher (0.99.6a) it seems to align fine. I know the fastq file is fine because other fusion tools are fine with it so I don't know what the problem is. I have attached the info.txt files here. 
[info 0.99.6a.txt](https://github.com/ndaniel/fusioncatcher/files/1557476/info.0.99.6a.txt)
[info 0.99.7d.txt](https://github.com/ndaniel/fusioncatcher/files/1557481/info.0.99.7d.txt)

**Comment by ndaniel** [comment]
Hi @dwooi 

Actually the newest version of FusionCatcher is 1.00 and not 0.99.7d.

I looked to the both attached files and it looks to me that rate of unaligned reads (that is 100%) is the same in both versions. I aligned manually some reads in UCSC Browser and it looks like the the reads contain some kind of index/barcode sequence (e.g. the first 13bp or first 20bp), as shown below
```
   ACTIONS      QUERY           SCORE START  END QSIZE IDENTITY CHRO STRAND  START    END      SPAN
---------------------------------------------------------------------------------------------------
browser details 1                112    13   125   125 100.0%     7   +   94429391  94430319    929
browser details 2                 88    11    99   125 100.0%     2   -  237377308 237378687   1380
browser details 3                117     9   125   125 100.0%     7   -   94430265  94430381    117
browser details 4                113    13   125   125 100.0%     2   +  237377234 237377346    113
browser details 5                117     5   125   125  97.5%     3   +  188877839 188877958    120
browser details 6                113    13   125   125 100.0%    17   -   50184192  50184304    113
browser details 7                113    13   125   125 100.0%     3   -  188877878 188877990    113
browser details 8                109    13   125   125 100.0%    17   +   50184105  50184217    113
```
If that is the case then probably the reads should be trimmed (such that that index sequene is removed) and only afterwards given as input to FusionCatcher.

**Comment by dwooi** [comment]
Thanks so much. Trimming the files worked. I am still new to this but in the future how can I check how much of the fastq files I need to trim before putting it through fusioncatcher?

**Comment by ndaniel** [comment]
Thanks for the feedback! 

I guess that it would help a lot and saved a lot of time for you if the person/organization who has provided you with the FASTQ files would have let you know about the bardcodes sequences embedded in the reads sequences beforehand.
