### ISSUE TITLE
 No such file or directory: 'organism.txt'

### ISSUE THREAD

**Issue by ranijames** [ndaniel/fusioncatcher#78]
Dear All,
I am using fusioncatcher to find fusion genes. I followed direct download of bulid genome data as following,
```
mkdir -p /some/human/data/
cd /some/human/data/
wget http://sourceforge.net/projects/fusioncatcher/files/data/human_v90.tar.gz.aa
wget http://sourceforge.net/projects/fusioncatcher/files/data/human_v90.tar.gz.ab
wget http://sourceforge.net/projects/fusioncatcher/files/data/human_v90.tar.gz.ac
wget http://sourceforge.net/projects/fusioncatcher/files/data/human_v90.tar.gz.ad
cat human_v90.tar.gz.* | tar xz
ln -s human_v90 current
```
And now when i try to run fusioncatcher using the command line,it throws following error,
```
 organism = file(datadir("organism.txt"),"r").readline().rstrip('\r\n').lower()
IOError: [Errno 2] No such file or directory: '/data/human_v90/organism.txt'
```
There is no `organism.txt` file in the folder human_v90, but It is not extracted from the downloaded file as well. I am wondering what is supposed to be in that file, I would like to create one manually or any suggestions would be great

**Comment by ndaniel** [comment]
@ranijames 

In the above example it looks like the path is not correct because it starts with `/some/human/data` which later unfortunately becomes `/data/human_v90/`. 

I checked few minutes ago and the file `organism.txt` can be found in `human_v90.tar.gz.a*` files.

It might be that also the  files `human_v90.tar.gz.a*` are corrupted, and in this case they should be downloaded again.

Also FusionCatcher can be insalled using this command line:
```
wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python bootstrap.py -t --download
```

**Comment by ranijames** [comment]
Thanks for the reply, I have downloaded all files again and still it complaints the same.

I had following error while unzipping tar files

```
gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```
The script used is same as mentioned in user manual,
` cat human_v90.tar.gz.* | tar xz
`

**Comment by ndaniel** [comment]
It looks like the files need to be downloaded again because the ones which are already downloaded got corrupted during the download.

**Comment by ranijames** [comment]
Ok, now I see there is a problem with the download I tried it a couple times and gave up. Again I tried following the mannuel using fusioncatcher-bulid as following,

`python fusioncatcher-build.py  -g homo_sapiens -o /home/user/projects/Kiel/ENSEMBLE
But it throws following error,

````
sh: 1: python_version.py: not found


ERROR: Workflow execution failed at step 1 while executing:
----------------
   python_version.py
----------------
Please, check if 'Python' (from <http://python.org/>) is installed (or if 'configuration.cfg' file is set up correctly)!
```
It would be great if you could tell me what is the issue or where is the isse

**Comment by ndaniel** [comment]
@ranijames 

> Ok, now I see there is a problem with the download I tried it a couple times and gave up. 

I guess trying again and again until the transfer is successful would be the easiest choice here.

> python fusioncatcher-build.py -g homo_sapiens -o /home/user/projects/Kiel/ENSEMBLE

This should be:
`fusioncatcher-build.py -g homo_sapiens -o /home/user/projects/Kiel/ENSEMBLE`

Also, this would likely work even less well because it also needs internet connection. This is why I think that downloading file human_v90.tar.gz.a* is the easiest choice here.

**Comment by ranijames** [comment]
The issue is on machine default python version is python 3 and if I try it like you mentioned using the following command,
fusioncatcher-build.py -g homo_sapiens -o /home/user/projects/Kiel/ENSEMBLE

It then complains the syntax issue as following,

```
 File "./fusioncatcher-build.py", line 331
    print "EXAMPLE:"
                   ^
SyntaxError: Missing parentheses in call to 'print'
```
Ok, I would try downloading but its taking 5-7 hours

**Comment by ndaniel** [comment]
> The issue is on machine default python version is python 3 and if I try it like you mentioned using the following command,

That looks like FusionCatcher was not installed properly. If the Python 2.X is something like this `/usr/bin/python2` then FusionCatcher should be installed like this `/usr/bin/python2 bootstrap.py` (or like this: https://github.com/ndaniel/fusioncatcher/blob/master/doc/manual.md#42---manual-installation-manual-installation ).

> Ok, I would try downloading but its taking 5-7 hours

That is ok!

**Comment by ranijames** [comment]
I downloaded the compiled version from here,
`https://sourceforge.net/projects/fusioncatcher/files/`

**Comment by ndaniel** [comment]
@ranijames 

That is not sufficient. It needs to be installed properly also! Installing properly FusionCatcher can be done using one liner command line:
```
wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python2 bootstrap.py -t --download
```
