### ISSUE TITLE
python path change in all scripts

### ISSUE THREAD

**Issue by komalsrathi** [ndaniel/fusioncatcher#80]
Hi,

I had successfully installed Fusioncatcher before with /usr/bin/python2.6 so all python scripts have this path. But now the path on our cluster has changed to /usr/bin/python2.7 and I have to go and change each script to reflect that change. Is there a quick way to change this path in all the python scripts of fusioncatcher?

**Comment by ndaniel** [comment]
This is documented in the [manual](https://github.com/ndaniel/fusioncatcher/blob/master/doc/manual.md)!

>Note 3: In some cases it might not be enough to change the Python's path in .bashrc file, like for example the case when FusionCatcher is run on a server which defaults to another Python than one used to install FusionCatcher. In this case it is required that one changes all the shebangs of the all Python scripts which belong to FusionCatcher. In case that one uses the Python which has the following Python executable path /some/other/python than this can be done like this (it changes in place /usr/bin/env python into /some/other/python in all /apps/fusioncatcher/bin/*.py):
```
sed -i 's/\/usr\/bin\/env\ python/\/some\/other\/python/g' /apps/fusioncatcher/bin/*.py
```
