### ISSUE TITLE
output Spanning_pairs/Spanning_unique_reads

### ISSUE THREAD

**Issue by dinggens** [ndaniel/fusioncatcher#84]
Hello,
I just started applying FusionCatcher, and I have a problem now interpreting the related output.
Other fusion calling tools distinguish between split and spanning/bridge reads, i.e. the amount of reads aligning as a split read at the site of the fusion junction or the amount of fragments encompassing the fusion junction such that one read aligns to a different gene than the other PE read, respectively.
My question is whether the FusionCatcher output columns mentioned in the title here refer to the amount of split or spanning reads?
Many thanks in advance!

**Comment by ndaniel** [comment]
Hi,

FusionCatcher provides those in file `final-list_candidate-fusion-genes.txt`. More information about the columns of that file is in the documentation of FusionCatcher in Table 1 [here](https://github.com/ndaniel/fusioncatcher/blob/master/doc/manual.md#62---output-data-output-data).

**Comment by dinggens** [comment]
Thank you, but I was interested in whether the read support means SPLIT or BRIDGE read as decribed above. The documention just calls it "supporting/mapping" the junction.

**Comment by dinggens** [comment]
Thank you very much!

**Comment by xiucz** [comment]
hi, @ndaniel

Generally,  there are two kinds of  "spanning reads" and "junction reads",  I want to confirm here Spanning_unique_reads means spanning reads, and Spanning_pairs means junction reads, do you agree on it ?

Thank you.

**Comment by ndaniel** [comment]
This Figure illustrates the type of reads and pairs of reads used by FusionCatcher to support a fusion ![image](https://user-images.githubusercontent.com/161419/56863286-42aed400-69bd-11e9-8f0f-420874a99109.png)


**Spanning_pairs** = Count of pairs of reads supporting the fusion (including also the multimapping reads), like for example reads R1/1, R1/2, R2/1, R2/2 from the above figure

**Spanning_unique_reads** = Count of unique reads (i.e. unique mapping positions) mapping on the fusion junction. Shortly, here are counted all the reads which map on fusion junction minus the PCR duplicated reads, like for example reads R3/2 and R4/2 from the above figure.
