### ISSUE TITLE
A fusion between two repetitive regions that should be flagged

### ISSUE THREAD

**Issue by pmrotem** [ndaniel/fusioncatcher#86]
Hi Daniel,

We noticed a fusion between two genes, EP400  & NCOR2. The fusion occurs at a polyQ segment, and we think it should have been flagged.

It is the same run as in the previous issue:
https://owncloud.incpm.weizmann.ac.il/owncloud/index.php/s/GnMFv4lELikNByb

All the best,

Gil & Rotem

**Comment by ndaniel** [comment]
Thanks for reporting this. Do you mean that this should be flagged/tagged as false-positive fusion or as polyQ (or both)!

**Comment by gilhornung** [comment]
I noticed the polyQ when I looked at the supporting reads on IGV.

Not sure about the best flag... You have a flag for homologous sequences, right? Maybe that's the correct flag. Or maybe a new "polyQ" flag...

Gil

**Comment by ndaniel** [comment]
This will be fixed in release 1.1.

**Comment by ndaniel** [comment]
Fixed in release 1.10.
