### ISSUE TITLE
Error in line 315 during installation.

### ISSUE THREAD

**Issue by deppworld** [ndaniel/fusioncatcher#87]
I am trying to install fusioncatcher on my nworkstation but it is giving following error during bootstrap installation. 
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Checking latest version of Ensembl database that is available...")?

I  tried with following :

deepak@deepak-ngs:~$ wget http://sf.net/projects/fusioncatcher/files/bootstrap.py -O bootstrap.py && python bootstrap.py -t --download
--2018-04-12 18:17:53--  http://sf.net/projects/fusioncatcher/files/bootstrap.py
Resolving sf.net (sf.net)... 216.105.38.13
Connecting to sf.net (sf.net)|216.105.38.13|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sf.net/projects/fusioncatcher/files/bootstrap.py [following]
--2018-04-12 18:17:54--  https://sf.net/projects/fusioncatcher/files/bootstrap.py
Connecting to sf.net (sf.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sourceforge.net/projects/fusioncatcher/files/bootstrap.py [following]
--2018-04-12 18:17:56--  https://sourceforge.net/projects/fusioncatcher/files/bootstrap.py
Resolving sourceforge.net (sourceforge.net)... 216.105.38.13
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://sourceforge.net/projects/fusioncatcher/files/bootstrap.py/download [following]
--2018-04-12 18:17:58--  https://sourceforge.net/projects/fusioncatcher/files/bootstrap.py/download
Connecting to sourceforge.net (sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://downloads.sourceforge.net/project/fusioncatcher/bootstrap.py?r=&ts=1523537560&use_mirror=netix [following]
--2018-04-12 18:18:01--  https://downloads.sourceforge.net/project/fusioncatcher/bootstrap.py?r=&ts=1523537560&use_mirror=netix
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://netix.dl.sourceforge.net/project/fusioncatcher/bootstrap.py [following]
--2018-04-12 18:18:03--  https://netix.dl.sourceforge.net/project/fusioncatcher/bootstrap.py
Resolving netix.dl.sourceforge.net (netix.dl.sourceforge.net)... 87.121.121.2
Connecting to netix.dl.sourceforge.net (netix.dl.sourceforge.net)|87.121.121.2|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 96495 (94K) [application/octet-stream]
Saving to: ‘bootstrap.py’

bootstrap.py                                       100%[================================================================================================================>]  94.23K   237KB/s    in 0.4s    

2018-04-12 18:18:06 (237 KB/s) - ‘bootstrap.py’ saved [96495/96495]

  File "bootstrap.py", line 315
    print "Checking latest version of Ensembl database that is available..."
                                                                           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Checking latest version of Ensembl database that is available...")?

**Comment by ndaniel** [comment]
Hi!

I guess that probably your default Python is Pyhon version 3.x and the boostrap.py needs Python 2.7.
One can use the Python 2.x by specifying the path to it something like:

```
/some/path/to/python2.7 bootstrap.py -t --download
```

**Comment by deppworld** [comment]
@ndaniel Thanks !!!!!! for this...... Now working fine.
