### ISSUE TITLE
trying to use docker to run fusioncatcher.

### ISSUE THREAD

**Issue by HLAmolec** [ndaniel/fusioncatcher#90]
Hello Daniel,

I'm trying to use docker to run fusioncatcher. I've copied the Dockerfile you provided into a notepad and ran 
$ docker build - < /data/fusion_catcher_docker.txt
It built an image with some errors. 

Please see below:

E: Unable to locate package automake
E: Unable to locate package build-essential
E: Unable to locate package cmake
E: Unable to locate package curl
E: Unable to locate package gawk
E: Unable to locate package gcc
E: Unable to locate package libc6-dev
E: Unable to locate package libncurses5-dev
E: Unable to locate package libtbb2
E: Unable to locate package libtbb-dev
E: Package 'make' has no installation candidate
E: Unable to locate package parallel
E: Unable to locate package pigz
E: Unable to locate package python
E: Unable to locate package python-dev
E: Unable to locate package python-biopython
E: Unable to locate package python-numpy
E: Unable to locate package python-openpyxl
E: Unable to locate package python-xlrd
E: Unable to locate package unzip
E: Unable to locate package wget
E: Unable to locate package zip
E: Unable to locate package zlib1g-dev
E: Unable to locate package zlibc
E: Unable to locate package default-jdk

I'm trying to run the images as follows and it's not working.

docker run --rm -v /data:/data ab38bce870fc \
     /opt/fusioncatcher/v1.00/bin/fusioncatcher \
    -d /data/human_data/human_v90/ \
    -i /data/tumor/ \
    -o /data/output/

The error says it can't find fusioncatcher.

Please advise how to run the image.

Thanks,

Lena

**Comment by ndaniel** [comment]
Hi Lena,

thanks for the bug report!

I have not had time to check properly myself the docker file. Unfortunately, I do not have experience with docker.

Daniel

**Comment by ndaniel** [comment]
:-(
I will fix this but it will take a while.

**Comment by Selonka** [comment]
Hi,
I build the dockerfile today and everything worked fine for me, so there is maybe no bug in the file.

**Comment by ndaniel** [comment]
Ok.

**Comment by chadsmitharc** [comment]
Selonka,

Can you provide the docker command you used to build and execute fusion-catcher? Many thanks!
