### ISSUE TITLE
Installation error in bootstrap.py

### ISSUE THREAD

**Issue by deppworld** [ndaniel/fusioncatcher#92]
Hello 
I am installing fusioncatcher on Ubantu 18 but during installation I am facing following error. I am able to install SEQTK manually but how can I skip during automatic installation for other tools in pipeline.  

Installing tool 'SEQTK (Toolkit for processing sequences in FASTA/Q formats)' at '/home/deepak/n' from 'http://github.com/ndaniel/seqtk/archive/1.2-r101c.tar.gz'
    # mkdir -p /home/deepak
    # rm -rf /home/deepak/1.2-r101c.tar.gz
    # wget http://github.com/ndaniel/seqtk/archive/1.2-r101c.tar.gz -O /home/deepak/1.2-r101c.tar.gz --no-check-certificate
    # rm -rf /home/deepak/n
    # rm -rf /home/deepak/1.2-r101c
    # tar --overwrite -xvzf /home/deepak/1.2-r101c.tar.gz -C /home/deepak

  * ERROR: Unable to execute: 'tar --overwrite -xvzf /home/deepak/1.2-r101c.tar.gz -C /home/deepak' (shell = False)!

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by deppworld** [comment]
Issue resolved by editing bootstrap.py for SEQTK.

**Comment by ndaniel** [comment]
Ok. Anyway, please be aware that FusionCatcher needs a very custom made version of SEQTK, that is `http://github.com/ndaniel/seqtk/archive/1.2-r101c.tar.gz`. If anything else will be used, then it will not work well!
