### ISSUE TITLE
Make Database Installation optional for DockerContainers

### ISSUE THREAD

**Issue by Selonka** [ndaniel/fusioncatcher#95]
Hi,

at first, thank you for that nice tool and the comfortable installation script. But would it be possible to separate the database installation from the of the installation script?  So the databases can be installed/downloaded outside the container to the host? This would make the building process much faster and the container much lighter. Maybe you can add another command flag to specify the location of the database directory when running fusioncatcher.

VEP does it the same way if you are familiar with it ;)

Thank you and Greeting,

Selonka

**Comment by ndaniel** [comment]
That is a good idea!

**Comment by Selonka** [comment]
Hi,
 thank you for your quick response, I committed a new dockerfile and also a bash-script (altered from the script from bootstrap) to install the Database-files to a chosen destination on the host machine.
