### ISSUE TITLE
Long reads?

### ISSUE THREAD

**Issue by OxPen** [ndaniel/fusioncatcher#97]
Hi, 

Can I please ask if FusionCatcher is suitable also for longer reads data (eg Nanopore) and if not, what is the reason (aligner, error management etc)?

Thank you,

Peny

**Comment by ndaniel** [comment]
FusionCatcher was built for reads coming from sequencing platforms like Solexa/HiSeq/NextSeq/MiSeq/MiniSeq. Therefore it uses aligners which are used/built for these sequencing platforms, like for example Bowtie. Therefore probalby FusionCatcher will not be able to find fusions using  Nanopore reads.
