### ISSUE TITLE
Human genome build error

### ISSUE THREAD

**Issue by evagradovich** [ndaniel/fusioncatcher#98]
There is an error building a human genome when downloading the GTF GENCODE which is now available under a different link (please find below):

```ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.annotation.gtf.gz```

Would it be possible to incorporate this?

**Comment by ndaniel** [comment]
Thanks for reporting this!

Here is the patch: https://github.com/ndaniel/fusioncatcher/commit/c72c155a92a9e6c63619de019559ce6aae222ae9

**Comment by ndaniel** [comment]
Until this fix will be released in the next official release one can use the built-in data files for human: https://sourceforge.net/projects/fusioncatcher/files/data/
