### ISSUE TITLE
human data download failing due to discrepancy in version numbers

### ISSUE THREAD

**Issue by amirkdv** [ndaniel/fusioncatcher#99]
The available data files on sourceforge are currently at [`v_90`](https://sourceforge.net/projects/fusioncatcher/files/data/), the version in the fusioncatcher `bootstrap.py` script is [`v_91`](https://github.com/ndaniel/fusioncatcher/blob/978553100906c40e720a98fd2039169687686162/bin/bootstrap.py#L1130) and the auxiliary `download-data-human.sh` script is at [`v_87`](https://github.com/ndaniel/fusioncatcher/blob/978553100906c40e720a98fd2039169687686162/bin/download-data-human.sh#L7). This causes both methods of preparing fusionscript data to fail (via `bootstrap --download` or running the shell script manually), this also affects the docker build process which [calls](https://github.com/ndaniel/fusioncatcher/blob/978553100906c40e720a98fd2039169687686162/docker/Dockerfile#L48) the former. 

To be specific wrong URLs fed to `wget` still "work" but they leave an empty file with a non-200 code and then the checksum matching step crashes (as desired).

I don't know what your preferred practice is to keep these versions in sync. Either:

* fix them manually as sourceforge data evolves.
* have a single configuration file in `bin/` that contains the human data version as an env variable `HUMAN_VERSION=v_90` which is then sourced by all shell scripts and read from environment in python.

I can send you a pull request once you confirm which one you prefer.

**Comment by ndaniel** [comment]
Hi amirkdv!
> The available data files on sourceforge are currently at v_90, the version in the fusioncatcher bootstrap.py script is v_91

The data available currently at sourceforge is at v90 and bootstrap.py available at sourceforge.net is also at v90 (and not v91).

The script `bin/download.sh` is built at the moment of installation and therefore it should contain also v90.

It looks that there are several versions of FusionCatcher overwriting each other. FusionCatcher does not work well when it is updated by overwriting an older version. The official release of FusionCatcher is stored at sourceforge (so please do not mix the FusionCatcher from github with the one from sourceforge). Each new version of FusionCatcher needs to be installed in a new/empty path/folder.

There is only one vXX and that it is in the bootstrap.py, and bootstrap.py is using it anyway as optional (if  it detects some newer version).

You may send the pull request if you wish so.

**Comment by amirkdv** [comment]
@ndaniel thank you for your prompt response!

I didn't have different versions of fusioncatcher overwriting each other. I ran into the problem by:
1. clone this github repo
1. feed the Dockerfile into `docker build` and watch it crash because it would download empty files from sourceforge (because it had wrong versions and `wget` was downloading me empty files).
 
* You are correct that the bootstrap script on sourceforge is correctly in sync. So we will switch in our tooling to use sourceforge and that will solve the problem I was running into. Maybe it would be useful to have a warning on top of the github README advising people to not use this repo as the official fusioncatcher repo (I see that you have a link in the bottom).
* For future reference, or even for this issue, is the code from this repo fed into sourceforge in the end? For example, if a bug fix / new feature is discussed here and added to github repo will it eventually show up on sourceforge?
* FYI the `download-data-human.sh` is out of sync on sourceforge as well (it says `v_87`). And I'm not talking about the `download.sh` script that is created by `bootstrap.py`, but the separate script that exists in the `bin` directory which as far as I can tell has identical contents as the `download.sh` created by `bootstrap.py`. It is useful to have that script in the repo anyway, but it's your call to decide if it's legacy or should be maintained.

**Comment by ndaniel** [comment]
Hi @amirkdv ,

thanks for the feedback!
> For future reference, or even for this issue, is the code from this repo fed into sourceforge in the end? For example, if a bug fix / new feature is discussed here and added to github repo will it eventually show up on sourceforge?

Yes, in the end the code from GitHub might end up in many cases on SourceForge. GitHub can be considered as pre-alpha where different ideas are tested.

> FYI the download-data-human.sh is out of sync on sourceforge as well (it says v_87).

You are correct that the file `download-data-human.sh` exists on SourceForge and GitHub. That is a bug and that file should have been deleted long time ago. It is not needed anymore and it creates confusion. Thanks for bring it to my attention. I deleted it from GitHub and also I will delete it from the SourceForge in the next release.

>I think it would be best to fix the download.sh script produced by bootstrap.py to have set -e (instead of set +e, ignore failing commands) and fail gracefully instead of ignoring them.

Ok. I did this on GitHub and will be available in the next release on Sourceforge.

**Comment by amirkdv** [comment]
Thank you @ndaniel !
